dir: "mocks"
filename: "mock_{{.InterfaceName}}.go"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
packages:
  wealth-warden/internal/services:
    interfaces:
      AccountServiceInterface:
      AnalyticsServiceInterface:
      JobServiceInterface:
      TransactionServiceInterface:
      AuthServiceInterface:
      SessionsServiceInterface:
      NotesServiceInterface:
      RolePermissionServiceInterface:
      UserServiceInterface:
      BackofficeServiceInterface:
      ExportServiceInterface:
      ImportServiceInterface:
      SavingsServiceInterface:
      InvestmentServiceInterface:
  wealth-warden/pkg/validators:
    interfaces:
      Validator:
  wealth-warden/internal/middleware:
    interfaces:
      WebClientMiddlewareInterface:
