dir: "mocks"
filename: "mock_{{.InterfaceName}}.go"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
packages:
  wealth-warden/internal/services:
    interfaces:
      AccountServiceInterface:
      TransactionServiceInterface:
      AuthServiceInterface:
  wealth-warden/pkg/validators:
    interfaces:
      Validator:
  wealth-warden/internal/middleware:
    interfaces:
      WebClientMiddlewareInterface:
