with-expecter: true
dir: "mocks"
outpkg: mocks
packages:
  wealth-warden/internal/services:
    interfaces:
      AccountServiceInterface:
      TransactionServiceInterface:
  wealth-warden/pkg/validators:
    interfaces:
      Validator: