package models

import (
	"github.com/shopspring/decimal"
	"time"
)

const DefaultCurrency = "EUR"

type Account struct {
	ID            int64       `gorm:"primaryKey;autoIncrement" json:"id"`
	UserID        int64       `gorm:"not null;index:idx_accounts_user" json:"user_id"`
	Name          string      `gorm:"type:varchar(150);not null" json:"name"`
	AccountTypeID int64       `gorm:"not null" json:"account_type_id" validate:"required"`
	AccountType   AccountType `json:"account_type"`
	Balance       Balance     `json:"balance"`
	Currency      string      `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	CreatedAt     time.Time   `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt     time.Time   `gorm:"autoUpdateTime" json:"updated_at"`
}

type AccountType struct {
	ID             int64     `gorm:"primaryKey;autoIncrement" json:"id"`
	Type           string    `gorm:"type:varchar(150);not null" json:"type" validate:"required"`
	Subtype        *string   `gorm:"type:varchar(100)" json:"subtype" validate:"required"`
	Classification string    `gorm:"->;type:varchar(20)" json:"classification" validate:"required"`
	CreatedAt      time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt      time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

type Balance struct {
	ID              int64           `gorm:"primaryKey;autoIncrement" json:"id"`
	AccountID       int64           `gorm:"not null;index:idx_balances_account_asof" json:"account_id"`
	AsOf            time.Time       `gorm:"type:date;not null;index:idx_balances_account_asof" json:"as_of"`
	StartBalance    decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"start_balance"`
	CashInflows     decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"cash_inflows"`
	CashOutflows    decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"cash_outflows"`
	NonCashInflows  decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"non_cash_inflows"`
	NonCashOutflows decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"non_cash_outflows"`
	NetMarketFlows  decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"net_market_flows"`
	Adjustments     decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"adjustments"`
	EndBalance      decimal.Decimal `gorm:"->;type:decimal(19,4)" json:"end_balance"` // read-only, generated by DB
	Currency        string          `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	CreatedAt       time.Time       `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt       time.Time       `gorm:"autoUpdateTime" json:"updated_at"`
}

type AccountCreateReq struct {
	Name           string          `json:"name" validate:"required"`
	AccountTypeID  int64           `json:"account_type_id" validate:"required"`
	Type           string          `json:"type" validate:"required"`
	Subtype        string          `json:"subtype" validate:"required"`
	Classification string          `json:"classification" validate:"required"`
	Balance        decimal.Decimal `json:"balance" validate:"required"`
}
