package models

import "time"

const DefaultCurrency = "EUR"

type Account struct {
	ID            uint        `gorm:"primaryKey;autoIncrement" json:"id"`
	UserID        uint        `gorm:"not null;index:idx_accounts_user" json:"user_id"`
	Name          string      `gorm:"type:varchar(150);not null" json:"name"`
	AccountTypeID uint        `gorm:"not null" json:"account_type_id" validate:"required"`
	AccountType   AccountType `json:"account_type"`
	Balance       Balance     `json:"balance"`
	Currency      string      `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	CreatedAt     time.Time   `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt     time.Time   `gorm:"autoUpdateTime" json:"updated_at"`
}

type AccountType struct {
	ID             uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	Type           string    `gorm:"type:varchar(150);not null" json:"type" validate:"required"`
	Subtype        *string   `gorm:"type:varchar(100)" json:"subtype" validate:"required"`
	Classification string    `gorm:"->;type:varchar(20)" json:"classification" validate:"required"`
	CreatedAt      time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt      time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

type Balance struct {
	ID              uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	AccountID       uint      `gorm:"not null;index:idx_balances_account_asof" json:"account_id"`
	AsOf            time.Time `gorm:"type:date;not null;index:idx_balances_account_asof" json:"as_of"`
	StartBalance    float64   `gorm:"type:decimal(19,4);not null;default:0" json:"start_balance"`
	CashInflows     float64   `gorm:"type:decimal(19,4);not null;default:0" json:"cash_inflows"`
	CashOutflows    float64   `gorm:"type:decimal(19,4);not null;default:0" json:"cash_outflows"`
	NonCashInflows  float64   `gorm:"type:decimal(19,4);not null;default:0" json:"non_cash_inflows"`
	NonCashOutflows float64   `gorm:"type:decimal(19,4);not null;default:0" json:"non_cash_outflows"`
	NetMarketFlows  float64   `gorm:"type:decimal(19,4);not null;default:0" json:"net_market_flows"`
	Adjustments     float64   `gorm:"type:decimal(19,4);not null;default:0" json:"adjustments"`
	EndBalance      float64   `gorm:"->;type:decimal(19,4)" json:"end_balance"` // read-only, generated by DB
	Currency        string    `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	CreatedAt       time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt       time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

type AccountCreateReq struct {
	Name           string  `json:"name" validate:"required"`
	AccountTypeID  uint    `json:"account_type_id" validate:"required"`
	Type           string  `json:"type" validate:"required"`
	Subtype        string  `json:"subtype" validate:"required"`
	Classification string  `json:"classification" validate:"required"`
	Balance        float64 `json:"balance" validate:"required"`
}
