package models

import (
	"github.com/shopspring/decimal"
	"time"
)

type AccountBalance struct {
	AccountID int64           `gorm:"primaryKey" json:"account_id"`
	UserID    int64           `gorm:"not null" json:"user_id"`
	Currency  string          `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	Balance   decimal.Decimal `gorm:"type:numeric(19,4);not null;default:0" json:"balance"`
	UpdatedAt time.Time       `gorm:"autoUpdateTime" json:"updated_at"`
	CreatedAt time.Time       `gorm:"autoCreateTime" json:"created_at"`
}

type Balance struct {
	ID           int64           `gorm:"primaryKey;autoIncrement" json:"id"`
	AccountID    int64           `gorm:"not null;index:idx_balances_account_asof" json:"account_id"`
	AsOf         time.Time       `gorm:"type:date;not null;index:idx_balances_account_asof" json:"as_of"`
	StartBalance decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"start_balance"`
	CashInflows  decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"cash_inflows"`
	CashOutflows decimal.Decimal `gorm:"type:decimal(19,4);not null;default:0" json:"cash_outflows"`
	EndBalance   decimal.Decimal `gorm:"->;type:decimal(19,4)" json:"end_balance"` // read-only, generated by DB
	MarketValue  decimal.Decimal `gorm:"-" json:"market_value"`                    // populated from latest snapshot for investment/crypto accounts
	TotalBalance decimal.Decimal `gorm:"-" json:"total_balance"`                   // end_balance + market_value, computed in code
	Currency     string          `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	CreatedAt    time.Time       `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt    time.Time       `gorm:"autoUpdateTime" json:"updated_at"`
}
