package models

import "time"

type Balance struct {
	ID              uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	AccountID       uint64    `gorm:"not null;index:idx_balances_account_asof" json:"account_id"`
	AsOf            time.Time `gorm:"type:date;not null;index:idx_balances_account_asof" json:"as_of"`
	StartBalance    float64   `gorm:"type:decimal(19,4);not null;default:0" json:"start_balance"`
	CashInflows     float64   `gorm:"type:decimal(19,4);not null;default:0" json:"cash_inflows"`
	CashOutflows    float64   `gorm:"type:decimal(19,4);not null;default:0" json:"cash_outflows"`
	NonCashInflows  float64   `gorm:"type:decimal(19,4);not null;default:0" json:"non_cash_inflows"`
	NonCashOutflows float64   `gorm:"type:decimal(19,4);not null;default:0" json:"non_cash_outflows"`
	NetMarketFlows  float64   `gorm:"type:decimal(19,4);not null;default:0" json:"net_market_flows"`
	Adjustments     float64   `gorm:"type:decimal(19,4);not null;default:0" json:"adjustments"`
	EndBalance      float64   `gorm:"->;type:decimal(19,4)" json:"end_balance"` // read-only, generated by DB
	Currency        string    `gorm:"type:char(3);not null;default:'EUR'" json:"currency"`
	CreatedAt       time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt       time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}
