// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRolePermissionServiceInterface creates a new instance of MockRolePermissionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolePermissionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolePermissionServiceInterface {
	mock := &MockRolePermissionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolePermissionServiceInterface is an autogenerated mock type for the RolePermissionServiceInterface type
type MockRolePermissionServiceInterface struct {
	mock.Mock
}

type MockRolePermissionServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolePermissionServiceInterface) EXPECT() *MockRolePermissionServiceInterface_Expecter {
	return &MockRolePermissionServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteRole provides a mock function for the type MockRolePermissionServiceInterface
func (_mock *MockRolePermissionServiceInterface) DeleteRole(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRolePermissionServiceInterface_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockRolePermissionServiceInterface_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockRolePermissionServiceInterface_Expecter) DeleteRole(ctx any, userID any, id any) *MockRolePermissionServiceInterface_DeleteRole_Call {
	return &MockRolePermissionServiceInterface_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, userID, id)}
}

func (_c *MockRolePermissionServiceInterface_DeleteRole_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockRolePermissionServiceInterface_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolePermissionServiceInterface_DeleteRole_Call) Return(err error) *MockRolePermissionServiceInterface_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRolePermissionServiceInterface_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockRolePermissionServiceInterface_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllPermissions provides a mock function for the type MockRolePermissionServiceInterface
func (_mock *MockRolePermissionServiceInterface) FetchAllPermissions(ctx context.Context) ([]models.Permission, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllPermissions")
	}

	var r0 []models.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Permission, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Permission); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolePermissionServiceInterface_FetchAllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllPermissions'
type MockRolePermissionServiceInterface_FetchAllPermissions_Call struct {
	*mock.Call
}

// FetchAllPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRolePermissionServiceInterface_Expecter) FetchAllPermissions(ctx any) *MockRolePermissionServiceInterface_FetchAllPermissions_Call {
	return &MockRolePermissionServiceInterface_FetchAllPermissions_Call{Call: _e.mock.On("FetchAllPermissions", ctx)}
}

func (_c *MockRolePermissionServiceInterface_FetchAllPermissions_Call) Run(run func(ctx context.Context)) *MockRolePermissionServiceInterface_FetchAllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRolePermissionServiceInterface_FetchAllPermissions_Call) Return(permissions []models.Permission, err error) *MockRolePermissionServiceInterface_FetchAllPermissions_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockRolePermissionServiceInterface_FetchAllPermissions_Call) RunAndReturn(run func(ctx context.Context) ([]models.Permission, error)) *MockRolePermissionServiceInterface_FetchAllPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllRoles provides a mock function for the type MockRolePermissionServiceInterface
func (_mock *MockRolePermissionServiceInterface) FetchAllRoles(ctx context.Context, withPermissions bool) ([]models.Role, error) {
	ret := _mock.Called(ctx, withPermissions)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllRoles")
	}

	var r0 []models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]models.Role, error)); ok {
		return returnFunc(ctx, withPermissions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []models.Role); ok {
		r0 = returnFunc(ctx, withPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, withPermissions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolePermissionServiceInterface_FetchAllRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllRoles'
type MockRolePermissionServiceInterface_FetchAllRoles_Call struct {
	*mock.Call
}

// FetchAllRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - withPermissions bool
func (_e *MockRolePermissionServiceInterface_Expecter) FetchAllRoles(ctx any, withPermissions any) *MockRolePermissionServiceInterface_FetchAllRoles_Call {
	return &MockRolePermissionServiceInterface_FetchAllRoles_Call{Call: _e.mock.On("FetchAllRoles", ctx, withPermissions)}
}

func (_c *MockRolePermissionServiceInterface_FetchAllRoles_Call) Run(run func(ctx context.Context, withPermissions bool)) *MockRolePermissionServiceInterface_FetchAllRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRolePermissionServiceInterface_FetchAllRoles_Call) Return(roles []models.Role, err error) *MockRolePermissionServiceInterface_FetchAllRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRolePermissionServiceInterface_FetchAllRoles_Call) RunAndReturn(run func(ctx context.Context, withPermissions bool) ([]models.Role, error)) *MockRolePermissionServiceInterface_FetchAllRoles_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRoleByID provides a mock function for the type MockRolePermissionServiceInterface
func (_mock *MockRolePermissionServiceInterface) FetchRoleByID(ctx context.Context, ID int64, withPermissions bool) (*models.Role, error) {
	ret := _mock.Called(ctx, ID, withPermissions)

	if len(ret) == 0 {
		panic("no return value specified for FetchRoleByID")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (*models.Role, error)); ok {
		return returnFunc(ctx, ID, withPermissions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) *models.Role); ok {
		r0 = returnFunc(ctx, ID, withPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, ID, withPermissions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolePermissionServiceInterface_FetchRoleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRoleByID'
type MockRolePermissionServiceInterface_FetchRoleByID_Call struct {
	*mock.Call
}

// FetchRoleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
//   - withPermissions bool
func (_e *MockRolePermissionServiceInterface_Expecter) FetchRoleByID(ctx any, ID any, withPermissions any) *MockRolePermissionServiceInterface_FetchRoleByID_Call {
	return &MockRolePermissionServiceInterface_FetchRoleByID_Call{Call: _e.mock.On("FetchRoleByID", ctx, ID, withPermissions)}
}

func (_c *MockRolePermissionServiceInterface_FetchRoleByID_Call) Run(run func(ctx context.Context, ID int64, withPermissions bool)) *MockRolePermissionServiceInterface_FetchRoleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolePermissionServiceInterface_FetchRoleByID_Call) Return(role *models.Role, err error) *MockRolePermissionServiceInterface_FetchRoleByID_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRolePermissionServiceInterface_FetchRoleByID_Call) RunAndReturn(run func(ctx context.Context, ID int64, withPermissions bool) (*models.Role, error)) *MockRolePermissionServiceInterface_FetchRoleByID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRole provides a mock function for the type MockRolePermissionServiceInterface
func (_mock *MockRolePermissionServiceInterface) InsertRole(ctx context.Context, userID int64, req models.RoleReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertRole")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.RoleReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.RoleReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, models.RoleReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolePermissionServiceInterface_InsertRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRole'
type MockRolePermissionServiceInterface_InsertRole_Call struct {
	*mock.Call
}

// InsertRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req models.RoleReq
func (_e *MockRolePermissionServiceInterface_Expecter) InsertRole(ctx any, userID any, req any) *MockRolePermissionServiceInterface_InsertRole_Call {
	return &MockRolePermissionServiceInterface_InsertRole_Call{Call: _e.mock.On("InsertRole", ctx, userID, req)}
}

func (_c *MockRolePermissionServiceInterface_InsertRole_Call) Run(run func(ctx context.Context, userID int64, req models.RoleReq)) *MockRolePermissionServiceInterface_InsertRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.RoleReq
		if args[2] != nil {
			arg2 = args[2].(models.RoleReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolePermissionServiceInterface_InsertRole_Call) Return(n int64, err error) *MockRolePermissionServiceInterface_InsertRole_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRolePermissionServiceInterface_InsertRole_Call) RunAndReturn(run func(ctx context.Context, userID int64, req models.RoleReq) (int64, error)) *MockRolePermissionServiceInterface_InsertRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockRolePermissionServiceInterface
func (_mock *MockRolePermissionServiceInterface) UpdateRole(ctx context.Context, userID int64, id int64, req *models.RoleReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.RoleReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.RoleReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.RoleReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolePermissionServiceInterface_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockRolePermissionServiceInterface_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.RoleReq
func (_e *MockRolePermissionServiceInterface_Expecter) UpdateRole(ctx any, userID any, id any, req any) *MockRolePermissionServiceInterface_UpdateRole_Call {
	return &MockRolePermissionServiceInterface_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, userID, id, req)}
}

func (_c *MockRolePermissionServiceInterface_UpdateRole_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.RoleReq)) *MockRolePermissionServiceInterface_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.RoleReq
		if args[3] != nil {
			arg3 = args[3].(*models.RoleReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRolePermissionServiceInterface_UpdateRole_Call) Return(n int64, err error) *MockRolePermissionServiceInterface_UpdateRole_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRolePermissionServiceInterface_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.RoleReq) (int64, error)) *MockRolePermissionServiceInterface_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
