// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBackofficeServiceInterface creates a new instance of MockBackofficeServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackofficeServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackofficeServiceInterface {
	mock := &MockBackofficeServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackofficeServiceInterface is an autogenerated mock type for the BackofficeServiceInterface type
type MockBackofficeServiceInterface struct {
	mock.Mock
}

type MockBackofficeServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackofficeServiceInterface) EXPECT() *MockBackofficeServiceInterface_Expecter {
	return &MockBackofficeServiceInterface_Expecter{mock: &_m.Mock}
}

// BackfillAssetCashFlows provides a mock function for the type MockBackofficeServiceInterface
func (_mock *MockBackofficeServiceInterface) BackfillAssetCashFlows(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BackfillAssetCashFlows")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackofficeServiceInterface_BackfillAssetCashFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackfillAssetCashFlows'
type MockBackofficeServiceInterface_BackfillAssetCashFlows_Call struct {
	*mock.Call
}

// BackfillAssetCashFlows is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackofficeServiceInterface_Expecter) BackfillAssetCashFlows(ctx any) *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call {
	return &MockBackofficeServiceInterface_BackfillAssetCashFlows_Call{Call: _e.mock.On("BackfillAssetCashFlows", ctx)}
}

func (_c *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call) Run(run func(ctx context.Context)) *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call) Return(err error) *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call) RunAndReturn(run func(ctx context.Context) error) *MockBackofficeServiceInterface_BackfillAssetCashFlows_Call {
	_c.Call.Return(run)
	return _c
}

// BackfillIncomeExchangeRates provides a mock function for the type MockBackofficeServiceInterface
func (_mock *MockBackofficeServiceInterface) BackfillIncomeExchangeRates(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BackfillIncomeExchangeRates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackfillIncomeExchangeRates'
type MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call struct {
	*mock.Call
}

// BackfillIncomeExchangeRates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackofficeServiceInterface_Expecter) BackfillIncomeExchangeRates(ctx any) *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call {
	return &MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call{Call: _e.mock.On("BackfillIncomeExchangeRates", ctx)}
}

func (_c *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call) Run(run func(ctx context.Context)) *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call) Return(err error) *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call) RunAndReturn(run func(ctx context.Context) error) *MockBackofficeServiceInterface_BackfillIncomeExchangeRates_Call {
	_c.Call.Return(run)
	return _c
}

// CorrectFeeAccounting provides a mock function for the type MockBackofficeServiceInterface
func (_mock *MockBackofficeServiceInterface) CorrectFeeAccounting(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CorrectFeeAccounting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackofficeServiceInterface_CorrectFeeAccounting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CorrectFeeAccounting'
type MockBackofficeServiceInterface_CorrectFeeAccounting_Call struct {
	*mock.Call
}

// CorrectFeeAccounting is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackofficeServiceInterface_Expecter) CorrectFeeAccounting(ctx any) *MockBackofficeServiceInterface_CorrectFeeAccounting_Call {
	return &MockBackofficeServiceInterface_CorrectFeeAccounting_Call{Call: _e.mock.On("CorrectFeeAccounting", ctx)}
}

func (_c *MockBackofficeServiceInterface_CorrectFeeAccounting_Call) Run(run func(ctx context.Context)) *MockBackofficeServiceInterface_CorrectFeeAccounting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackofficeServiceInterface_CorrectFeeAccounting_Call) Return(err error) *MockBackofficeServiceInterface_CorrectFeeAccounting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackofficeServiceInterface_CorrectFeeAccounting_Call) RunAndReturn(run func(ctx context.Context) error) *MockBackofficeServiceInterface_CorrectFeeAccounting_Call {
	_c.Call.Return(run)
	return _c
}

// MigrateZeroCostTrades provides a mock function for the type MockBackofficeServiceInterface
func (_mock *MockBackofficeServiceInterface) MigrateZeroCostTrades(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MigrateZeroCostTrades")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackofficeServiceInterface_MigrateZeroCostTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateZeroCostTrades'
type MockBackofficeServiceInterface_MigrateZeroCostTrades_Call struct {
	*mock.Call
}

// MigrateZeroCostTrades is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackofficeServiceInterface_Expecter) MigrateZeroCostTrades(ctx any) *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call {
	return &MockBackofficeServiceInterface_MigrateZeroCostTrades_Call{Call: _e.mock.On("MigrateZeroCostTrades", ctx)}
}

func (_c *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call) Run(run func(ctx context.Context)) *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call) Return(err error) *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call) RunAndReturn(run func(ctx context.Context) error) *MockBackofficeServiceInterface_MigrateZeroCostTrades_Call {
	_c.Call.Return(run)
	return _c
}

// RunZeroCostTradeMigration provides a mock function for the type MockBackofficeServiceInterface
func (_mock *MockBackofficeServiceInterface) RunZeroCostTradeMigration(ctx context.Context) (*models.ZeroCostMigrationResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunZeroCostTradeMigration")
	}

	var r0 *models.ZeroCostMigrationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.ZeroCostMigrationResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.ZeroCostMigrationResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ZeroCostMigrationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunZeroCostTradeMigration'
type MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call struct {
	*mock.Call
}

// RunZeroCostTradeMigration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackofficeServiceInterface_Expecter) RunZeroCostTradeMigration(ctx any) *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call {
	return &MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call{Call: _e.mock.On("RunZeroCostTradeMigration", ctx)}
}

func (_c *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call) Run(run func(ctx context.Context)) *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call) Return(zeroCostMigrationResult *models.ZeroCostMigrationResult, err error) *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call {
	_c.Call.Return(zeroCostMigrationResult, err)
	return _c
}

func (_c *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call) RunAndReturn(run func(ctx context.Context) (*models.ZeroCostMigrationResult, error)) *MockBackofficeServiceInterface_RunZeroCostTradeMigration_Call {
	_c.Call.Return(run)
	return _c
}
