// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"wealth-warden/internal/models"
	"wealth-warden/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsServiceInterface creates a new instance of MockAnalyticsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsServiceInterface {
	mock := &MockAnalyticsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsServiceInterface is an autogenerated mock type for the AnalyticsServiceInterface type
type MockAnalyticsServiceInterface struct {
	mock.Mock
}

type MockAnalyticsServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsServiceInterface) EXPECT() *MockAnalyticsServiceInterface_Expecter {
	return &MockAnalyticsServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteReport provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) DeleteReport(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalyticsServiceInterface_DeleteReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReport'
type MockAnalyticsServiceInterface_DeleteReport_Call struct {
	*mock.Call
}

// DeleteReport is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockAnalyticsServiceInterface_Expecter) DeleteReport(ctx any, userID any, id any) *MockAnalyticsServiceInterface_DeleteReport_Call {
	return &MockAnalyticsServiceInterface_DeleteReport_Call{Call: _e.mock.On("DeleteReport", ctx, userID, id)}
}

func (_c *MockAnalyticsServiceInterface_DeleteReport_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockAnalyticsServiceInterface_DeleteReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_DeleteReport_Call) Return(err error) *MockAnalyticsServiceInterface_DeleteReport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_DeleteReport_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockAnalyticsServiceInterface_DeleteReport_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadReport provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) DownloadReport(ctx context.Context, id int64, userID int64) ([]byte, string, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadReport")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]byte, string, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []byte); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) string); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, int64) error); ok {
		r2 = returnFunc(ctx, id, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAnalyticsServiceInterface_DownloadReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadReport'
type MockAnalyticsServiceInterface_DownloadReport_Call struct {
	*mock.Call
}

// DownloadReport is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
func (_e *MockAnalyticsServiceInterface_Expecter) DownloadReport(ctx any, id any, userID any) *MockAnalyticsServiceInterface_DownloadReport_Call {
	return &MockAnalyticsServiceInterface_DownloadReport_Call{Call: _e.mock.On("DownloadReport", ctx, id, userID)}
}

func (_c *MockAnalyticsServiceInterface_DownloadReport_Call) Run(run func(ctx context.Context, id int64, userID int64)) *MockAnalyticsServiceInterface_DownloadReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_DownloadReport_Call) Return(bytes []byte, s string, err error) *MockAnalyticsServiceInterface_DownloadReport_Call {
	_c.Call.Return(bytes, s, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_DownloadReport_Call) RunAndReturn(run func(ctx context.Context, id int64, userID int64) ([]byte, string, error)) *MockAnalyticsServiceInterface_DownloadReport_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAssetChart provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) FetchAssetChart(ctx context.Context, userID int64, assetID int64, rangeKey string) (*models.AssetChartResponse, error) {
	ret := _mock.Called(ctx, userID, assetID, rangeKey)

	if len(ret) == 0 {
		panic("no return value specified for FetchAssetChart")
	}

	var r0 *models.AssetChartResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) (*models.AssetChartResponse, error)); ok {
		return returnFunc(ctx, userID, assetID, rangeKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) *models.AssetChartResponse); ok {
		r0 = returnFunc(ctx, userID, assetID, rangeKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AssetChartResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, assetID, rangeKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_FetchAssetChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAssetChart'
type MockAnalyticsServiceInterface_FetchAssetChart_Call struct {
	*mock.Call
}

// FetchAssetChart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - assetID int64
//   - rangeKey string
func (_e *MockAnalyticsServiceInterface_Expecter) FetchAssetChart(ctx any, userID any, assetID any, rangeKey any) *MockAnalyticsServiceInterface_FetchAssetChart_Call {
	return &MockAnalyticsServiceInterface_FetchAssetChart_Call{Call: _e.mock.On("FetchAssetChart", ctx, userID, assetID, rangeKey)}
}

func (_c *MockAnalyticsServiceInterface_FetchAssetChart_Call) Run(run func(ctx context.Context, userID int64, assetID int64, rangeKey string)) *MockAnalyticsServiceInterface_FetchAssetChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_FetchAssetChart_Call) Return(assetChartResponse *models.AssetChartResponse, err error) *MockAnalyticsServiceInterface_FetchAssetChart_Call {
	_c.Call.Return(assetChartResponse, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_FetchAssetChart_Call) RunAndReturn(run func(ctx context.Context, userID int64, assetID int64, rangeKey string) (*models.AssetChartResponse, error)) *MockAnalyticsServiceInterface_FetchAssetChart_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCategoryReportData provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) FetchCategoryReportData(ctx context.Context, userID int64, params models.CategoryReportParams) ([]models.CategoryReportDataRow, error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for FetchCategoryReportData")
	}

	var r0 []models.CategoryReportDataRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.CategoryReportParams) ([]models.CategoryReportDataRow, error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.CategoryReportParams) []models.CategoryReportDataRow); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CategoryReportDataRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, models.CategoryReportParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_FetchCategoryReportData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCategoryReportData'
type MockAnalyticsServiceInterface_FetchCategoryReportData_Call struct {
	*mock.Call
}

// FetchCategoryReportData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - params models.CategoryReportParams
func (_e *MockAnalyticsServiceInterface_Expecter) FetchCategoryReportData(ctx any, userID any, params any) *MockAnalyticsServiceInterface_FetchCategoryReportData_Call {
	return &MockAnalyticsServiceInterface_FetchCategoryReportData_Call{Call: _e.mock.On("FetchCategoryReportData", ctx, userID, params)}
}

func (_c *MockAnalyticsServiceInterface_FetchCategoryReportData_Call) Run(run func(ctx context.Context, userID int64, params models.CategoryReportParams)) *MockAnalyticsServiceInterface_FetchCategoryReportData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.CategoryReportParams
		if args[2] != nil {
			arg2 = args[2].(models.CategoryReportParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_FetchCategoryReportData_Call) Return(categoryReportDataRows []models.CategoryReportDataRow, err error) *MockAnalyticsServiceInterface_FetchCategoryReportData_Call {
	_c.Call.Return(categoryReportDataRows, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_FetchCategoryReportData_Call) RunAndReturn(run func(ctx context.Context, userID int64, params models.CategoryReportParams) ([]models.CategoryReportDataRow, error)) *MockAnalyticsServiceInterface_FetchCategoryReportData_Call {
	_c.Call.Return(run)
	return _c
}

// FindReportAccountScope provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) FindReportAccountScope(ctx context.Context, userID int64, accountID int64) (*models.ReportAccountScope, error) {
	ret := _mock.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for FindReportAccountScope")
	}

	var r0 *models.ReportAccountScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.ReportAccountScope, error)); ok {
		return returnFunc(ctx, userID, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.ReportAccountScope); ok {
		r0 = returnFunc(ctx, userID, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReportAccountScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_FindReportAccountScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReportAccountScope'
type MockAnalyticsServiceInterface_FindReportAccountScope_Call struct {
	*mock.Call
}

// FindReportAccountScope is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID int64
func (_e *MockAnalyticsServiceInterface_Expecter) FindReportAccountScope(ctx any, userID any, accountID any) *MockAnalyticsServiceInterface_FindReportAccountScope_Call {
	return &MockAnalyticsServiceInterface_FindReportAccountScope_Call{Call: _e.mock.On("FindReportAccountScope", ctx, userID, accountID)}
}

func (_c *MockAnalyticsServiceInterface_FindReportAccountScope_Call) Run(run func(ctx context.Context, userID int64, accountID int64)) *MockAnalyticsServiceInterface_FindReportAccountScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_FindReportAccountScope_Call) Return(reportAccountScope *models.ReportAccountScope, err error) *MockAnalyticsServiceInterface_FindReportAccountScope_Call {
	_c.Call.Return(reportAccountScope, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_FindReportAccountScope_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID int64) (*models.ReportAccountScope, error)) *MockAnalyticsServiceInterface_FindReportAccountScope_Call {
	_c.Call.Return(run)
	return _c
}

// FindReportByID provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) FindReportByID(ctx context.Context, id int64, userID int64) (*models.Report, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindReportByID")
	}

	var r0 *models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.Report, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.Report); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_FindReportByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReportByID'
type MockAnalyticsServiceInterface_FindReportByID_Call struct {
	*mock.Call
}

// FindReportByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
func (_e *MockAnalyticsServiceInterface_Expecter) FindReportByID(ctx any, id any, userID any) *MockAnalyticsServiceInterface_FindReportByID_Call {
	return &MockAnalyticsServiceInterface_FindReportByID_Call{Call: _e.mock.On("FindReportByID", ctx, id, userID)}
}

func (_c *MockAnalyticsServiceInterface_FindReportByID_Call) Run(run func(ctx context.Context, id int64, userID int64)) *MockAnalyticsServiceInterface_FindReportByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_FindReportByID_Call) Return(report *models.Report, err error) *MockAnalyticsServiceInterface_FindReportByID_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_FindReportByID_Call) RunAndReturn(run func(ctx context.Context, id int64, userID int64) (*models.Report, error)) *MockAnalyticsServiceInterface_FindReportByID_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCategoryReport provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GenerateCategoryReport(ctx context.Context, userID int64, params models.CategoryReportParams) (*models.Report, error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCategoryReport")
	}

	var r0 *models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.CategoryReportParams) (*models.Report, error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.CategoryReportParams) *models.Report); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, models.CategoryReportParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GenerateCategoryReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCategoryReport'
type MockAnalyticsServiceInterface_GenerateCategoryReport_Call struct {
	*mock.Call
}

// GenerateCategoryReport is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - params models.CategoryReportParams
func (_e *MockAnalyticsServiceInterface_Expecter) GenerateCategoryReport(ctx any, userID any, params any) *MockAnalyticsServiceInterface_GenerateCategoryReport_Call {
	return &MockAnalyticsServiceInterface_GenerateCategoryReport_Call{Call: _e.mock.On("GenerateCategoryReport", ctx, userID, params)}
}

func (_c *MockAnalyticsServiceInterface_GenerateCategoryReport_Call) Run(run func(ctx context.Context, userID int64, params models.CategoryReportParams)) *MockAnalyticsServiceInterface_GenerateCategoryReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.CategoryReportParams
		if args[2] != nil {
			arg2 = args[2].(models.CategoryReportParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GenerateCategoryReport_Call) Return(report *models.Report, err error) *MockAnalyticsServiceInterface_GenerateCategoryReport_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GenerateCategoryReport_Call) RunAndReturn(run func(ctx context.Context, userID int64, params models.CategoryReportParams) (*models.Report, error)) *MockAnalyticsServiceInterface_GenerateCategoryReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountBasicStatistics provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetAccountBasicStatistics(ctx context.Context, accID *int64, userID int64, year int) (*models.BasicAccountStats, error) {
	ret := _mock.Called(ctx, accID, userID, year)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountBasicStatistics")
	}

	var r0 *models.BasicAccountStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int64, int) (*models.BasicAccountStats, error)); ok {
		return returnFunc(ctx, accID, userID, year)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int64, int) *models.BasicAccountStats); ok {
		r0 = returnFunc(ctx, accID, userID, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BasicAccountStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64, int64, int) error); ok {
		r1 = returnFunc(ctx, accID, userID, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountBasicStatistics'
type MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call struct {
	*mock.Call
}

// GetAccountBasicStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - accID *int64
//   - userID int64
//   - year int
func (_e *MockAnalyticsServiceInterface_Expecter) GetAccountBasicStatistics(ctx any, accID any, userID any, year any) *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call {
	return &MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call{Call: _e.mock.On("GetAccountBasicStatistics", ctx, accID, userID, year)}
}

func (_c *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call) Run(run func(ctx context.Context, accID *int64, userID int64, year int)) *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call) Return(basicAccountStats *models.BasicAccountStats, err error) *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call {
	_c.Call.Return(basicAccountStats, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call) RunAndReturn(run func(ctx context.Context, accID *int64, userID int64, year int) (*models.BasicAccountStats, error)) *MockAnalyticsServiceInterface_GetAccountBasicStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableStatsYears provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetAvailableStatsYears(ctx context.Context, accID *int64, userID int64, includeMonths bool) ([]models.AvailableStatsYear, error) {
	ret := _mock.Called(ctx, accID, userID, includeMonths)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableStatsYears")
	}

	var r0 []models.AvailableStatsYear
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int64, bool) ([]models.AvailableStatsYear, error)); ok {
		return returnFunc(ctx, accID, userID, includeMonths)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int64, bool) []models.AvailableStatsYear); ok {
		r0 = returnFunc(ctx, accID, userID, includeMonths)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AvailableStatsYear)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64, int64, bool) error); ok {
		r1 = returnFunc(ctx, accID, userID, includeMonths)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetAvailableStatsYears_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableStatsYears'
type MockAnalyticsServiceInterface_GetAvailableStatsYears_Call struct {
	*mock.Call
}

// GetAvailableStatsYears is a helper method to define mock.On call
//   - ctx context.Context
//   - accID *int64
//   - userID int64
//   - includeMonths bool
func (_e *MockAnalyticsServiceInterface_Expecter) GetAvailableStatsYears(ctx any, accID any, userID any, includeMonths any) *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call {
	return &MockAnalyticsServiceInterface_GetAvailableStatsYears_Call{Call: _e.mock.On("GetAvailableStatsYears", ctx, accID, userID, includeMonths)}
}

func (_c *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call) Run(run func(ctx context.Context, accID *int64, userID int64, includeMonths bool)) *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call) Return(availableStatsYears []models.AvailableStatsYear, err error) *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call {
	_c.Call.Return(availableStatsYears, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call) RunAndReturn(run func(ctx context.Context, accID *int64, userID int64, includeMonths bool) ([]models.AvailableStatsYear, error)) *MockAnalyticsServiceInterface_GetAvailableStatsYears_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryUsageForYear provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetCategoryUsageForYear(ctx context.Context, userID int64, year int, class string, accID *int64, catID *int64, asPercent bool) (*models.CategoryUsageResponse, error) {
	ret := _mock.Called(ctx, userID, year, class, accID, catID, asPercent)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryUsageForYear")
	}

	var r0 *models.CategoryUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, string, *int64, *int64, bool) (*models.CategoryUsageResponse, error)); ok {
		return returnFunc(ctx, userID, year, class, accID, catID, asPercent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, string, *int64, *int64, bool) *models.CategoryUsageResponse); ok {
		r0 = returnFunc(ctx, userID, year, class, accID, catID, asPercent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CategoryUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, string, *int64, *int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, year, class, accID, catID, asPercent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryUsageForYear'
type MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call struct {
	*mock.Call
}

// GetCategoryUsageForYear is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - year int
//   - class string
//   - accID *int64
//   - catID *int64
//   - asPercent bool
func (_e *MockAnalyticsServiceInterface_Expecter) GetCategoryUsageForYear(ctx any, userID any, year any, class any, accID any, catID any, asPercent any) *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call {
	return &MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call{Call: _e.mock.On("GetCategoryUsageForYear", ctx, userID, year, class, accID, catID, asPercent)}
}

func (_c *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call) Run(run func(ctx context.Context, userID int64, year int, class string, accID *int64, catID *int64, asPercent bool)) *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *int64
		if args[5] != nil {
			arg5 = args[5].(*int64)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call) Return(categoryUsageResponse *models.CategoryUsageResponse, err error) *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call {
	_c.Call.Return(categoryUsageResponse, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call) RunAndReturn(run func(ctx context.Context, userID int64, year int, class string, accID *int64, catID *int64, asPercent bool) (*models.CategoryUsageResponse, error)) *MockAnalyticsServiceInterface_GetCategoryUsageForYear_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryUsageForYears provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetCategoryUsageForYears(ctx context.Context, userID int64, years []int, class string, accID *int64, catID *int64, asPercent bool) (*models.MultiYearCategoryUsageResponse, error) {
	ret := _mock.Called(ctx, userID, years, class, accID, catID, asPercent)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryUsageForYears")
	}

	var r0 *models.MultiYearCategoryUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []int, string, *int64, *int64, bool) (*models.MultiYearCategoryUsageResponse, error)); ok {
		return returnFunc(ctx, userID, years, class, accID, catID, asPercent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []int, string, *int64, *int64, bool) *models.MultiYearCategoryUsageResponse); ok {
		r0 = returnFunc(ctx, userID, years, class, accID, catID, asPercent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MultiYearCategoryUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, []int, string, *int64, *int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, years, class, accID, catID, asPercent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryUsageForYears'
type MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call struct {
	*mock.Call
}

// GetCategoryUsageForYears is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - years []int
//   - class string
//   - accID *int64
//   - catID *int64
//   - asPercent bool
func (_e *MockAnalyticsServiceInterface_Expecter) GetCategoryUsageForYears(ctx any, userID any, years any, class any, accID any, catID any, asPercent any) *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call {
	return &MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call{Call: _e.mock.On("GetCategoryUsageForYears", ctx, userID, years, class, accID, catID, asPercent)}
}

func (_c *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call) Run(run func(ctx context.Context, userID int64, years []int, class string, accID *int64, catID *int64, asPercent bool)) *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *int64
		if args[5] != nil {
			arg5 = args[5].(*int64)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call) Return(multiYearCategoryUsageResponse *models.MultiYearCategoryUsageResponse, err error) *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call {
	_c.Call.Return(multiYearCategoryUsageResponse, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call) RunAndReturn(run func(ctx context.Context, userID int64, years []int, class string, accID *int64, catID *int64, asPercent bool) (*models.MultiYearCategoryUsageResponse, error)) *MockAnalyticsServiceInterface_GetCategoryUsageForYears_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyStats provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetMonthlyStats(ctx context.Context, userID int64, accountID *int64, year int, month int) (*models.MonthlyStats, error) {
	ret := _mock.Called(ctx, userID, accountID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyStats")
	}

	var r0 *models.MonthlyStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64, int, int) (*models.MonthlyStats, error)); ok {
		return returnFunc(ctx, userID, accountID, year, month)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64, int, int) *models.MonthlyStats); ok {
		r0 = returnFunc(ctx, userID, accountID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MonthlyStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *int64, int, int) error); ok {
		r1 = returnFunc(ctx, userID, accountID, year, month)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetMonthlyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyStats'
type MockAnalyticsServiceInterface_GetMonthlyStats_Call struct {
	*mock.Call
}

// GetMonthlyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID *int64
//   - year int
//   - month int
func (_e *MockAnalyticsServiceInterface_Expecter) GetMonthlyStats(ctx any, userID any, accountID any, year any, month any) *MockAnalyticsServiceInterface_GetMonthlyStats_Call {
	return &MockAnalyticsServiceInterface_GetMonthlyStats_Call{Call: _e.mock.On("GetMonthlyStats", ctx, userID, accountID, year, month)}
}

func (_c *MockAnalyticsServiceInterface_GetMonthlyStats_Call) Run(run func(ctx context.Context, userID int64, accountID *int64, year int, month int)) *MockAnalyticsServiceInterface_GetMonthlyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetMonthlyStats_Call) Return(monthlyStats *models.MonthlyStats, err error) *MockAnalyticsServiceInterface_GetMonthlyStats_Call {
	_c.Call.Return(monthlyStats, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetMonthlyStats_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID *int64, year int, month int) (*models.MonthlyStats, error)) *MockAnalyticsServiceInterface_GetMonthlyStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetWorthSeries provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetNetWorthSeries(ctx context.Context, userID int64, currency string, rangeKey string, from string, to string, accountID *int64) (*models.NetWorthResponse, error) {
	ret := _mock.Called(ctx, userID, currency, rangeKey, from, to, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetNetWorthSeries")
	}

	var r0 *models.NetWorthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, *int64) (*models.NetWorthResponse, error)); ok {
		return returnFunc(ctx, userID, currency, rangeKey, from, to, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, *int64) *models.NetWorthResponse); ok {
		r0 = returnFunc(ctx, userID, currency, rangeKey, from, to, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NetWorthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, string, string, *int64) error); ok {
		r1 = returnFunc(ctx, userID, currency, rangeKey, from, to, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetNetWorthSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetWorthSeries'
type MockAnalyticsServiceInterface_GetNetWorthSeries_Call struct {
	*mock.Call
}

// GetNetWorthSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currency string
//   - rangeKey string
//   - from string
//   - to string
//   - accountID *int64
func (_e *MockAnalyticsServiceInterface_Expecter) GetNetWorthSeries(ctx any, userID any, currency any, rangeKey any, from any, to any, accountID any) *MockAnalyticsServiceInterface_GetNetWorthSeries_Call {
	return &MockAnalyticsServiceInterface_GetNetWorthSeries_Call{Call: _e.mock.On("GetNetWorthSeries", ctx, userID, currency, rangeKey, from, to, accountID)}
}

func (_c *MockAnalyticsServiceInterface_GetNetWorthSeries_Call) Run(run func(ctx context.Context, userID int64, currency string, rangeKey string, from string, to string, accountID *int64)) *MockAnalyticsServiceInterface_GetNetWorthSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 *int64
		if args[6] != nil {
			arg6 = args[6].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetNetWorthSeries_Call) Return(netWorthResponse *models.NetWorthResponse, err error) *MockAnalyticsServiceInterface_GetNetWorthSeries_Call {
	_c.Call.Return(netWorthResponse, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetNetWorthSeries_Call) RunAndReturn(run func(ctx context.Context, userID int64, currency string, rangeKey string, from string, to string, accountID *int64) (*models.NetWorthResponse, error)) *MockAnalyticsServiceInterface_GetNetWorthSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodayStats provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetTodayStats(ctx context.Context, userID int64, accountID *int64) (*models.TodayStats, error) {
	ret := _mock.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodayStats")
	}

	var r0 *models.TodayStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64) (*models.TodayStats, error)); ok {
		return returnFunc(ctx, userID, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64) *models.TodayStats); ok {
		r0 = returnFunc(ctx, userID, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TodayStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *int64) error); ok {
		r1 = returnFunc(ctx, userID, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetTodayStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodayStats'
type MockAnalyticsServiceInterface_GetTodayStats_Call struct {
	*mock.Call
}

// GetTodayStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID *int64
func (_e *MockAnalyticsServiceInterface_Expecter) GetTodayStats(ctx any, userID any, accountID any) *MockAnalyticsServiceInterface_GetTodayStats_Call {
	return &MockAnalyticsServiceInterface_GetTodayStats_Call{Call: _e.mock.On("GetTodayStats", ctx, userID, accountID)}
}

func (_c *MockAnalyticsServiceInterface_GetTodayStats_Call) Run(run func(ctx context.Context, userID int64, accountID *int64)) *MockAnalyticsServiceInterface_GetTodayStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetTodayStats_Call) Return(todayStats *models.TodayStats, err error) *MockAnalyticsServiceInterface_GetTodayStats_Call {
	_c.Call.Return(todayStats, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetTodayStats_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID *int64) (*models.TodayStats, error)) *MockAnalyticsServiceInterface_GetTodayStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlyAverageForCategory provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetYearlyAverageForCategory(ctx context.Context, userID int64, accountID int64, categoryID int64, isGroup bool) (float64, error) {
	ret := _mock.Called(ctx, userID, accountID, categoryID, isGroup)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlyAverageForCategory")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int64, bool) (float64, error)); ok {
		return returnFunc(ctx, userID, accountID, categoryID, isGroup)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int64, bool) float64); ok {
		r0 = returnFunc(ctx, userID, accountID, categoryID, isGroup)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, accountID, categoryID, isGroup)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlyAverageForCategory'
type MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call struct {
	*mock.Call
}

// GetYearlyAverageForCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID int64
//   - categoryID int64
//   - isGroup bool
func (_e *MockAnalyticsServiceInterface_Expecter) GetYearlyAverageForCategory(ctx any, userID any, accountID any, categoryID any, isGroup any) *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call {
	return &MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call{Call: _e.mock.On("GetYearlyAverageForCategory", ctx, userID, accountID, categoryID, isGroup)}
}

func (_c *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call) Run(run func(ctx context.Context, userID int64, accountID int64, categoryID int64, isGroup bool)) *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call) Return(f float64, err error) *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID int64, categoryID int64, isGroup bool) (float64, error)) *MockAnalyticsServiceInterface_GetYearlyAverageForCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlyBreakdownStats provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetYearlyBreakdownStats(ctx context.Context, accID *int64, userID int64, year int, comparisonYear *int) (*models.YearlyBreakdownStats, error) {
	ret := _mock.Called(ctx, accID, userID, year, comparisonYear)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlyBreakdownStats")
	}

	var r0 *models.YearlyBreakdownStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int64, int, *int) (*models.YearlyBreakdownStats, error)); ok {
		return returnFunc(ctx, accID, userID, year, comparisonYear)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int64, int, *int) *models.YearlyBreakdownStats); ok {
		r0 = returnFunc(ctx, accID, userID, year, comparisonYear)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YearlyBreakdownStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64, int64, int, *int) error); ok {
		r1 = returnFunc(ctx, accID, userID, year, comparisonYear)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlyBreakdownStats'
type MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call struct {
	*mock.Call
}

// GetYearlyBreakdownStats is a helper method to define mock.On call
//   - ctx context.Context
//   - accID *int64
//   - userID int64
//   - year int
//   - comparisonYear *int
func (_e *MockAnalyticsServiceInterface_Expecter) GetYearlyBreakdownStats(ctx any, accID any, userID any, year any, comparisonYear any) *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call {
	return &MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call{Call: _e.mock.On("GetYearlyBreakdownStats", ctx, accID, userID, year, comparisonYear)}
}

func (_c *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call) Run(run func(ctx context.Context, accID *int64, userID int64, year int, comparisonYear *int)) *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call) Return(yearlyBreakdownStats *models.YearlyBreakdownStats, err error) *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call {
	_c.Call.Return(yearlyBreakdownStats, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call) RunAndReturn(run func(ctx context.Context, accID *int64, userID int64, year int, comparisonYear *int) (*models.YearlyBreakdownStats, error)) *MockAnalyticsServiceInterface_GetYearlyBreakdownStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlyCashFlowBreakdown provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetYearlyCashFlowBreakdown(ctx context.Context, userID int64, year int, accountID *int64) (*models.YearlyCashflowBreakdown, error) {
	ret := _mock.Called(ctx, userID, year, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlyCashFlowBreakdown")
	}

	var r0 *models.YearlyCashflowBreakdown
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, *int64) (*models.YearlyCashflowBreakdown, error)); ok {
		return returnFunc(ctx, userID, year, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, *int64) *models.YearlyCashflowBreakdown); ok {
		r0 = returnFunc(ctx, userID, year, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YearlyCashflowBreakdown)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, *int64) error); ok {
		r1 = returnFunc(ctx, userID, year, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlyCashFlowBreakdown'
type MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call struct {
	*mock.Call
}

// GetYearlyCashFlowBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - year int
//   - accountID *int64
func (_e *MockAnalyticsServiceInterface_Expecter) GetYearlyCashFlowBreakdown(ctx any, userID any, year any, accountID any) *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call {
	return &MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call{Call: _e.mock.On("GetYearlyCashFlowBreakdown", ctx, userID, year, accountID)}
}

func (_c *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call) Run(run func(ctx context.Context, userID int64, year int, accountID *int64)) *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call) Return(yearlyCashflowBreakdown *models.YearlyCashflowBreakdown, err error) *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call {
	_c.Call.Return(yearlyCashflowBreakdown, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call) RunAndReturn(run func(ctx context.Context, userID int64, year int, accountID *int64) (*models.YearlyCashflowBreakdown, error)) *MockAnalyticsServiceInterface_GetYearlyCashFlowBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlySankeyData provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) GetYearlySankeyData(ctx context.Context, userID int64, accountID *int64, year int) (*models.YearlySankeyData, error) {
	ret := _mock.Called(ctx, userID, accountID, year)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlySankeyData")
	}

	var r0 *models.YearlySankeyData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64, int) (*models.YearlySankeyData, error)); ok {
		return returnFunc(ctx, userID, accountID, year)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64, int) *models.YearlySankeyData); ok {
		r0 = returnFunc(ctx, userID, accountID, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YearlySankeyData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *int64, int) error); ok {
		r1 = returnFunc(ctx, userID, accountID, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsServiceInterface_GetYearlySankeyData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlySankeyData'
type MockAnalyticsServiceInterface_GetYearlySankeyData_Call struct {
	*mock.Call
}

// GetYearlySankeyData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID *int64
//   - year int
func (_e *MockAnalyticsServiceInterface_Expecter) GetYearlySankeyData(ctx any, userID any, accountID any, year any) *MockAnalyticsServiceInterface_GetYearlySankeyData_Call {
	return &MockAnalyticsServiceInterface_GetYearlySankeyData_Call{Call: _e.mock.On("GetYearlySankeyData", ctx, userID, accountID, year)}
}

func (_c *MockAnalyticsServiceInterface_GetYearlySankeyData_Call) Run(run func(ctx context.Context, userID int64, accountID *int64, year int)) *MockAnalyticsServiceInterface_GetYearlySankeyData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlySankeyData_Call) Return(yearlySankeyData *models.YearlySankeyData, err error) *MockAnalyticsServiceInterface_GetYearlySankeyData_Call {
	_c.Call.Return(yearlySankeyData, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_GetYearlySankeyData_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID *int64, year int) (*models.YearlySankeyData, error)) *MockAnalyticsServiceInterface_GetYearlySankeyData_Call {
	_c.Call.Return(run)
	return _c
}

// ListReportsPaginated provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) ListReportsPaginated(ctx context.Context, userID int64, p utils.PaginationParams) ([]models.Report, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, p)

	if len(ret) == 0 {
		panic("no return value specified for ListReportsPaginated")
	}

	var r0 []models.Report
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams) ([]models.Report, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams) []models.Report); ok {
		r0 = returnFunc(ctx, userID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, utils.PaginationParams) *utils.Paginator); ok {
		r1 = returnFunc(ctx, userID, p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, utils.PaginationParams) error); ok {
		r2 = returnFunc(ctx, userID, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAnalyticsServiceInterface_ListReportsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReportsPaginated'
type MockAnalyticsServiceInterface_ListReportsPaginated_Call struct {
	*mock.Call
}

// ListReportsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p utils.PaginationParams
func (_e *MockAnalyticsServiceInterface_Expecter) ListReportsPaginated(ctx any, userID any, p any) *MockAnalyticsServiceInterface_ListReportsPaginated_Call {
	return &MockAnalyticsServiceInterface_ListReportsPaginated_Call{Call: _e.mock.On("ListReportsPaginated", ctx, userID, p)}
}

func (_c *MockAnalyticsServiceInterface_ListReportsPaginated_Call) Run(run func(ctx context.Context, userID int64, p utils.PaginationParams)) *MockAnalyticsServiceInterface_ListReportsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 utils.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(utils.PaginationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_ListReportsPaginated_Call) Return(reports []models.Report, paginator *utils.Paginator, err error) *MockAnalyticsServiceInterface_ListReportsPaginated_Call {
	_c.Call.Return(reports, paginator, err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_ListReportsPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, p utils.PaginationParams) ([]models.Report, *utils.Paginator, error)) *MockAnalyticsServiceInterface_ListReportsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReportCompleted provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) MarkReportCompleted(ctx context.Context, reportID int64, name string, filePath string, fileSize int64, completedAt time.Time) error {
	ret := _mock.Called(ctx, reportID, name, filePath, fileSize, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkReportCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, reportID, name, filePath, fileSize, completedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalyticsServiceInterface_MarkReportCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReportCompleted'
type MockAnalyticsServiceInterface_MarkReportCompleted_Call struct {
	*mock.Call
}

// MarkReportCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID int64
//   - name string
//   - filePath string
//   - fileSize int64
//   - completedAt time.Time
func (_e *MockAnalyticsServiceInterface_Expecter) MarkReportCompleted(ctx any, reportID any, name any, filePath any, fileSize any, completedAt any) *MockAnalyticsServiceInterface_MarkReportCompleted_Call {
	return &MockAnalyticsServiceInterface_MarkReportCompleted_Call{Call: _e.mock.On("MarkReportCompleted", ctx, reportID, name, filePath, fileSize, completedAt)}
}

func (_c *MockAnalyticsServiceInterface_MarkReportCompleted_Call) Run(run func(ctx context.Context, reportID int64, name string, filePath string, fileSize int64, completedAt time.Time)) *MockAnalyticsServiceInterface_MarkReportCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_MarkReportCompleted_Call) Return(err error) *MockAnalyticsServiceInterface_MarkReportCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_MarkReportCompleted_Call) RunAndReturn(run func(ctx context.Context, reportID int64, name string, filePath string, fileSize int64, completedAt time.Time) error) *MockAnalyticsServiceInterface_MarkReportCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReportFailed provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) MarkReportFailed(ctx context.Context, reportID int64, reason string) error {
	ret := _mock.Called(ctx, reportID, reason)

	if len(ret) == 0 {
		panic("no return value specified for MarkReportFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, reportID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalyticsServiceInterface_MarkReportFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReportFailed'
type MockAnalyticsServiceInterface_MarkReportFailed_Call struct {
	*mock.Call
}

// MarkReportFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID int64
//   - reason string
func (_e *MockAnalyticsServiceInterface_Expecter) MarkReportFailed(ctx any, reportID any, reason any) *MockAnalyticsServiceInterface_MarkReportFailed_Call {
	return &MockAnalyticsServiceInterface_MarkReportFailed_Call{Call: _e.mock.On("MarkReportFailed", ctx, reportID, reason)}
}

func (_c *MockAnalyticsServiceInterface_MarkReportFailed_Call) Run(run func(ctx context.Context, reportID int64, reason string)) *MockAnalyticsServiceInterface_MarkReportFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_MarkReportFailed_Call) Return(err error) *MockAnalyticsServiceInterface_MarkReportFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_MarkReportFailed_Call) RunAndReturn(run func(ctx context.Context, reportID int64, reason string) error) *MockAnalyticsServiceInterface_MarkReportFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReportProcessing provides a mock function for the type MockAnalyticsServiceInterface
func (_mock *MockAnalyticsServiceInterface) MarkReportProcessing(ctx context.Context, reportID int64) error {
	ret := _mock.Called(ctx, reportID)

	if len(ret) == 0 {
		panic("no return value specified for MarkReportProcessing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, reportID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalyticsServiceInterface_MarkReportProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReportProcessing'
type MockAnalyticsServiceInterface_MarkReportProcessing_Call struct {
	*mock.Call
}

// MarkReportProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID int64
func (_e *MockAnalyticsServiceInterface_Expecter) MarkReportProcessing(ctx any, reportID any) *MockAnalyticsServiceInterface_MarkReportProcessing_Call {
	return &MockAnalyticsServiceInterface_MarkReportProcessing_Call{Call: _e.mock.On("MarkReportProcessing", ctx, reportID)}
}

func (_c *MockAnalyticsServiceInterface_MarkReportProcessing_Call) Run(run func(ctx context.Context, reportID int64)) *MockAnalyticsServiceInterface_MarkReportProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsServiceInterface_MarkReportProcessing_Call) Return(err error) *MockAnalyticsServiceInterface_MarkReportProcessing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalyticsServiceInterface_MarkReportProcessing_Call) RunAndReturn(run func(ctx context.Context, reportID int64) error) *MockAnalyticsServiceInterface_MarkReportProcessing_Call {
	_c.Call.Return(run)
	return _c
}
