// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockWebClientMiddlewareInterface is an autogenerated mock type for the WebClientMiddlewareInterface type
type MockWebClientMiddlewareInterface struct {
	mock.Mock
}

type MockWebClientMiddlewareInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebClientMiddlewareInterface) EXPECT() *MockWebClientMiddlewareInterface_Expecter {
	return &MockWebClientMiddlewareInterface_Expecter{mock: &_m.Mock}
}

// CookieDomainForEnv provides a mock function with no fields
func (_m *MockWebClientMiddlewareInterface) CookieDomainForEnv() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CookieDomainForEnv")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWebClientMiddlewareInterface_CookieDomainForEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CookieDomainForEnv'
type MockWebClientMiddlewareInterface_CookieDomainForEnv_Call struct {
	*mock.Call
}

// CookieDomainForEnv is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) CookieDomainForEnv() *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	return &MockWebClientMiddlewareInterface_CookieDomainForEnv_Call{Call: _e.mock.On("CookieDomainForEnv")}
}

func (_c *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call) Run(run func()) *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call) Return(_a0 string) *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call) RunAndReturn(run func() string) *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	_c.Call.Return(run)
	return _c
}

// CookieSecure provides a mock function with no fields
func (_m *MockWebClientMiddlewareInterface) CookieSecure() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CookieSecure")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWebClientMiddlewareInterface_CookieSecure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CookieSecure'
type MockWebClientMiddlewareInterface_CookieSecure_Call struct {
	*mock.Call
}

// CookieSecure is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) CookieSecure() *MockWebClientMiddlewareInterface_CookieSecure_Call {
	return &MockWebClientMiddlewareInterface_CookieSecure_Call{Call: _e.mock.On("CookieSecure")}
}

func (_c *MockWebClientMiddlewareInterface_CookieSecure_Call) Run(run func()) *MockWebClientMiddlewareInterface_CookieSecure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieSecure_Call) Return(_a0 bool) *MockWebClientMiddlewareInterface_CookieSecure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieSecure_Call) RunAndReturn(run func() bool) *MockWebClientMiddlewareInterface_CookieSecure_Call {
	_c.Call.Return(run)
	return _c
}

// ErrorLogger provides a mock function with no fields
func (_m *MockWebClientMiddlewareInterface) ErrorLogger() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorLogger")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// MockWebClientMiddlewareInterface_ErrorLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorLogger'
type MockWebClientMiddlewareInterface_ErrorLogger_Call struct {
	*mock.Call
}

// ErrorLogger is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) ErrorLogger() *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	return &MockWebClientMiddlewareInterface_ErrorLogger_Call{Call: _e.mock.On("ErrorLogger")}
}

func (_c *MockWebClientMiddlewareInterface_ErrorLogger_Call) Run(run func()) *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_ErrorLogger_Call) Return(_a0 gin.HandlerFunc) *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_ErrorLogger_Call) RunAndReturn(run func() gin.HandlerFunc) *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateLoginTokens provides a mock function with given fields: userID, rememberMe
func (_m *MockWebClientMiddlewareInterface) GenerateLoginTokens(userID int64, rememberMe bool) (string, string, error) {
	ret := _m.Called(userID, rememberMe)

	if len(ret) == 0 {
		panic("no return value specified for GenerateLoginTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(int64, bool) (string, string, error)); ok {
		return rf(userID, rememberMe)
	}
	if rf, ok := ret.Get(0).(func(int64, bool) string); ok {
		r0 = rf(userID, rememberMe)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, bool) string); ok {
		r1 = rf(userID, rememberMe)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(int64, bool) error); ok {
		r2 = rf(userID, rememberMe)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWebClientMiddlewareInterface_GenerateLoginTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateLoginTokens'
type MockWebClientMiddlewareInterface_GenerateLoginTokens_Call struct {
	*mock.Call
}

// GenerateLoginTokens is a helper method to define mock.On call
//   - userID int64
//   - rememberMe bool
func (_e *MockWebClientMiddlewareInterface_Expecter) GenerateLoginTokens(userID interface{}, rememberMe interface{}) *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call {
	return &MockWebClientMiddlewareInterface_GenerateLoginTokens_Call{Call: _e.mock.On("GenerateLoginTokens", userID, rememberMe)}
}

func (_c *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call) Run(run func(userID int64, rememberMe bool)) *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(bool))
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call) Return(_a0 string, _a1 string, _a2 error) *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call) RunAndReturn(run func(int64, bool) (string, string, error)) *MockWebClientMiddlewareInterface_GenerateLoginTokens_Call {
	_c.Call.Return(run)
	return _c
}

// WebClientAuthentication provides a mock function with no fields
func (_m *MockWebClientMiddlewareInterface) WebClientAuthentication() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebClientAuthentication")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// MockWebClientMiddlewareInterface_WebClientAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebClientAuthentication'
type MockWebClientMiddlewareInterface_WebClientAuthentication_Call struct {
	*mock.Call
}

// WebClientAuthentication is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) WebClientAuthentication() *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	return &MockWebClientMiddlewareInterface_WebClientAuthentication_Call{Call: _e.mock.On("WebClientAuthentication")}
}

func (_c *MockWebClientMiddlewareInterface_WebClientAuthentication_Call) Run(run func()) *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_WebClientAuthentication_Call) Return(_a0 gin.HandlerFunc) *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_WebClientAuthentication_Call) RunAndReturn(run func() gin.HandlerFunc) *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebClientMiddlewareInterface creates a new instance of MockWebClientMiddlewareInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebClientMiddlewareInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebClientMiddlewareInterface {
	mock := &MockWebClientMiddlewareInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
