// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"wealth-warden/internal/models"
	"wealth-warden/pkg/utils"

	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockAccountServiceInterface creates a new instance of MockAccountServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountServiceInterface {
	mock := &MockAccountServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountServiceInterface is an autogenerated mock type for the AccountServiceInterface type
type MockAccountServiceInterface struct {
	mock.Mock
}

type MockAccountServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountServiceInterface) EXPECT() *MockAccountServiceInterface_Expecter {
	return &MockAccountServiceInterface_Expecter{mock: &_m.Mock}
}

// BackfillBalancesForUser provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) BackfillBalancesForUser(ctx context.Context, userID int64, from string, to string) error {
	ret := _mock.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for BackfillBalancesForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = returnFunc(ctx, userID, from, to)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_BackfillBalancesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackfillBalancesForUser'
type MockAccountServiceInterface_BackfillBalancesForUser_Call struct {
	*mock.Call
}

// BackfillBalancesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - from string
//   - to string
func (_e *MockAccountServiceInterface_Expecter) BackfillBalancesForUser(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockAccountServiceInterface_BackfillBalancesForUser_Call {
	return &MockAccountServiceInterface_BackfillBalancesForUser_Call{Call: _e.mock.On("BackfillBalancesForUser", ctx, userID, from, to)}
}

func (_c *MockAccountServiceInterface_BackfillBalancesForUser_Call) Run(run func(ctx context.Context, userID int64, from string, to string)) *MockAccountServiceInterface_BackfillBalancesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_BackfillBalancesForUser_Call) Return(err error) *MockAccountServiceInterface_BackfillBalancesForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_BackfillBalancesForUser_Call) RunAndReturn(run func(ctx context.Context, userID int64, from string, to string) error) *MockAccountServiceInterface_BackfillBalancesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ClearInvestmentCashFlows provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) ClearInvestmentCashFlows(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearInvestmentCashFlows")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_ClearInvestmentCashFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearInvestmentCashFlows'
type MockAccountServiceInterface_ClearInvestmentCashFlows_Call struct {
	*mock.Call
}

// ClearInvestmentCashFlows is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) ClearInvestmentCashFlows(ctx interface{}, userID interface{}) *MockAccountServiceInterface_ClearInvestmentCashFlows_Call {
	return &MockAccountServiceInterface_ClearInvestmentCashFlows_Call{Call: _e.mock.On("ClearInvestmentCashFlows", ctx, userID)}
}

func (_c *MockAccountServiceInterface_ClearInvestmentCashFlows_Call) Run(run func(ctx context.Context, userID int64)) *MockAccountServiceInterface_ClearInvestmentCashFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_ClearInvestmentCashFlows_Call) Return(err error) *MockAccountServiceInterface_ClearInvestmentCashFlows_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_ClearInvestmentCashFlows_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockAccountServiceInterface_ClearInvestmentCashFlows_Call {
	_c.Call.Return(run)
	return _c
}

// ClearInvestmentSnapshots provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) ClearInvestmentSnapshots(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearInvestmentSnapshots")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_ClearInvestmentSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearInvestmentSnapshots'
type MockAccountServiceInterface_ClearInvestmentSnapshots_Call struct {
	*mock.Call
}

// ClearInvestmentSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) ClearInvestmentSnapshots(ctx interface{}, userID interface{}) *MockAccountServiceInterface_ClearInvestmentSnapshots_Call {
	return &MockAccountServiceInterface_ClearInvestmentSnapshots_Call{Call: _e.mock.On("ClearInvestmentSnapshots", ctx, userID)}
}

func (_c *MockAccountServiceInterface_ClearInvestmentSnapshots_Call) Run(run func(ctx context.Context, userID int64)) *MockAccountServiceInterface_ClearInvestmentSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_ClearInvestmentSnapshots_Call) Return(err error) *MockAccountServiceInterface_ClearInvestmentSnapshots_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_ClearInvestmentSnapshots_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockAccountServiceInterface_ClearInvestmentSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// CloseAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) CloseAccount(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for CloseAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_CloseAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAccount'
type MockAccountServiceInterface_CloseAccount_Call struct {
	*mock.Call
}

// CloseAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockAccountServiceInterface_Expecter) CloseAccount(ctx interface{}, userID interface{}, id interface{}) *MockAccountServiceInterface_CloseAccount_Call {
	return &MockAccountServiceInterface_CloseAccount_Call{Call: _e.mock.On("CloseAccount", ctx, userID, id)}
}

func (_c *MockAccountServiceInterface_CloseAccount_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockAccountServiceInterface_CloseAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_CloseAccount_Call) Return(err error) *MockAccountServiceInterface_CloseAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_CloseAccount_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockAccountServiceInterface_CloseAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountByID provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountByID(ctx context.Context, userID int64, id int64, initialBalance bool) (*models.Account, error) {
	ret := _mock.Called(ctx, userID, id, initialBalance)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountByID")
	}

	var r0 *models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, bool) (*models.Account, error)); ok {
		return returnFunc(ctx, userID, id, initialBalance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, bool) *models.Account); ok {
		r0 = returnFunc(ctx, userID, id, initialBalance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, id, initialBalance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountByID'
type MockAccountServiceInterface_FetchAccountByID_Call struct {
	*mock.Call
}

// FetchAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - initialBalance bool
func (_e *MockAccountServiceInterface_Expecter) FetchAccountByID(ctx interface{}, userID interface{}, id interface{}, initialBalance interface{}) *MockAccountServiceInterface_FetchAccountByID_Call {
	return &MockAccountServiceInterface_FetchAccountByID_Call{Call: _e.mock.On("FetchAccountByID", ctx, userID, id, initialBalance)}
}

func (_c *MockAccountServiceInterface_FetchAccountByID_Call) Run(run func(ctx context.Context, userID int64, id int64, initialBalance bool)) *MockAccountServiceInterface_FetchAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountByID_Call) Return(account *models.Account, err error) *MockAccountServiceInterface_FetchAccountByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, initialBalance bool) (*models.Account, error)) *MockAccountServiceInterface_FetchAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountByName provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountByName(ctx context.Context, userID int64, name string) (*models.Account, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountByName")
	}

	var r0 *models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (*models.Account, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) *models.Account); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAccountByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountByName'
type MockAccountServiceInterface_FetchAccountByName_Call struct {
	*mock.Call
}

// FetchAccountByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
func (_e *MockAccountServiceInterface_Expecter) FetchAccountByName(ctx interface{}, userID interface{}, name interface{}) *MockAccountServiceInterface_FetchAccountByName_Call {
	return &MockAccountServiceInterface_FetchAccountByName_Call{Call: _e.mock.On("FetchAccountByName", ctx, userID, name)}
}

func (_c *MockAccountServiceInterface_FetchAccountByName_Call) Run(run func(ctx context.Context, userID int64, name string)) *MockAccountServiceInterface_FetchAccountByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountByName_Call) Return(account *models.Account, err error) *MockAccountServiceInterface_FetchAccountByName_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountByName_Call) RunAndReturn(run func(ctx context.Context, userID int64, name string) (*models.Account, error)) *MockAccountServiceInterface_FetchAccountByName_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountTypesWithoutDefaults provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountTypesWithoutDefaults(ctx context.Context, userID int64) ([]models.AccountType, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountTypesWithoutDefaults")
	}

	var r0 []models.AccountType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.AccountType, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.AccountType); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AccountType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountTypesWithoutDefaults'
type MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call struct {
	*mock.Call
}

// FetchAccountTypesWithoutDefaults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) FetchAccountTypesWithoutDefaults(ctx interface{}, userID interface{}) *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call {
	return &MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call{Call: _e.mock.On("FetchAccountTypesWithoutDefaults", ctx, userID)}
}

func (_c *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call) Run(run func(ctx context.Context, userID int64)) *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call) Return(accountTypes []models.AccountType, err error) *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call {
	_c.Call.Return(accountTypes, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.AccountType, error)) *MockAccountServiceInterface_FetchAccountTypesWithoutDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountsBySubtype provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountsBySubtype(ctx context.Context, userID int64, subtype string) ([]models.Account, error) {
	ret := _mock.Called(ctx, userID, subtype)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountsBySubtype")
	}

	var r0 []models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]models.Account, error)); ok {
		return returnFunc(ctx, userID, subtype)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []models.Account); ok {
		r0 = returnFunc(ctx, userID, subtype)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, subtype)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAccountsBySubtype_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountsBySubtype'
type MockAccountServiceInterface_FetchAccountsBySubtype_Call struct {
	*mock.Call
}

// FetchAccountsBySubtype is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - subtype string
func (_e *MockAccountServiceInterface_Expecter) FetchAccountsBySubtype(ctx interface{}, userID interface{}, subtype interface{}) *MockAccountServiceInterface_FetchAccountsBySubtype_Call {
	return &MockAccountServiceInterface_FetchAccountsBySubtype_Call{Call: _e.mock.On("FetchAccountsBySubtype", ctx, userID, subtype)}
}

func (_c *MockAccountServiceInterface_FetchAccountsBySubtype_Call) Run(run func(ctx context.Context, userID int64, subtype string)) *MockAccountServiceInterface_FetchAccountsBySubtype_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsBySubtype_Call) Return(accounts []models.Account, err error) *MockAccountServiceInterface_FetchAccountsBySubtype_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsBySubtype_Call) RunAndReturn(run func(ctx context.Context, userID int64, subtype string) ([]models.Account, error)) *MockAccountServiceInterface_FetchAccountsBySubtype_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountsByType provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountsByType(ctx context.Context, userID int64, t string) ([]models.Account, error) {
	ret := _mock.Called(ctx, userID, t)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountsByType")
	}

	var r0 []models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]models.Account, error)); ok {
		return returnFunc(ctx, userID, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []models.Account); ok {
		r0 = returnFunc(ctx, userID, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAccountsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountsByType'
type MockAccountServiceInterface_FetchAccountsByType_Call struct {
	*mock.Call
}

// FetchAccountsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - t string
func (_e *MockAccountServiceInterface_Expecter) FetchAccountsByType(ctx interface{}, userID interface{}, t interface{}) *MockAccountServiceInterface_FetchAccountsByType_Call {
	return &MockAccountServiceInterface_FetchAccountsByType_Call{Call: _e.mock.On("FetchAccountsByType", ctx, userID, t)}
}

func (_c *MockAccountServiceInterface_FetchAccountsByType_Call) Run(run func(ctx context.Context, userID int64, t string)) *MockAccountServiceInterface_FetchAccountsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsByType_Call) Return(accounts []models.Account, err error) *MockAccountServiceInterface_FetchAccountsByType_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsByType_Call) RunAndReturn(run func(ctx context.Context, userID int64, t string) ([]models.Account, error)) *MockAccountServiceInterface_FetchAccountsByType_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountsPaginated provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountsPaginated(ctx context.Context, userID int64, p utils.PaginationParams, includeInactive bool, classification string) ([]models.Account, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, p, includeInactive, classification)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountsPaginated")
	}

	var r0 []models.Account
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, bool, string) ([]models.Account, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, p, includeInactive, classification)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, bool, string) []models.Account); ok {
		r0 = returnFunc(ctx, userID, p, includeInactive, classification)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, utils.PaginationParams, bool, string) *utils.Paginator); ok {
		r1 = returnFunc(ctx, userID, p, includeInactive, classification)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, utils.PaginationParams, bool, string) error); ok {
		r2 = returnFunc(ctx, userID, p, includeInactive, classification)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAccountServiceInterface_FetchAccountsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountsPaginated'
type MockAccountServiceInterface_FetchAccountsPaginated_Call struct {
	*mock.Call
}

// FetchAccountsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p utils.PaginationParams
//   - includeInactive bool
//   - classification string
func (_e *MockAccountServiceInterface_Expecter) FetchAccountsPaginated(ctx interface{}, userID interface{}, p interface{}, includeInactive interface{}, classification interface{}) *MockAccountServiceInterface_FetchAccountsPaginated_Call {
	return &MockAccountServiceInterface_FetchAccountsPaginated_Call{Call: _e.mock.On("FetchAccountsPaginated", ctx, userID, p, includeInactive, classification)}
}

func (_c *MockAccountServiceInterface_FetchAccountsPaginated_Call) Run(run func(ctx context.Context, userID int64, p utils.PaginationParams, includeInactive bool, classification string)) *MockAccountServiceInterface_FetchAccountsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 utils.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(utils.PaginationParams)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsPaginated_Call) Return(accounts []models.Account, paginator *utils.Paginator, err error) *MockAccountServiceInterface_FetchAccountsPaginated_Call {
	_c.Call.Return(accounts, paginator, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, p utils.PaginationParams, includeInactive bool, classification string) ([]models.Account, *utils.Paginator, error)) *MockAccountServiceInterface_FetchAccountsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAccountsWithDefaults provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAccountsWithDefaults(ctx context.Context, userID int64) ([]models.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountsWithDefaults")
	}

	var r0 []models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAccountsWithDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAccountsWithDefaults'
type MockAccountServiceInterface_FetchAccountsWithDefaults_Call struct {
	*mock.Call
}

// FetchAccountsWithDefaults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) FetchAccountsWithDefaults(ctx interface{}, userID interface{}) *MockAccountServiceInterface_FetchAccountsWithDefaults_Call {
	return &MockAccountServiceInterface_FetchAccountsWithDefaults_Call{Call: _e.mock.On("FetchAccountsWithDefaults", ctx, userID)}
}

func (_c *MockAccountServiceInterface_FetchAccountsWithDefaults_Call) Run(run func(ctx context.Context, userID int64)) *MockAccountServiceInterface_FetchAccountsWithDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsWithDefaults_Call) Return(accounts []models.Account, err error) *MockAccountServiceInterface_FetchAccountsWithDefaults_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAccountsWithDefaults_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.Account, error)) *MockAccountServiceInterface_FetchAccountsWithDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllAccountTypes provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAllAccountTypes(ctx context.Context) ([]models.AccountType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllAccountTypes")
	}

	var r0 []models.AccountType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.AccountType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.AccountType); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AccountType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAllAccountTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllAccountTypes'
type MockAccountServiceInterface_FetchAllAccountTypes_Call struct {
	*mock.Call
}

// FetchAllAccountTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountServiceInterface_Expecter) FetchAllAccountTypes(ctx interface{}) *MockAccountServiceInterface_FetchAllAccountTypes_Call {
	return &MockAccountServiceInterface_FetchAllAccountTypes_Call{Call: _e.mock.On("FetchAllAccountTypes", ctx)}
}

func (_c *MockAccountServiceInterface_FetchAllAccountTypes_Call) Run(run func(ctx context.Context)) *MockAccountServiceInterface_FetchAllAccountTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAllAccountTypes_Call) Return(accountTypes []models.AccountType, err error) *MockAccountServiceInterface_FetchAllAccountTypes_Call {
	_c.Call.Return(accountTypes, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAllAccountTypes_Call) RunAndReturn(run func(ctx context.Context) ([]models.AccountType, error)) *MockAccountServiceInterface_FetchAllAccountTypes_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllAccounts provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchAllAccounts(ctx context.Context, userID int64, includeInactive bool, options ...bool) ([]models.Account, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, userID, includeInactive, options)
	} else {
		tmpRet = _mock.Called(ctx, userID, includeInactive)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FetchAllAccounts")
	}

	var r0 []models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool, ...bool) ([]models.Account, error)); ok {
		return returnFunc(ctx, userID, includeInactive, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool, ...bool) []models.Account); ok {
		r0 = returnFunc(ctx, userID, includeInactive, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool, ...bool) error); ok {
		r1 = returnFunc(ctx, userID, includeInactive, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchAllAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllAccounts'
type MockAccountServiceInterface_FetchAllAccounts_Call struct {
	*mock.Call
}

// FetchAllAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - includeInactive bool
//   - options ...bool
func (_e *MockAccountServiceInterface_Expecter) FetchAllAccounts(ctx interface{}, userID interface{}, includeInactive interface{}, options ...interface{}) *MockAccountServiceInterface_FetchAllAccounts_Call {
	return &MockAccountServiceInterface_FetchAllAccounts_Call{Call: _e.mock.On("FetchAllAccounts",
		append([]interface{}{ctx, userID, includeInactive}, options...)...)}
}

func (_c *MockAccountServiceInterface_FetchAllAccounts_Call) Run(run func(ctx context.Context, userID int64, includeInactive bool, options ...bool)) *MockAccountServiceInterface_FetchAllAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 []bool
		var variadicArgs []bool
		if len(args) > 3 {
			variadicArgs = args[3].([]bool)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchAllAccounts_Call) Return(accounts []models.Account, err error) *MockAccountServiceInterface_FetchAllAccounts_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchAllAccounts_Call) RunAndReturn(run func(ctx context.Context, userID int64, includeInactive bool, options ...bool) ([]models.Account, error)) *MockAccountServiceInterface_FetchAllAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// FetchLatestBalance provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FetchLatestBalance(ctx context.Context, accID int64, userID int64) (*models.Balance, error) {
	ret := _mock.Called(ctx, accID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchLatestBalance")
	}

	var r0 *models.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.Balance, error)); ok {
		return returnFunc(ctx, accID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.Balance); ok {
		r0 = returnFunc(ctx, accID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, accID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_FetchLatestBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchLatestBalance'
type MockAccountServiceInterface_FetchLatestBalance_Call struct {
	*mock.Call
}

// FetchLatestBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accID int64
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) FetchLatestBalance(ctx interface{}, accID interface{}, userID interface{}) *MockAccountServiceInterface_FetchLatestBalance_Call {
	return &MockAccountServiceInterface_FetchLatestBalance_Call{Call: _e.mock.On("FetchLatestBalance", ctx, accID, userID)}
}

func (_c *MockAccountServiceInterface_FetchLatestBalance_Call) Run(run func(ctx context.Context, accID int64, userID int64)) *MockAccountServiceInterface_FetchLatestBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FetchLatestBalance_Call) Return(balance *models.Balance, err error) *MockAccountServiceInterface_FetchLatestBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockAccountServiceInterface_FetchLatestBalance_Call) RunAndReturn(run func(ctx context.Context, accID int64, userID int64) (*models.Balance, error)) *MockAccountServiceInterface_FetchLatestBalance_Call {
	_c.Call.Return(run)
	return _c
}

// FrontfillBalancesForAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) FrontfillBalancesForAccount(ctx context.Context, tx *gorm.DB, userID int64, accountID int64, currency string, from time.Time) error {
	ret := _mock.Called(ctx, tx, userID, accountID, currency, from)

	if len(ret) == 0 {
		panic("no return value specified for FrontfillBalancesForAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, int64, string, time.Time) error); ok {
		r0 = returnFunc(ctx, tx, userID, accountID, currency, from)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_FrontfillBalancesForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FrontfillBalancesForAccount'
type MockAccountServiceInterface_FrontfillBalancesForAccount_Call struct {
	*mock.Call
}

// FrontfillBalancesForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - userID int64
//   - accountID int64
//   - currency string
//   - from time.Time
func (_e *MockAccountServiceInterface_Expecter) FrontfillBalancesForAccount(ctx interface{}, tx interface{}, userID interface{}, accountID interface{}, currency interface{}, from interface{}) *MockAccountServiceInterface_FrontfillBalancesForAccount_Call {
	return &MockAccountServiceInterface_FrontfillBalancesForAccount_Call{Call: _e.mock.On("FrontfillBalancesForAccount", ctx, tx, userID, accountID, currency, from)}
}

func (_c *MockAccountServiceInterface_FrontfillBalancesForAccount_Call) Run(run func(ctx context.Context, tx *gorm.DB, userID int64, accountID int64, currency string, from time.Time)) *MockAccountServiceInterface_FrontfillBalancesForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_FrontfillBalancesForAccount_Call) Return(err error) *MockAccountServiceInterface_FrontfillBalancesForAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_FrontfillBalancesForAccount_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, userID int64, accountID int64, currency string, from time.Time) error) *MockAccountServiceInterface_FrontfillBalancesForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetIDsForAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) GetAssetIDsForAccount(ctx context.Context, userID int64, accountID int64) ([]int64, error) {
	ret := _mock.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetIDsForAccount")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]int64, error)); ok {
		return returnFunc(ctx, userID, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []int64); ok {
		r0 = returnFunc(ctx, userID, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_GetAssetIDsForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetIDsForAccount'
type MockAccountServiceInterface_GetAssetIDsForAccount_Call struct {
	*mock.Call
}

// GetAssetIDsForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID int64
func (_e *MockAccountServiceInterface_Expecter) GetAssetIDsForAccount(ctx interface{}, userID interface{}, accountID interface{}) *MockAccountServiceInterface_GetAssetIDsForAccount_Call {
	return &MockAccountServiceInterface_GetAssetIDsForAccount_Call{Call: _e.mock.On("GetAssetIDsForAccount", ctx, userID, accountID)}
}

func (_c *MockAccountServiceInterface_GetAssetIDsForAccount_Call) Run(run func(ctx context.Context, userID int64, accountID int64)) *MockAccountServiceInterface_GetAssetIDsForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_GetAssetIDsForAccount_Call) Return(int64s []int64, err error) *MockAccountServiceInterface_GetAssetIDsForAccount_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockAccountServiceInterface_GetAssetIDsForAccount_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID int64) ([]int64, error)) *MockAccountServiceInterface_GetAssetIDsForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) InsertAccount(ctx context.Context, userID int64, req *models.AccountReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertAccount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.AccountReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.AccountReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.AccountReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_InsertAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAccount'
type MockAccountServiceInterface_InsertAccount_Call struct {
	*mock.Call
}

// InsertAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.AccountReq
func (_e *MockAccountServiceInterface_Expecter) InsertAccount(ctx interface{}, userID interface{}, req interface{}) *MockAccountServiceInterface_InsertAccount_Call {
	return &MockAccountServiceInterface_InsertAccount_Call{Call: _e.mock.On("InsertAccount", ctx, userID, req)}
}

func (_c *MockAccountServiceInterface_InsertAccount_Call) Run(run func(ctx context.Context, userID int64, req *models.AccountReq)) *MockAccountServiceInterface_InsertAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.AccountReq
		if args[2] != nil {
			arg2 = args[2].(*models.AccountReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_InsertAccount_Call) Return(n int64, err error) *MockAccountServiceInterface_InsertAccount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountServiceInterface_InsertAccount_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.AccountReq) (int64, error)) *MockAccountServiceInterface_InsertAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RebuildSnapshotsForUser provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) RebuildSnapshotsForUser(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RebuildSnapshotsForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_RebuildSnapshotsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebuildSnapshotsForUser'
type MockAccountServiceInterface_RebuildSnapshotsForUser_Call struct {
	*mock.Call
}

// RebuildSnapshotsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) RebuildSnapshotsForUser(ctx interface{}, userID interface{}) *MockAccountServiceInterface_RebuildSnapshotsForUser_Call {
	return &MockAccountServiceInterface_RebuildSnapshotsForUser_Call{Call: _e.mock.On("RebuildSnapshotsForUser", ctx, userID)}
}

func (_c *MockAccountServiceInterface_RebuildSnapshotsForUser_Call) Run(run func(ctx context.Context, userID int64)) *MockAccountServiceInterface_RebuildSnapshotsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_RebuildSnapshotsForUser_Call) Return(err error) *MockAccountServiceInterface_RebuildSnapshotsForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_RebuildSnapshotsForUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockAccountServiceInterface_RebuildSnapshotsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RecalculateAssetPnL provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) RecalculateAssetPnL(ctx context.Context, userID int64, assetID int64) error {
	ret := _mock.Called(ctx, userID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for RecalculateAssetPnL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, assetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_RecalculateAssetPnL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecalculateAssetPnL'
type MockAccountServiceInterface_RecalculateAssetPnL_Call struct {
	*mock.Call
}

// RecalculateAssetPnL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - assetID int64
func (_e *MockAccountServiceInterface_Expecter) RecalculateAssetPnL(ctx interface{}, userID interface{}, assetID interface{}) *MockAccountServiceInterface_RecalculateAssetPnL_Call {
	return &MockAccountServiceInterface_RecalculateAssetPnL_Call{Call: _e.mock.On("RecalculateAssetPnL", ctx, userID, assetID)}
}

func (_c *MockAccountServiceInterface_RecalculateAssetPnL_Call) Run(run func(ctx context.Context, userID int64, assetID int64)) *MockAccountServiceInterface_RecalculateAssetPnL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_RecalculateAssetPnL_Call) Return(err error) *MockAccountServiceInterface_RecalculateAssetPnL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_RecalculateAssetPnL_Call) RunAndReturn(run func(ctx context.Context, userID int64, assetID int64) error) *MockAccountServiceInterface_RecalculateAssetPnL_Call {
	_c.Call.Return(run)
	return _c
}

// RevertAccountProjection provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) RevertAccountProjection(ctx context.Context, id int64, userID int64) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevertAccountProjection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_RevertAccountProjection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevertAccountProjection'
type MockAccountServiceInterface_RevertAccountProjection_Call struct {
	*mock.Call
}

// RevertAccountProjection is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) RevertAccountProjection(ctx interface{}, id interface{}, userID interface{}) *MockAccountServiceInterface_RevertAccountProjection_Call {
	return &MockAccountServiceInterface_RevertAccountProjection_Call{Call: _e.mock.On("RevertAccountProjection", ctx, id, userID)}
}

func (_c *MockAccountServiceInterface_RevertAccountProjection_Call) Run(run func(ctx context.Context, id int64, userID int64)) *MockAccountServiceInterface_RevertAccountProjection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_RevertAccountProjection_Call) Return(err error) *MockAccountServiceInterface_RevertAccountProjection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_RevertAccountProjection_Call) RunAndReturn(run func(ctx context.Context, id int64, userID int64) error) *MockAccountServiceInterface_RevertAccountProjection_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAccountProjection provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) SaveAccountProjection(ctx context.Context, id int64, userID int64, req *models.AccountProjectionReq) error {
	ret := _mock.Called(ctx, id, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveAccountProjection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.AccountProjectionReq) error); ok {
		r0 = returnFunc(ctx, id, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_SaveAccountProjection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAccountProjection'
type MockAccountServiceInterface_SaveAccountProjection_Call struct {
	*mock.Call
}

// SaveAccountProjection is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
//   - req *models.AccountProjectionReq
func (_e *MockAccountServiceInterface_Expecter) SaveAccountProjection(ctx interface{}, id interface{}, userID interface{}, req interface{}) *MockAccountServiceInterface_SaveAccountProjection_Call {
	return &MockAccountServiceInterface_SaveAccountProjection_Call{Call: _e.mock.On("SaveAccountProjection", ctx, id, userID, req)}
}

func (_c *MockAccountServiceInterface_SaveAccountProjection_Call) Run(run func(ctx context.Context, id int64, userID int64, req *models.AccountProjectionReq)) *MockAccountServiceInterface_SaveAccountProjection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.AccountProjectionReq
		if args[3] != nil {
			arg3 = args[3].(*models.AccountProjectionReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_SaveAccountProjection_Call) Return(err error) *MockAccountServiceInterface_SaveAccountProjection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_SaveAccountProjection_Call) RunAndReturn(run func(ctx context.Context, id int64, userID int64, req *models.AccountProjectionReq) error) *MockAccountServiceInterface_SaveAccountProjection_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) SetDefaultAccount(ctx context.Context, userID int64, accountID int64) error {
	ret := _mock.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_SetDefaultAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultAccount'
type MockAccountServiceInterface_SetDefaultAccount_Call struct {
	*mock.Call
}

// SetDefaultAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID int64
func (_e *MockAccountServiceInterface_Expecter) SetDefaultAccount(ctx interface{}, userID interface{}, accountID interface{}) *MockAccountServiceInterface_SetDefaultAccount_Call {
	return &MockAccountServiceInterface_SetDefaultAccount_Call{Call: _e.mock.On("SetDefaultAccount", ctx, userID, accountID)}
}

func (_c *MockAccountServiceInterface_SetDefaultAccount_Call) Run(run func(ctx context.Context, userID int64, accountID int64)) *MockAccountServiceInterface_SetDefaultAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_SetDefaultAccount_Call) Return(err error) *MockAccountServiceInterface_SetDefaultAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_SetDefaultAccount_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID int64) error) *MockAccountServiceInterface_SetDefaultAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SyncAccountPnL provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) SyncAccountPnL(ctx context.Context, userID int64, accountID int64) error {
	ret := _mock.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for SyncAccountPnL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_SyncAccountPnL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAccountPnL'
type MockAccountServiceInterface_SyncAccountPnL_Call struct {
	*mock.Call
}

// SyncAccountPnL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID int64
func (_e *MockAccountServiceInterface_Expecter) SyncAccountPnL(ctx interface{}, userID interface{}, accountID interface{}) *MockAccountServiceInterface_SyncAccountPnL_Call {
	return &MockAccountServiceInterface_SyncAccountPnL_Call{Call: _e.mock.On("SyncAccountPnL", ctx, userID, accountID)}
}

func (_c *MockAccountServiceInterface_SyncAccountPnL_Call) Run(run func(ctx context.Context, userID int64, accountID int64)) *MockAccountServiceInterface_SyncAccountPnL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_SyncAccountPnL_Call) Return(err error) *MockAccountServiceInterface_SyncAccountPnL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_SyncAccountPnL_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID int64) error) *MockAccountServiceInterface_SyncAccountPnL_Call {
	_c.Call.Return(run)
	return _c
}

// SyncAssetPnL provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) SyncAssetPnL(ctx context.Context, userID int64, assetID int64) error {
	ret := _mock.Called(ctx, userID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for SyncAssetPnL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, assetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_SyncAssetPnL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAssetPnL'
type MockAccountServiceInterface_SyncAssetPnL_Call struct {
	*mock.Call
}

// SyncAssetPnL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - assetID int64
func (_e *MockAccountServiceInterface_Expecter) SyncAssetPnL(ctx interface{}, userID interface{}, assetID interface{}) *MockAccountServiceInterface_SyncAssetPnL_Call {
	return &MockAccountServiceInterface_SyncAssetPnL_Call{Call: _e.mock.On("SyncAssetPnL", ctx, userID, assetID)}
}

func (_c *MockAccountServiceInterface_SyncAssetPnL_Call) Run(run func(ctx context.Context, userID int64, assetID int64)) *MockAccountServiceInterface_SyncAssetPnL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_SyncAssetPnL_Call) Return(err error) *MockAccountServiceInterface_SyncAssetPnL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_SyncAssetPnL_Call) RunAndReturn(run func(ctx context.Context, userID int64, assetID int64) error) *MockAccountServiceInterface_SyncAssetPnL_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleAccountActiveState provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) ToggleAccountActiveState(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleAccountActiveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_ToggleAccountActiveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleAccountActiveState'
type MockAccountServiceInterface_ToggleAccountActiveState_Call struct {
	*mock.Call
}

// ToggleAccountActiveState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockAccountServiceInterface_Expecter) ToggleAccountActiveState(ctx interface{}, userID interface{}, id interface{}) *MockAccountServiceInterface_ToggleAccountActiveState_Call {
	return &MockAccountServiceInterface_ToggleAccountActiveState_Call{Call: _e.mock.On("ToggleAccountActiveState", ctx, userID, id)}
}

func (_c *MockAccountServiceInterface_ToggleAccountActiveState_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockAccountServiceInterface_ToggleAccountActiveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_ToggleAccountActiveState_Call) Return(err error) *MockAccountServiceInterface_ToggleAccountActiveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_ToggleAccountActiveState_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockAccountServiceInterface_ToggleAccountActiveState_Call {
	_c.Call.Return(run)
	return _c
}

// UnsetDefaultAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) UnsetDefaultAccount(ctx context.Context, userID int64, accountID int64) error {
	ret := _mock.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for UnsetDefaultAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_UnsetDefaultAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsetDefaultAccount'
type MockAccountServiceInterface_UnsetDefaultAccount_Call struct {
	*mock.Call
}

// UnsetDefaultAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - accountID int64
func (_e *MockAccountServiceInterface_Expecter) UnsetDefaultAccount(ctx interface{}, userID interface{}, accountID interface{}) *MockAccountServiceInterface_UnsetDefaultAccount_Call {
	return &MockAccountServiceInterface_UnsetDefaultAccount_Call{Call: _e.mock.On("UnsetDefaultAccount", ctx, userID, accountID)}
}

func (_c *MockAccountServiceInterface_UnsetDefaultAccount_Call) Run(run func(ctx context.Context, userID int64, accountID int64)) *MockAccountServiceInterface_UnsetDefaultAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_UnsetDefaultAccount_Call) Return(err error) *MockAccountServiceInterface_UnsetDefaultAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_UnsetDefaultAccount_Call) RunAndReturn(run func(ctx context.Context, userID int64, accountID int64) error) *MockAccountServiceInterface_UnsetDefaultAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) UpdateAccount(ctx context.Context, userID int64, id int64, req *models.AccountReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.AccountReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.AccountReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.AccountReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountServiceInterface_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockAccountServiceInterface_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.AccountReq
func (_e *MockAccountServiceInterface_Expecter) UpdateAccount(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockAccountServiceInterface_UpdateAccount_Call {
	return &MockAccountServiceInterface_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, userID, id, req)}
}

func (_c *MockAccountServiceInterface_UpdateAccount_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.AccountReq)) *MockAccountServiceInterface_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.AccountReq
		if args[3] != nil {
			arg3 = args[3].(*models.AccountReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_UpdateAccount_Call) Return(n int64, err error) *MockAccountServiceInterface_UpdateAccount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountServiceInterface_UpdateAccount_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.AccountReq) (int64, error)) *MockAccountServiceInterface_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountCashBalance provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) UpdateAccountCashBalance(ctx context.Context, tx *gorm.DB, acc *models.Account, asOf time.Time, transactionType string, amount decimal.Decimal) error {
	ret := _mock.Called(ctx, tx, acc, asOf, transactionType, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountCashBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Account, time.Time, string, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, tx, acc, asOf, transactionType, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_UpdateAccountCashBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountCashBalance'
type MockAccountServiceInterface_UpdateAccountCashBalance_Call struct {
	*mock.Call
}

// UpdateAccountCashBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - acc *models.Account
//   - asOf time.Time
//   - transactionType string
//   - amount decimal.Decimal
func (_e *MockAccountServiceInterface_Expecter) UpdateAccountCashBalance(ctx interface{}, tx interface{}, acc interface{}, asOf interface{}, transactionType interface{}, amount interface{}) *MockAccountServiceInterface_UpdateAccountCashBalance_Call {
	return &MockAccountServiceInterface_UpdateAccountCashBalance_Call{Call: _e.mock.On("UpdateAccountCashBalance", ctx, tx, acc, asOf, transactionType, amount)}
}

func (_c *MockAccountServiceInterface_UpdateAccountCashBalance_Call) Run(run func(ctx context.Context, tx *gorm.DB, acc *models.Account, asOf time.Time, transactionType string, amount decimal.Decimal)) *MockAccountServiceInterface_UpdateAccountCashBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *models.Account
		if args[2] != nil {
			arg2 = args[2].(*models.Account)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 decimal.Decimal
		if args[5] != nil {
			arg5 = args[5].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_UpdateAccountCashBalance_Call) Return(err error) *MockAccountServiceInterface_UpdateAccountCashBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_UpdateAccountCashBalance_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, acc *models.Account, asOf time.Time, transactionType string, amount decimal.Decimal) error) *MockAccountServiceInterface_UpdateAccountCashBalance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalancesForTransfer provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) UpdateBalancesForTransfer(ctx context.Context, tx *gorm.DB, fromAcc *models.Account, toAcc *models.Account, when time.Time, amount decimal.Decimal) error {
	ret := _mock.Called(ctx, tx, fromAcc, toAcc, when, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalancesForTransfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Account, *models.Account, time.Time, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, tx, fromAcc, toAcc, when, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_UpdateBalancesForTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalancesForTransfer'
type MockAccountServiceInterface_UpdateBalancesForTransfer_Call struct {
	*mock.Call
}

// UpdateBalancesForTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - fromAcc *models.Account
//   - toAcc *models.Account
//   - when time.Time
//   - amount decimal.Decimal
func (_e *MockAccountServiceInterface_Expecter) UpdateBalancesForTransfer(ctx interface{}, tx interface{}, fromAcc interface{}, toAcc interface{}, when interface{}, amount interface{}) *MockAccountServiceInterface_UpdateBalancesForTransfer_Call {
	return &MockAccountServiceInterface_UpdateBalancesForTransfer_Call{Call: _e.mock.On("UpdateBalancesForTransfer", ctx, tx, fromAcc, toAcc, when, amount)}
}

func (_c *MockAccountServiceInterface_UpdateBalancesForTransfer_Call) Run(run func(ctx context.Context, tx *gorm.DB, fromAcc *models.Account, toAcc *models.Account, when time.Time, amount decimal.Decimal)) *MockAccountServiceInterface_UpdateBalancesForTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *models.Account
		if args[2] != nil {
			arg2 = args[2].(*models.Account)
		}
		var arg3 *models.Account
		if args[3] != nil {
			arg3 = args[3].(*models.Account)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 decimal.Decimal
		if args[5] != nil {
			arg5 = args[5].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_UpdateBalancesForTransfer_Call) Return(err error) *MockAccountServiceInterface_UpdateBalancesForTransfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_UpdateBalancesForTransfer_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, fromAcc *models.Account, toAcc *models.Account, when time.Time, amount decimal.Decimal) error) *MockAccountServiceInterface_UpdateBalancesForTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDailyCashNoSnapshot provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) UpdateDailyCashNoSnapshot(ctx context.Context, tx *gorm.DB, acc *models.Account, asOf time.Time, txnType string, amt decimal.Decimal) error {
	ret := _mock.Called(ctx, tx, acc, asOf, txnType, amt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDailyCashNoSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Account, time.Time, string, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, tx, acc, asOf, txnType, amt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDailyCashNoSnapshot'
type MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call struct {
	*mock.Call
}

// UpdateDailyCashNoSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - acc *models.Account
//   - asOf time.Time
//   - txnType string
//   - amt decimal.Decimal
func (_e *MockAccountServiceInterface_Expecter) UpdateDailyCashNoSnapshot(ctx interface{}, tx interface{}, acc interface{}, asOf interface{}, txnType interface{}, amt interface{}) *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call {
	return &MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call{Call: _e.mock.On("UpdateDailyCashNoSnapshot", ctx, tx, acc, asOf, txnType, amt)}
}

func (_c *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call) Run(run func(ctx context.Context, tx *gorm.DB, acc *models.Account, asOf time.Time, txnType string, amt decimal.Decimal)) *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *models.Account
		if args[2] != nil {
			arg2 = args[2].(*models.Account)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 decimal.Decimal
		if args[5] != nil {
			arg5 = args[5].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call) Return(err error) *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, acc *models.Account, asOf time.Time, txnType string, amt decimal.Decimal) error) *MockAccountServiceInterface_UpdateDailyCashNoSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSnapshotMarketValues provides a mock function for the type MockAccountServiceInterface
func (_mock *MockAccountServiceInterface) UpdateSnapshotMarketValues(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSnapshotMarketValues")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountServiceInterface_UpdateSnapshotMarketValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSnapshotMarketValues'
type MockAccountServiceInterface_UpdateSnapshotMarketValues_Call struct {
	*mock.Call
}

// UpdateSnapshotMarketValues is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAccountServiceInterface_Expecter) UpdateSnapshotMarketValues(ctx interface{}, userID interface{}) *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call {
	return &MockAccountServiceInterface_UpdateSnapshotMarketValues_Call{Call: _e.mock.On("UpdateSnapshotMarketValues", ctx, userID)}
}

func (_c *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call) Run(run func(ctx context.Context, userID int64)) *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call) Return(err error) *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockAccountServiceInterface_UpdateSnapshotMarketValues_Call {
	_c.Call.Return(run)
	return _c
}
