// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"
	"wealth-warden/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotesServiceInterface creates a new instance of MockNotesServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotesServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotesServiceInterface {
	mock := &MockNotesServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotesServiceInterface is an autogenerated mock type for the NotesServiceInterface type
type MockNotesServiceInterface struct {
	mock.Mock
}

type MockNotesServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotesServiceInterface) EXPECT() *MockNotesServiceInterface_Expecter {
	return &MockNotesServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteNote provides a mock function for the type MockNotesServiceInterface
func (_mock *MockNotesServiceInterface) DeleteNote(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotesServiceInterface_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockNotesServiceInterface_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockNotesServiceInterface_Expecter) DeleteNote(ctx any, userID any, id any) *MockNotesServiceInterface_DeleteNote_Call {
	return &MockNotesServiceInterface_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, userID, id)}
}

func (_c *MockNotesServiceInterface_DeleteNote_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockNotesServiceInterface_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesServiceInterface_DeleteNote_Call) Return(err error) *MockNotesServiceInterface_DeleteNote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotesServiceInterface_DeleteNote_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockNotesServiceInterface_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// FetchNoteByID provides a mock function for the type MockNotesServiceInterface
func (_mock *MockNotesServiceInterface) FetchNoteByID(ctx context.Context, userID int64, id int64) (*models.Note, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchNoteByID")
	}

	var r0 *models.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.Note, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.Note); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesServiceInterface_FetchNoteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchNoteByID'
type MockNotesServiceInterface_FetchNoteByID_Call struct {
	*mock.Call
}

// FetchNoteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockNotesServiceInterface_Expecter) FetchNoteByID(ctx any, userID any, id any) *MockNotesServiceInterface_FetchNoteByID_Call {
	return &MockNotesServiceInterface_FetchNoteByID_Call{Call: _e.mock.On("FetchNoteByID", ctx, userID, id)}
}

func (_c *MockNotesServiceInterface_FetchNoteByID_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockNotesServiceInterface_FetchNoteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesServiceInterface_FetchNoteByID_Call) Return(note *models.Note, err error) *MockNotesServiceInterface_FetchNoteByID_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNotesServiceInterface_FetchNoteByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (*models.Note, error)) *MockNotesServiceInterface_FetchNoteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchNotesPaginated provides a mock function for the type MockNotesServiceInterface
func (_mock *MockNotesServiceInterface) FetchNotesPaginated(ctx context.Context, userID int64, p utils.PaginationParams) ([]models.Note, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, p)

	if len(ret) == 0 {
		panic("no return value specified for FetchNotesPaginated")
	}

	var r0 []models.Note
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams) ([]models.Note, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams) []models.Note); ok {
		r0 = returnFunc(ctx, userID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, utils.PaginationParams) *utils.Paginator); ok {
		r1 = returnFunc(ctx, userID, p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, utils.PaginationParams) error); ok {
		r2 = returnFunc(ctx, userID, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotesServiceInterface_FetchNotesPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchNotesPaginated'
type MockNotesServiceInterface_FetchNotesPaginated_Call struct {
	*mock.Call
}

// FetchNotesPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p utils.PaginationParams
func (_e *MockNotesServiceInterface_Expecter) FetchNotesPaginated(ctx any, userID any, p any) *MockNotesServiceInterface_FetchNotesPaginated_Call {
	return &MockNotesServiceInterface_FetchNotesPaginated_Call{Call: _e.mock.On("FetchNotesPaginated", ctx, userID, p)}
}

func (_c *MockNotesServiceInterface_FetchNotesPaginated_Call) Run(run func(ctx context.Context, userID int64, p utils.PaginationParams)) *MockNotesServiceInterface_FetchNotesPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 utils.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(utils.PaginationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesServiceInterface_FetchNotesPaginated_Call) Return(notes []models.Note, paginator *utils.Paginator, err error) *MockNotesServiceInterface_FetchNotesPaginated_Call {
	_c.Call.Return(notes, paginator, err)
	return _c
}

func (_c *MockNotesServiceInterface_FetchNotesPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, p utils.PaginationParams) ([]models.Note, *utils.Paginator, error)) *MockNotesServiceInterface_FetchNotesPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// InsertNote provides a mock function for the type MockNotesServiceInterface
func (_mock *MockNotesServiceInterface) InsertNote(ctx context.Context, userID int64, req *models.NoteReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertNote")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.NoteReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.NoteReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.NoteReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesServiceInterface_InsertNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertNote'
type MockNotesServiceInterface_InsertNote_Call struct {
	*mock.Call
}

// InsertNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.NoteReq
func (_e *MockNotesServiceInterface_Expecter) InsertNote(ctx any, userID any, req any) *MockNotesServiceInterface_InsertNote_Call {
	return &MockNotesServiceInterface_InsertNote_Call{Call: _e.mock.On("InsertNote", ctx, userID, req)}
}

func (_c *MockNotesServiceInterface_InsertNote_Call) Run(run func(ctx context.Context, userID int64, req *models.NoteReq)) *MockNotesServiceInterface_InsertNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.NoteReq
		if args[2] != nil {
			arg2 = args[2].(*models.NoteReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesServiceInterface_InsertNote_Call) Return(n int64, err error) *MockNotesServiceInterface_InsertNote_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotesServiceInterface_InsertNote_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.NoteReq) (int64, error)) *MockNotesServiceInterface_InsertNote_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleResolveState provides a mock function for the type MockNotesServiceInterface
func (_mock *MockNotesServiceInterface) ToggleResolveState(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleResolveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotesServiceInterface_ToggleResolveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleResolveState'
type MockNotesServiceInterface_ToggleResolveState_Call struct {
	*mock.Call
}

// ToggleResolveState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockNotesServiceInterface_Expecter) ToggleResolveState(ctx any, userID any, id any) *MockNotesServiceInterface_ToggleResolveState_Call {
	return &MockNotesServiceInterface_ToggleResolveState_Call{Call: _e.mock.On("ToggleResolveState", ctx, userID, id)}
}

func (_c *MockNotesServiceInterface_ToggleResolveState_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockNotesServiceInterface_ToggleResolveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesServiceInterface_ToggleResolveState_Call) Return(err error) *MockNotesServiceInterface_ToggleResolveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotesServiceInterface_ToggleResolveState_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockNotesServiceInterface_ToggleResolveState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNote provides a mock function for the type MockNotesServiceInterface
func (_mock *MockNotesServiceInterface) UpdateNote(ctx context.Context, userID int64, id int64, req *models.NoteReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.NoteReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.NoteReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.NoteReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesServiceInterface_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type MockNotesServiceInterface_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.NoteReq
func (_e *MockNotesServiceInterface_Expecter) UpdateNote(ctx any, userID any, id any, req any) *MockNotesServiceInterface_UpdateNote_Call {
	return &MockNotesServiceInterface_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, userID, id, req)}
}

func (_c *MockNotesServiceInterface_UpdateNote_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.NoteReq)) *MockNotesServiceInterface_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.NoteReq
		if args[3] != nil {
			arg3 = args[3].(*models.NoteReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotesServiceInterface_UpdateNote_Call) Return(n int64, err error) *MockNotesServiceInterface_UpdateNote_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotesServiceInterface_UpdateNote_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.NoteReq) (int64, error)) *MockNotesServiceInterface_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}
