// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "wealth-warden/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// ConfirmEmail provides a mock function with given fields: ctx, tokenValue, userAgent, ip
func (_m *MockAuthServiceInterface) ConfirmEmail(ctx context.Context, tokenValue string, userAgent string, ip string) error {
	ret := _m.Called(ctx, tokenValue, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tokenValue, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_ConfirmEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmEmail'
type MockAuthServiceInterface_ConfirmEmail_Call struct {
	*mock.Call
}

// ConfirmEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenValue string
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) ConfirmEmail(ctx interface{}, tokenValue interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_ConfirmEmail_Call {
	return &MockAuthServiceInterface_ConfirmEmail_Call{Call: _e.mock.On("ConfirmEmail", ctx, tokenValue, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_ConfirmEmail_Call) Run(run func(ctx context.Context, tokenValue string, userAgent string, ip string)) *MockAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ConfirmEmail_Call) Return(_a0 error) *MockAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_ConfirmEmail_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUser provides a mock function with given fields: ctx, userID
func (_m *MockAuthServiceInterface) GetCurrentUser(ctx context.Context, userID int64) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_GetCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUser'
type MockAuthServiceInterface_GetCurrentUser_Call struct {
	*mock.Call
}

// GetCurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthServiceInterface_Expecter) GetCurrentUser(ctx interface{}, userID interface{}) *MockAuthServiceInterface_GetCurrentUser_Call {
	return &MockAuthServiceInterface_GetCurrentUser_Call{Call: _e.mock.On("GetCurrentUser", ctx, userID)}
}

func (_c *MockAuthServiceInterface_GetCurrentUser_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthServiceInterface_GetCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAuthServiceInterface_GetCurrentUser_Call) Return(_a0 *models.User, _a1 error) *MockAuthServiceInterface_GetCurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_GetCurrentUser_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *MockAuthServiceInterface_GetCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, form, userAgent, ip
func (_m *MockAuthServiceInterface) RegisterUser(ctx context.Context, form models.RegisterForm, userAgent string, ip string) error {
	ret := _m.Called(ctx, form, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RegisterForm, string, string) error); ok {
		r0 = rf(ctx, form, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockAuthServiceInterface_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - form models.RegisterForm
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) RegisterUser(ctx interface{}, form interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_RegisterUser_Call {
	return &MockAuthServiceInterface_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, form, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_RegisterUser_Call) Run(run func(ctx context.Context, form models.RegisterForm, userAgent string, ip string)) *MockAuthServiceInterface_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RegisterForm), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_RegisterUser_Call) Return(_a0 error) *MockAuthServiceInterface_RegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_RegisterUser_Call) RunAndReturn(run func(context.Context, models.RegisterForm, string, string) error) *MockAuthServiceInterface_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, email, userAgent, ip
func (_m *MockAuthServiceInterface) RequestPasswordReset(ctx context.Context, email string, userAgent string, ip string) error {
	ret := _m.Called(ctx, email, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockAuthServiceInterface_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) RequestPasswordReset(ctx interface{}, email interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_RequestPasswordReset_Call {
	return &MockAuthServiceInterface_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string, userAgent string, ip string)) *MockAuthServiceInterface_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_RequestPasswordReset_Call) Return(_a0 error) *MockAuthServiceInterface_RequestPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAuthServiceInterface_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResendConfirmationEmail provides a mock function with given fields: ctx, email, userAgent, ip
func (_m *MockAuthServiceInterface) ResendConfirmationEmail(ctx context.Context, email string, userAgent string, ip string) error {
	ret := _m.Called(ctx, email, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for ResendConfirmationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_ResendConfirmationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendConfirmationEmail'
type MockAuthServiceInterface_ResendConfirmationEmail_Call struct {
	*mock.Call
}

// ResendConfirmationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) ResendConfirmationEmail(ctx interface{}, email interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_ResendConfirmationEmail_Call {
	return &MockAuthServiceInterface_ResendConfirmationEmail_Call{Call: _e.mock.On("ResendConfirmationEmail", ctx, email, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_ResendConfirmationEmail_Call) Run(run func(ctx context.Context, email string, userAgent string, ip string)) *MockAuthServiceInterface_ResendConfirmationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ResendConfirmationEmail_Call) Return(_a0 error) *MockAuthServiceInterface_ResendConfirmationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_ResendConfirmationEmail_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAuthServiceInterface_ResendConfirmationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, form, userAgent, ip
func (_m *MockAuthServiceInterface) ResetPassword(ctx context.Context, form models.ResetPasswordForm, userAgent string, ip string) error {
	ret := _m.Called(ctx, form, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ResetPasswordForm, string, string) error); ok {
		r0 = rf(ctx, form, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthServiceInterface_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - form models.ResetPasswordForm
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) ResetPassword(ctx interface{}, form interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_ResetPassword_Call {
	return &MockAuthServiceInterface_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, form, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_ResetPassword_Call) Run(run func(ctx context.Context, form models.ResetPasswordForm, userAgent string, ip string)) *MockAuthServiceInterface_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ResetPasswordForm), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ResetPassword_Call) Return(_a0 error) *MockAuthServiceInterface_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_ResetPassword_Call) RunAndReturn(run func(context.Context, models.ResetPasswordForm, string, string) error) *MockAuthServiceInterface_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function with given fields: ctx, form, userAgent, ip
func (_m *MockAuthServiceInterface) SignUp(ctx context.Context, form models.RegisterForm, userAgent string, ip string) error {
	ret := _m.Called(ctx, form, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RegisterForm, string, string) error); ok {
		r0 = rf(ctx, form, userAgent, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockAuthServiceInterface_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - form models.RegisterForm
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) SignUp(ctx interface{}, form interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_SignUp_Call {
	return &MockAuthServiceInterface_SignUp_Call{Call: _e.mock.On("SignUp", ctx, form, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_SignUp_Call) Run(run func(ctx context.Context, form models.RegisterForm, userAgent string, ip string)) *MockAuthServiceInterface_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RegisterForm), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_SignUp_Call) Return(_a0 error) *MockAuthServiceInterface_SignUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_SignUp_Call) RunAndReturn(run func(context.Context, models.RegisterForm, string, string) error) *MockAuthServiceInterface_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateInvitation provides a mock function with given fields: ctx, hash
func (_m *MockAuthServiceInterface) ValidateInvitation(ctx context.Context, hash string) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ValidateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_ValidateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateInvitation'
type MockAuthServiceInterface_ValidateInvitation_Call struct {
	*mock.Call
}

// ValidateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockAuthServiceInterface_Expecter) ValidateInvitation(ctx interface{}, hash interface{}) *MockAuthServiceInterface_ValidateInvitation_Call {
	return &MockAuthServiceInterface_ValidateInvitation_Call{Call: _e.mock.On("ValidateInvitation", ctx, hash)}
}

func (_c *MockAuthServiceInterface_ValidateInvitation_Call) Run(run func(ctx context.Context, hash string)) *MockAuthServiceInterface_ValidateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ValidateInvitation_Call) Return(_a0 error) *MockAuthServiceInterface_ValidateInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_ValidateInvitation_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServiceInterface_ValidateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateLogin provides a mock function with given fields: ctx, email, password, userAgent, ip
func (_m *MockAuthServiceInterface) ValidateLogin(ctx context.Context, email string, password string, userAgent string, ip string) (*models.User, error) {
	ret := _m.Called(ctx, email, password, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogin")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*models.User, error)); ok {
		return rf(ctx, email, password, userAgent, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *models.User); ok {
		r0 = rf(ctx, email, password, userAgent, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, password, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_ValidateLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateLogin'
type MockAuthServiceInterface_ValidateLogin_Call struct {
	*mock.Call
}

// ValidateLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - userAgent string
//   - ip string
func (_e *MockAuthServiceInterface_Expecter) ValidateLogin(ctx interface{}, email interface{}, password interface{}, userAgent interface{}, ip interface{}) *MockAuthServiceInterface_ValidateLogin_Call {
	return &MockAuthServiceInterface_ValidateLogin_Call{Call: _e.mock.On("ValidateLogin", ctx, email, password, userAgent, ip)}
}

func (_c *MockAuthServiceInterface_ValidateLogin_Call) Run(run func(ctx context.Context, email string, password string, userAgent string, ip string)) *MockAuthServiceInterface_ValidateLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ValidateLogin_Call) Return(_a0 *models.User, _a1 error) *MockAuthServiceInterface_ValidateLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_ValidateLogin_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*models.User, error)) *MockAuthServiceInterface_ValidateLogin_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePasswordReset provides a mock function with given fields: ctx, tokenValue
func (_m *MockAuthServiceInterface) ValidatePasswordReset(ctx context.Context, tokenValue string) (string, error) {
	ret := _m.Called(ctx, tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePasswordReset")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tokenValue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tokenValue)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_ValidatePasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePasswordReset'
type MockAuthServiceInterface_ValidatePasswordReset_Call struct {
	*mock.Call
}

// ValidatePasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenValue string
func (_e *MockAuthServiceInterface_Expecter) ValidatePasswordReset(ctx interface{}, tokenValue interface{}) *MockAuthServiceInterface_ValidatePasswordReset_Call {
	return &MockAuthServiceInterface_ValidatePasswordReset_Call{Call: _e.mock.On("ValidatePasswordReset", ctx, tokenValue)}
}

func (_c *MockAuthServiceInterface_ValidatePasswordReset_Call) Run(run func(ctx context.Context, tokenValue string)) *MockAuthServiceInterface_ValidatePasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ValidatePasswordReset_Call) Return(_a0 string, _a1 error) *MockAuthServiceInterface_ValidatePasswordReset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_ValidatePasswordReset_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockAuthServiceInterface_ValidatePasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
