// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"
	"wealth-warden/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteInvitation provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) DeleteInvitation(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvitation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserServiceInterface_DeleteInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvitation'
type MockUserServiceInterface_DeleteInvitation_Call struct {
	*mock.Call
}

// DeleteInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockUserServiceInterface_Expecter) DeleteInvitation(ctx any, userID any, id any) *MockUserServiceInterface_DeleteInvitation_Call {
	return &MockUserServiceInterface_DeleteInvitation_Call{Call: _e.mock.On("DeleteInvitation", ctx, userID, id)}
}

func (_c *MockUserServiceInterface_DeleteInvitation_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockUserServiceInterface_DeleteInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_DeleteInvitation_Call) Return(err error) *MockUserServiceInterface_DeleteInvitation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserServiceInterface_DeleteInvitation_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockUserServiceInterface_DeleteInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) DeleteUser(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserServiceInterface_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserServiceInterface_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockUserServiceInterface_Expecter) DeleteUser(ctx any, userID any, id any) *MockUserServiceInterface_DeleteUser_Call {
	return &MockUserServiceInterface_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID, id)}
}

func (_c *MockUserServiceInterface_DeleteUser_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockUserServiceInterface_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_DeleteUser_Call) Return(err error) *MockUserServiceInterface_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserServiceInterface_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockUserServiceInterface_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// FetchInvitationByHash provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) FetchInvitationByHash(ctx context.Context, hash string) (*models.Invitation, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FetchInvitationByHash")
	}

	var r0 *models.Invitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Invitation, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Invitation); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_FetchInvitationByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInvitationByHash'
type MockUserServiceInterface_FetchInvitationByHash_Call struct {
	*mock.Call
}

// FetchInvitationByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockUserServiceInterface_Expecter) FetchInvitationByHash(ctx any, hash any) *MockUserServiceInterface_FetchInvitationByHash_Call {
	return &MockUserServiceInterface_FetchInvitationByHash_Call{Call: _e.mock.On("FetchInvitationByHash", ctx, hash)}
}

func (_c *MockUserServiceInterface_FetchInvitationByHash_Call) Run(run func(ctx context.Context, hash string)) *MockUserServiceInterface_FetchInvitationByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_FetchInvitationByHash_Call) Return(invitation *models.Invitation, err error) *MockUserServiceInterface_FetchInvitationByHash_Call {
	_c.Call.Return(invitation, err)
	return _c
}

func (_c *MockUserServiceInterface_FetchInvitationByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*models.Invitation, error)) *MockUserServiceInterface_FetchInvitationByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FetchInvitationsPaginated provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) FetchInvitationsPaginated(ctx context.Context, p utils.PaginationParams) ([]models.Invitation, *utils.Paginator, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for FetchInvitationsPaginated")
	}

	var r0 []models.Invitation
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.PaginationParams) ([]models.Invitation, *utils.Paginator, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.PaginationParams) []models.Invitation); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Invitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, utils.PaginationParams) *utils.Paginator); ok {
		r1 = returnFunc(ctx, p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, utils.PaginationParams) error); ok {
		r2 = returnFunc(ctx, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserServiceInterface_FetchInvitationsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInvitationsPaginated'
type MockUserServiceInterface_FetchInvitationsPaginated_Call struct {
	*mock.Call
}

// FetchInvitationsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - p utils.PaginationParams
func (_e *MockUserServiceInterface_Expecter) FetchInvitationsPaginated(ctx any, p any) *MockUserServiceInterface_FetchInvitationsPaginated_Call {
	return &MockUserServiceInterface_FetchInvitationsPaginated_Call{Call: _e.mock.On("FetchInvitationsPaginated", ctx, p)}
}

func (_c *MockUserServiceInterface_FetchInvitationsPaginated_Call) Run(run func(ctx context.Context, p utils.PaginationParams)) *MockUserServiceInterface_FetchInvitationsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 utils.PaginationParams
		if args[1] != nil {
			arg1 = args[1].(utils.PaginationParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_FetchInvitationsPaginated_Call) Return(invitations []models.Invitation, paginator *utils.Paginator, err error) *MockUserServiceInterface_FetchInvitationsPaginated_Call {
	_c.Call.Return(invitations, paginator, err)
	return _c
}

func (_c *MockUserServiceInterface_FetchInvitationsPaginated_Call) RunAndReturn(run func(ctx context.Context, p utils.PaginationParams) ([]models.Invitation, *utils.Paginator, error)) *MockUserServiceInterface_FetchInvitationsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserByID provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) FetchUserByID(ctx context.Context, ID int64) (*models.User, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_FetchUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserByID'
type MockUserServiceInterface_FetchUserByID_Call struct {
	*mock.Call
}

// FetchUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *MockUserServiceInterface_Expecter) FetchUserByID(ctx any, ID any) *MockUserServiceInterface_FetchUserByID_Call {
	return &MockUserServiceInterface_FetchUserByID_Call{Call: _e.mock.On("FetchUserByID", ctx, ID)}
}

func (_c *MockUserServiceInterface_FetchUserByID_Call) Run(run func(ctx context.Context, ID int64)) *MockUserServiceInterface_FetchUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_FetchUserByID_Call) Return(user *models.User, err error) *MockUserServiceInterface_FetchUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserServiceInterface_FetchUserByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (*models.User, error)) *MockUserServiceInterface_FetchUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserByToken provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) FetchUserByToken(ctx context.Context, tokenType string, tokenValue string) (*models.User, error) {
	ret := _mock.Called(ctx, tokenType, tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserByToken")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return returnFunc(ctx, tokenType, tokenValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = returnFunc(ctx, tokenType, tokenValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tokenType, tokenValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_FetchUserByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserByToken'
type MockUserServiceInterface_FetchUserByToken_Call struct {
	*mock.Call
}

// FetchUserByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenType string
//   - tokenValue string
func (_e *MockUserServiceInterface_Expecter) FetchUserByToken(ctx any, tokenType any, tokenValue any) *MockUserServiceInterface_FetchUserByToken_Call {
	return &MockUserServiceInterface_FetchUserByToken_Call{Call: _e.mock.On("FetchUserByToken", ctx, tokenType, tokenValue)}
}

func (_c *MockUserServiceInterface_FetchUserByToken_Call) Run(run func(ctx context.Context, tokenType string, tokenValue string)) *MockUserServiceInterface_FetchUserByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_FetchUserByToken_Call) Return(user *models.User, err error) *MockUserServiceInterface_FetchUserByToken_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserServiceInterface_FetchUserByToken_Call) RunAndReturn(run func(ctx context.Context, tokenType string, tokenValue string) (*models.User, error)) *MockUserServiceInterface_FetchUserByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUsersPaginated provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) FetchUsersPaginated(ctx context.Context, p utils.PaginationParams, includeDeleted bool) ([]models.User, *utils.Paginator, error) {
	ret := _mock.Called(ctx, p, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for FetchUsersPaginated")
	}

	var r0 []models.User
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.PaginationParams, bool) ([]models.User, *utils.Paginator, error)); ok {
		return returnFunc(ctx, p, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, utils.PaginationParams, bool) []models.User); ok {
		r0 = returnFunc(ctx, p, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, utils.PaginationParams, bool) *utils.Paginator); ok {
		r1 = returnFunc(ctx, p, includeDeleted)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, utils.PaginationParams, bool) error); ok {
		r2 = returnFunc(ctx, p, includeDeleted)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserServiceInterface_FetchUsersPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUsersPaginated'
type MockUserServiceInterface_FetchUsersPaginated_Call struct {
	*mock.Call
}

// FetchUsersPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - p utils.PaginationParams
//   - includeDeleted bool
func (_e *MockUserServiceInterface_Expecter) FetchUsersPaginated(ctx any, p any, includeDeleted any) *MockUserServiceInterface_FetchUsersPaginated_Call {
	return &MockUserServiceInterface_FetchUsersPaginated_Call{Call: _e.mock.On("FetchUsersPaginated", ctx, p, includeDeleted)}
}

func (_c *MockUserServiceInterface_FetchUsersPaginated_Call) Run(run func(ctx context.Context, p utils.PaginationParams, includeDeleted bool)) *MockUserServiceInterface_FetchUsersPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 utils.PaginationParams
		if args[1] != nil {
			arg1 = args[1].(utils.PaginationParams)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_FetchUsersPaginated_Call) Return(users []models.User, paginator *utils.Paginator, err error) *MockUserServiceInterface_FetchUsersPaginated_Call {
	_c.Call.Return(users, paginator, err)
	return _c
}

func (_c *MockUserServiceInterface_FetchUsersPaginated_Call) RunAndReturn(run func(ctx context.Context, p utils.PaginationParams, includeDeleted bool) ([]models.User, *utils.Paginator, error)) *MockUserServiceInterface_FetchUsersPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllActiveUserIDs provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) GetAllActiveUserIDs(ctx context.Context) ([]int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllActiveUserIDs")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []int64); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_GetAllActiveUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllActiveUserIDs'
type MockUserServiceInterface_GetAllActiveUserIDs_Call struct {
	*mock.Call
}

// GetAllActiveUserIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserServiceInterface_Expecter) GetAllActiveUserIDs(ctx any) *MockUserServiceInterface_GetAllActiveUserIDs_Call {
	return &MockUserServiceInterface_GetAllActiveUserIDs_Call{Call: _e.mock.On("GetAllActiveUserIDs", ctx)}
}

func (_c *MockUserServiceInterface_GetAllActiveUserIDs_Call) Run(run func(ctx context.Context)) *MockUserServiceInterface_GetAllActiveUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_GetAllActiveUserIDs_Call) Return(int64s []int64, err error) *MockUserServiceInterface_GetAllActiveUserIDs_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockUserServiceInterface_GetAllActiveUserIDs_Call) RunAndReturn(run func(ctx context.Context) ([]int64, error)) *MockUserServiceInterface_GetAllActiveUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertInvitation provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) InsertInvitation(ctx context.Context, userID int64, req models.InvitationReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertInvitation")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.InvitationReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.InvitationReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, models.InvitationReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_InsertInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertInvitation'
type MockUserServiceInterface_InsertInvitation_Call struct {
	*mock.Call
}

// InsertInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req models.InvitationReq
func (_e *MockUserServiceInterface_Expecter) InsertInvitation(ctx any, userID any, req any) *MockUserServiceInterface_InsertInvitation_Call {
	return &MockUserServiceInterface_InsertInvitation_Call{Call: _e.mock.On("InsertInvitation", ctx, userID, req)}
}

func (_c *MockUserServiceInterface_InsertInvitation_Call) Run(run func(ctx context.Context, userID int64, req models.InvitationReq)) *MockUserServiceInterface_InsertInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.InvitationReq
		if args[2] != nil {
			arg2 = args[2].(models.InvitationReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_InsertInvitation_Call) Return(n int64, err error) *MockUserServiceInterface_InsertInvitation_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserServiceInterface_InsertInvitation_Call) RunAndReturn(run func(ctx context.Context, userID int64, req models.InvitationReq) (int64, error)) *MockUserServiceInterface_InsertInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// ResendInvitation provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) ResendInvitation(ctx context.Context, userID int64, id int64) (int64, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for ResendInvitation")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_ResendInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendInvitation'
type MockUserServiceInterface_ResendInvitation_Call struct {
	*mock.Call
}

// ResendInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockUserServiceInterface_Expecter) ResendInvitation(ctx any, userID any, id any) *MockUserServiceInterface_ResendInvitation_Call {
	return &MockUserServiceInterface_ResendInvitation_Call{Call: _e.mock.On("ResendInvitation", ctx, userID, id)}
}

func (_c *MockUserServiceInterface_ResendInvitation_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockUserServiceInterface_ResendInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_ResendInvitation_Call) Return(n int64, err error) *MockUserServiceInterface_ResendInvitation_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserServiceInterface_ResendInvitation_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (int64, error)) *MockUserServiceInterface_ResendInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsersByEmail provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) SearchUsersByEmail(ctx context.Context, q string) ([]models.UserLookup, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsersByEmail")
	}

	var r0 []models.UserLookup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.UserLookup, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.UserLookup); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserLookup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_SearchUsersByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsersByEmail'
type MockUserServiceInterface_SearchUsersByEmail_Call struct {
	*mock.Call
}

// SearchUsersByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - q string
func (_e *MockUserServiceInterface_Expecter) SearchUsersByEmail(ctx any, q any) *MockUserServiceInterface_SearchUsersByEmail_Call {
	return &MockUserServiceInterface_SearchUsersByEmail_Call{Call: _e.mock.On("SearchUsersByEmail", ctx, q)}
}

func (_c *MockUserServiceInterface_SearchUsersByEmail_Call) Run(run func(ctx context.Context, q string)) *MockUserServiceInterface_SearchUsersByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_SearchUsersByEmail_Call) Return(userLookups []models.UserLookup, err error) *MockUserServiceInterface_SearchUsersByEmail_Call {
	_c.Call.Return(userLookups, err)
	return _c
}

func (_c *MockUserServiceInterface_SearchUsersByEmail_Call) RunAndReturn(run func(ctx context.Context, q string) ([]models.UserLookup, error)) *MockUserServiceInterface_SearchUsersByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) UpdateUser(ctx context.Context, userID int64, id int64, req *models.UserReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.UserReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.UserReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.UserReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserServiceInterface_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.UserReq
func (_e *MockUserServiceInterface_Expecter) UpdateUser(ctx any, userID any, id any, req any) *MockUserServiceInterface_UpdateUser_Call {
	return &MockUserServiceInterface_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, id, req)}
}

func (_c *MockUserServiceInterface_UpdateUser_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.UserReq)) *MockUserServiceInterface_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.UserReq
		if args[3] != nil {
			arg3 = args[3].(*models.UserReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_UpdateUser_Call) Return(n int64, err error) *MockUserServiceInterface_UpdateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserServiceInterface_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.UserReq) (int64, error)) *MockUserServiceInterface_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
