// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWebClientMiddlewareInterface creates a new instance of MockWebClientMiddlewareInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebClientMiddlewareInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebClientMiddlewareInterface {
	mock := &MockWebClientMiddlewareInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebClientMiddlewareInterface is an autogenerated mock type for the WebClientMiddlewareInterface type
type MockWebClientMiddlewareInterface struct {
	mock.Mock
}

type MockWebClientMiddlewareInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebClientMiddlewareInterface) EXPECT() *MockWebClientMiddlewareInterface_Expecter {
	return &MockWebClientMiddlewareInterface_Expecter{mock: &_m.Mock}
}

// CookieDomainForEnv provides a mock function for the type MockWebClientMiddlewareInterface
func (_mock *MockWebClientMiddlewareInterface) CookieDomainForEnv() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CookieDomainForEnv")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWebClientMiddlewareInterface_CookieDomainForEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CookieDomainForEnv'
type MockWebClientMiddlewareInterface_CookieDomainForEnv_Call struct {
	*mock.Call
}

// CookieDomainForEnv is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) CookieDomainForEnv() *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	return &MockWebClientMiddlewareInterface_CookieDomainForEnv_Call{Call: _e.mock.On("CookieDomainForEnv")}
}

func (_c *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call) Run(run func()) *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call) Return(s string) *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call) RunAndReturn(run func() string) *MockWebClientMiddlewareInterface_CookieDomainForEnv_Call {
	_c.Call.Return(run)
	return _c
}

// CookieSecure provides a mock function for the type MockWebClientMiddlewareInterface
func (_mock *MockWebClientMiddlewareInterface) CookieSecure() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CookieSecure")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockWebClientMiddlewareInterface_CookieSecure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CookieSecure'
type MockWebClientMiddlewareInterface_CookieSecure_Call struct {
	*mock.Call
}

// CookieSecure is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) CookieSecure() *MockWebClientMiddlewareInterface_CookieSecure_Call {
	return &MockWebClientMiddlewareInterface_CookieSecure_Call{Call: _e.mock.On("CookieSecure")}
}

func (_c *MockWebClientMiddlewareInterface_CookieSecure_Call) Run(run func()) *MockWebClientMiddlewareInterface_CookieSecure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieSecure_Call) Return(b bool) *MockWebClientMiddlewareInterface_CookieSecure_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CookieSecure_Call) RunAndReturn(run func() bool) *MockWebClientMiddlewareInterface_CookieSecure_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLoginSession provides a mock function for the type MockWebClientMiddlewareInterface
func (_mock *MockWebClientMiddlewareInterface) CreateLoginSession(ctx context.Context, userID int64, rememberMe bool, userAgent string, ip string) (string, int, error) {
	ret := _mock.Called(ctx, userID, rememberMe, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoginSession")
	}

	var r0 string
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool, string, string) (string, int, error)); ok {
		return returnFunc(ctx, userID, rememberMe, userAgent, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool, string, string) string); ok {
		r0 = returnFunc(ctx, userID, rememberMe, userAgent, ip)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool, string, string) int); ok {
		r1 = returnFunc(ctx, userID, rememberMe, userAgent, ip)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, bool, string, string) error); ok {
		r2 = returnFunc(ctx, userID, rememberMe, userAgent, ip)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWebClientMiddlewareInterface_CreateLoginSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLoginSession'
type MockWebClientMiddlewareInterface_CreateLoginSession_Call struct {
	*mock.Call
}

// CreateLoginSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - rememberMe bool
//   - userAgent string
//   - ip string
func (_e *MockWebClientMiddlewareInterface_Expecter) CreateLoginSession(ctx interface{}, userID interface{}, rememberMe interface{}, userAgent interface{}, ip interface{}) *MockWebClientMiddlewareInterface_CreateLoginSession_Call {
	return &MockWebClientMiddlewareInterface_CreateLoginSession_Call{Call: _e.mock.On("CreateLoginSession", ctx, userID, rememberMe, userAgent, ip)}
}

func (_c *MockWebClientMiddlewareInterface_CreateLoginSession_Call) Run(run func(ctx context.Context, userID int64, rememberMe bool, userAgent string, ip string)) *MockWebClientMiddlewareInterface_CreateLoginSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CreateLoginSession_Call) Return(s string, n int, err error) *MockWebClientMiddlewareInterface_CreateLoginSession_Call {
	_c.Call.Return(s, n, err)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_CreateLoginSession_Call) RunAndReturn(run func(ctx context.Context, userID int64, rememberMe bool, userAgent string, ip string) (string, int, error)) *MockWebClientMiddlewareInterface_CreateLoginSession_Call {
	_c.Call.Return(run)
	return _c
}

// DestroySession provides a mock function for the type MockWebClientMiddlewareInterface
func (_mock *MockWebClientMiddlewareInterface) DestroySession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DestroySession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebClientMiddlewareInterface_DestroySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroySession'
type MockWebClientMiddlewareInterface_DestroySession_Call struct {
	*mock.Call
}

// DestroySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockWebClientMiddlewareInterface_Expecter) DestroySession(ctx interface{}, sessionID interface{}) *MockWebClientMiddlewareInterface_DestroySession_Call {
	return &MockWebClientMiddlewareInterface_DestroySession_Call{Call: _e.mock.On("DestroySession", ctx, sessionID)}
}

func (_c *MockWebClientMiddlewareInterface_DestroySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockWebClientMiddlewareInterface_DestroySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_DestroySession_Call) Return(err error) *MockWebClientMiddlewareInterface_DestroySession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_DestroySession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockWebClientMiddlewareInterface_DestroySession_Call {
	_c.Call.Return(run)
	return _c
}

// ErrorLogger provides a mock function for the type MockWebClientMiddlewareInterface
func (_mock *MockWebClientMiddlewareInterface) ErrorLogger() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorLogger")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockWebClientMiddlewareInterface_ErrorLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorLogger'
type MockWebClientMiddlewareInterface_ErrorLogger_Call struct {
	*mock.Call
}

// ErrorLogger is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) ErrorLogger() *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	return &MockWebClientMiddlewareInterface_ErrorLogger_Call{Call: _e.mock.On("ErrorLogger")}
}

func (_c *MockWebClientMiddlewareInterface_ErrorLogger_Call) Run(run func()) *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_ErrorLogger_Call) Return(handlerFunc gin.HandlerFunc) *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_ErrorLogger_Call) RunAndReturn(run func() gin.HandlerFunc) *MockWebClientMiddlewareInterface_ErrorLogger_Call {
	_c.Call.Return(run)
	return _c
}

// WebClientAuthentication provides a mock function for the type MockWebClientMiddlewareInterface
func (_mock *MockWebClientMiddlewareInterface) WebClientAuthentication() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebClientAuthentication")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockWebClientMiddlewareInterface_WebClientAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebClientAuthentication'
type MockWebClientMiddlewareInterface_WebClientAuthentication_Call struct {
	*mock.Call
}

// WebClientAuthentication is a helper method to define mock.On call
func (_e *MockWebClientMiddlewareInterface_Expecter) WebClientAuthentication() *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	return &MockWebClientMiddlewareInterface_WebClientAuthentication_Call{Call: _e.mock.On("WebClientAuthentication")}
}

func (_c *MockWebClientMiddlewareInterface_WebClientAuthentication_Call) Run(run func()) *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebClientMiddlewareInterface_WebClientAuthentication_Call) Return(handlerFunc gin.HandlerFunc) *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockWebClientMiddlewareInterface_WebClientAuthentication_Call) RunAndReturn(run func() gin.HandlerFunc) *MockWebClientMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Return(run)
	return _c
}
