// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRulesServiceInterface creates a new instance of MockRulesServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRulesServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRulesServiceInterface {
	mock := &MockRulesServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRulesServiceInterface is an autogenerated mock type for the RulesServiceInterface type
type MockRulesServiceInterface struct {
	mock.Mock
}

type MockRulesServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRulesServiceInterface) EXPECT() *MockRulesServiceInterface_Expecter {
	return &MockRulesServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteRule provides a mock function for the type MockRulesServiceInterface
func (_mock *MockRulesServiceInterface) DeleteRule(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRulesServiceInterface_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockRulesServiceInterface_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockRulesServiceInterface_Expecter) DeleteRule(ctx any, userID any, id any) *MockRulesServiceInterface_DeleteRule_Call {
	return &MockRulesServiceInterface_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, userID, id)}
}

func (_c *MockRulesServiceInterface_DeleteRule_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockRulesServiceInterface_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRulesServiceInterface_DeleteRule_Call) Return(err error) *MockRulesServiceInterface_DeleteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRulesServiceInterface_DeleteRule_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockRulesServiceInterface_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchApplyRules provides a mock function for the type MockRulesServiceInterface
func (_mock *MockRulesServiceInterface) DispatchApplyRules(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DispatchApplyRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRulesServiceInterface_DispatchApplyRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchApplyRules'
type MockRulesServiceInterface_DispatchApplyRules_Call struct {
	*mock.Call
}

// DispatchApplyRules is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRulesServiceInterface_Expecter) DispatchApplyRules(ctx any, userID any) *MockRulesServiceInterface_DispatchApplyRules_Call {
	return &MockRulesServiceInterface_DispatchApplyRules_Call{Call: _e.mock.On("DispatchApplyRules", ctx, userID)}
}

func (_c *MockRulesServiceInterface_DispatchApplyRules_Call) Run(run func(ctx context.Context, userID int64)) *MockRulesServiceInterface_DispatchApplyRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRulesServiceInterface_DispatchApplyRules_Call) Return(err error) *MockRulesServiceInterface_DispatchApplyRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRulesServiceInterface_DispatchApplyRules_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockRulesServiceInterface_DispatchApplyRules_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRuleByID provides a mock function for the type MockRulesServiceInterface
func (_mock *MockRulesServiceInterface) FetchRuleByID(ctx context.Context, userID int64, id int64) (*models.Rule, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchRuleByID")
	}

	var r0 *models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.Rule, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.Rule); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesServiceInterface_FetchRuleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRuleByID'
type MockRulesServiceInterface_FetchRuleByID_Call struct {
	*mock.Call
}

// FetchRuleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockRulesServiceInterface_Expecter) FetchRuleByID(ctx any, userID any, id any) *MockRulesServiceInterface_FetchRuleByID_Call {
	return &MockRulesServiceInterface_FetchRuleByID_Call{Call: _e.mock.On("FetchRuleByID", ctx, userID, id)}
}

func (_c *MockRulesServiceInterface_FetchRuleByID_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockRulesServiceInterface_FetchRuleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRulesServiceInterface_FetchRuleByID_Call) Return(rule *models.Rule, err error) *MockRulesServiceInterface_FetchRuleByID_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockRulesServiceInterface_FetchRuleByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (*models.Rule, error)) *MockRulesServiceInterface_FetchRuleByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRules provides a mock function for the type MockRulesServiceInterface
func (_mock *MockRulesServiceInterface) FetchRules(ctx context.Context, userID int64) ([]models.Rule, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchRules")
	}

	var r0 []models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.Rule, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.Rule); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesServiceInterface_FetchRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRules'
type MockRulesServiceInterface_FetchRules_Call struct {
	*mock.Call
}

// FetchRules is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRulesServiceInterface_Expecter) FetchRules(ctx any, userID any) *MockRulesServiceInterface_FetchRules_Call {
	return &MockRulesServiceInterface_FetchRules_Call{Call: _e.mock.On("FetchRules", ctx, userID)}
}

func (_c *MockRulesServiceInterface_FetchRules_Call) Run(run func(ctx context.Context, userID int64)) *MockRulesServiceInterface_FetchRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRulesServiceInterface_FetchRules_Call) Return(rules []models.Rule, err error) *MockRulesServiceInterface_FetchRules_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockRulesServiceInterface_FetchRules_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.Rule, error)) *MockRulesServiceInterface_FetchRules_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRule provides a mock function for the type MockRulesServiceInterface
func (_mock *MockRulesServiceInterface) InsertRule(ctx context.Context, userID int64, req *models.RuleReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertRule")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.RuleReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.RuleReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.RuleReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesServiceInterface_InsertRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRule'
type MockRulesServiceInterface_InsertRule_Call struct {
	*mock.Call
}

// InsertRule is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.RuleReq
func (_e *MockRulesServiceInterface_Expecter) InsertRule(ctx any, userID any, req any) *MockRulesServiceInterface_InsertRule_Call {
	return &MockRulesServiceInterface_InsertRule_Call{Call: _e.mock.On("InsertRule", ctx, userID, req)}
}

func (_c *MockRulesServiceInterface_InsertRule_Call) Run(run func(ctx context.Context, userID int64, req *models.RuleReq)) *MockRulesServiceInterface_InsertRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.RuleReq
		if args[2] != nil {
			arg2 = args[2].(*models.RuleReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRulesServiceInterface_InsertRule_Call) Return(n int64, err error) *MockRulesServiceInterface_InsertRule_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRulesServiceInterface_InsertRule_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.RuleReq) (int64, error)) *MockRulesServiceInterface_InsertRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function for the type MockRulesServiceInterface
func (_mock *MockRulesServiceInterface) UpdateRule(ctx context.Context, userID int64, id int64, req *models.RuleReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.RuleReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.RuleReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.RuleReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesServiceInterface_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockRulesServiceInterface_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.RuleReq
func (_e *MockRulesServiceInterface_Expecter) UpdateRule(ctx any, userID any, id any, req any) *MockRulesServiceInterface_UpdateRule_Call {
	return &MockRulesServiceInterface_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, userID, id, req)}
}

func (_c *MockRulesServiceInterface_UpdateRule_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.RuleReq)) *MockRulesServiceInterface_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.RuleReq
		if args[3] != nil {
			arg3 = args[3].(*models.RuleReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRulesServiceInterface_UpdateRule_Call) Return(n int64, err error) *MockRulesServiceInterface_UpdateRule_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRulesServiceInterface_UpdateRule_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.RuleReq) (int64, error)) *MockRulesServiceInterface_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}
