// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"
	"wealth-warden/pkg/utils"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTransactionServiceInterface creates a new instance of MockTransactionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionServiceInterface {
	mock := &MockTransactionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionServiceInterface is an autogenerated mock type for the TransactionServiceInterface type
type MockTransactionServiceInterface struct {
	mock.Mock
}

type MockTransactionServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionServiceInterface) EXPECT() *MockTransactionServiceInterface_Expecter {
	return &MockTransactionServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteCategory provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) DeleteCategory(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockTransactionServiceInterface_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) DeleteCategory(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_DeleteCategory_Call {
	return &MockTransactionServiceInterface_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_DeleteCategory_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteCategory_Call) Return(err error) *MockTransactionServiceInterface_DeleteCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteCategory_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategoryGroup provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) DeleteCategoryGroup(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategoryGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_DeleteCategoryGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategoryGroup'
type MockTransactionServiceInterface_DeleteCategoryGroup_Call struct {
	*mock.Call
}

// DeleteCategoryGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) DeleteCategoryGroup(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_DeleteCategoryGroup_Call {
	return &MockTransactionServiceInterface_DeleteCategoryGroup_Call{Call: _e.mock.On("DeleteCategoryGroup", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_DeleteCategoryGroup_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_DeleteCategoryGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteCategoryGroup_Call) Return(err error) *MockTransactionServiceInterface_DeleteCategoryGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteCategoryGroup_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_DeleteCategoryGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransaction provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) DeleteTransaction(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_DeleteTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransaction'
type MockTransactionServiceInterface_DeleteTransaction_Call struct {
	*mock.Call
}

// DeleteTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) DeleteTransaction(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_DeleteTransaction_Call {
	return &MockTransactionServiceInterface_DeleteTransaction_Call{Call: _e.mock.On("DeleteTransaction", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_DeleteTransaction_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_DeleteTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteTransaction_Call) Return(err error) *MockTransactionServiceInterface_DeleteTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteTransaction_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_DeleteTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransactionTemplate provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) DeleteTransactionTemplate(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransactionTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_DeleteTransactionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransactionTemplate'
type MockTransactionServiceInterface_DeleteTransactionTemplate_Call struct {
	*mock.Call
}

// DeleteTransactionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) DeleteTransactionTemplate(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_DeleteTransactionTemplate_Call {
	return &MockTransactionServiceInterface_DeleteTransactionTemplate_Call{Call: _e.mock.On("DeleteTransactionTemplate", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_DeleteTransactionTemplate_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_DeleteTransactionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteTransactionTemplate_Call) Return(err error) *MockTransactionServiceInterface_DeleteTransactionTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteTransactionTemplate_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_DeleteTransactionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransfer provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) DeleteTransfer(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_DeleteTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransfer'
type MockTransactionServiceInterface_DeleteTransfer_Call struct {
	*mock.Call
}

// DeleteTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) DeleteTransfer(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_DeleteTransfer_Call {
	return &MockTransactionServiceInterface_DeleteTransfer_Call{Call: _e.mock.On("DeleteTransfer", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_DeleteTransfer_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_DeleteTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteTransfer_Call) Return(err error) *MockTransactionServiceInterface_DeleteTransfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_DeleteTransfer_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_DeleteTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllCategories provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchAllCategories(ctx context.Context, userID int64, includeDeleted bool) ([]models.Category, error) {
	ret := _mock.Called(ctx, userID, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllCategories")
	}

	var r0 []models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) ([]models.Category, error)); ok {
		return returnFunc(ctx, userID, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) []models.Category); ok {
		r0 = returnFunc(ctx, userID, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllCategories'
type MockTransactionServiceInterface_FetchAllCategories_Call struct {
	*mock.Call
}

// FetchAllCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - includeDeleted bool
func (_e *MockTransactionServiceInterface_Expecter) FetchAllCategories(ctx interface{}, userID interface{}, includeDeleted interface{}) *MockTransactionServiceInterface_FetchAllCategories_Call {
	return &MockTransactionServiceInterface_FetchAllCategories_Call{Call: _e.mock.On("FetchAllCategories", ctx, userID, includeDeleted)}
}

func (_c *MockTransactionServiceInterface_FetchAllCategories_Call) Run(run func(ctx context.Context, userID int64, includeDeleted bool)) *MockTransactionServiceInterface_FetchAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchAllCategories_Call) Return(categorys []models.Category, err error) *MockTransactionServiceInterface_FetchAllCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchAllCategories_Call) RunAndReturn(run func(ctx context.Context, userID int64, includeDeleted bool) ([]models.Category, error)) *MockTransactionServiceInterface_FetchAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllCategoriesWithGroups provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchAllCategoriesWithGroups(ctx context.Context, userID int64) ([]models.CategoryOrGroup, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllCategoriesWithGroups")
	}

	var r0 []models.CategoryOrGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.CategoryOrGroup, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.CategoryOrGroup); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CategoryOrGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllCategoriesWithGroups'
type MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call struct {
	*mock.Call
}

// FetchAllCategoriesWithGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTransactionServiceInterface_Expecter) FetchAllCategoriesWithGroups(ctx interface{}, userID interface{}) *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call {
	return &MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call{Call: _e.mock.On("FetchAllCategoriesWithGroups", ctx, userID)}
}

func (_c *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call) Run(run func(ctx context.Context, userID int64)) *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call) Return(categoryOrGroups []models.CategoryOrGroup, err error) *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call {
	_c.Call.Return(categoryOrGroups, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.CategoryOrGroup, error)) *MockTransactionServiceInterface_FetchAllCategoriesWithGroups_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAllCategoryGroups provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchAllCategoryGroups(ctx context.Context, userID int64) ([]models.CategoryGroup, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllCategoryGroups")
	}

	var r0 []models.CategoryGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.CategoryGroup, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.CategoryGroup); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CategoryGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchAllCategoryGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAllCategoryGroups'
type MockTransactionServiceInterface_FetchAllCategoryGroups_Call struct {
	*mock.Call
}

// FetchAllCategoryGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTransactionServiceInterface_Expecter) FetchAllCategoryGroups(ctx interface{}, userID interface{}) *MockTransactionServiceInterface_FetchAllCategoryGroups_Call {
	return &MockTransactionServiceInterface_FetchAllCategoryGroups_Call{Call: _e.mock.On("FetchAllCategoryGroups", ctx, userID)}
}

func (_c *MockTransactionServiceInterface_FetchAllCategoryGroups_Call) Run(run func(ctx context.Context, userID int64)) *MockTransactionServiceInterface_FetchAllCategoryGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchAllCategoryGroups_Call) Return(categoryGroups []models.CategoryGroup, err error) *MockTransactionServiceInterface_FetchAllCategoryGroups_Call {
	_c.Call.Return(categoryGroups, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchAllCategoryGroups_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.CategoryGroup, error)) *MockTransactionServiceInterface_FetchAllCategoryGroups_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCategoryByID provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchCategoryByID(ctx context.Context, userID int64, id int64, includeDeleted bool) (*models.Category, error) {
	ret := _mock.Called(ctx, userID, id, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for FetchCategoryByID")
	}

	var r0 *models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, bool) (*models.Category, error)); ok {
		return returnFunc(ctx, userID, id, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, bool) *models.Category); ok {
		r0 = returnFunc(ctx, userID, id, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, id, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCategoryByID'
type MockTransactionServiceInterface_FetchCategoryByID_Call struct {
	*mock.Call
}

// FetchCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - includeDeleted bool
func (_e *MockTransactionServiceInterface_Expecter) FetchCategoryByID(ctx interface{}, userID interface{}, id interface{}, includeDeleted interface{}) *MockTransactionServiceInterface_FetchCategoryByID_Call {
	return &MockTransactionServiceInterface_FetchCategoryByID_Call{Call: _e.mock.On("FetchCategoryByID", ctx, userID, id, includeDeleted)}
}

func (_c *MockTransactionServiceInterface_FetchCategoryByID_Call) Run(run func(ctx context.Context, userID int64, id int64, includeDeleted bool)) *MockTransactionServiceInterface_FetchCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchCategoryByID_Call) Return(category *models.Category, err error) *MockTransactionServiceInterface_FetchCategoryByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchCategoryByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, includeDeleted bool) (*models.Category, error)) *MockTransactionServiceInterface_FetchCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchCategoryGroupByID provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchCategoryGroupByID(ctx context.Context, userID int64, id int64) (*models.CategoryGroup, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchCategoryGroupByID")
	}

	var r0 *models.CategoryGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.CategoryGroup, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.CategoryGroup); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CategoryGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchCategoryGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCategoryGroupByID'
type MockTransactionServiceInterface_FetchCategoryGroupByID_Call struct {
	*mock.Call
}

// FetchCategoryGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) FetchCategoryGroupByID(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_FetchCategoryGroupByID_Call {
	return &MockTransactionServiceInterface_FetchCategoryGroupByID_Call{Call: _e.mock.On("FetchCategoryGroupByID", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_FetchCategoryGroupByID_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_FetchCategoryGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchCategoryGroupByID_Call) Return(categoryGroup *models.CategoryGroup, err error) *MockTransactionServiceInterface_FetchCategoryGroupByID_Call {
	_c.Call.Return(categoryGroup, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchCategoryGroupByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (*models.CategoryGroup, error)) *MockTransactionServiceInterface_FetchCategoryGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchTransactionByID provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchTransactionByID(ctx context.Context, userID int64, id int64, includeDeleted bool) (*models.Transaction, error) {
	ret := _mock.Called(ctx, userID, id, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactionByID")
	}

	var r0 *models.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, bool) (*models.Transaction, error)); ok {
		return returnFunc(ctx, userID, id, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, bool) *models.Transaction); ok {
		r0 = returnFunc(ctx, userID, id, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, id, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchTransactionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTransactionByID'
type MockTransactionServiceInterface_FetchTransactionByID_Call struct {
	*mock.Call
}

// FetchTransactionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - includeDeleted bool
func (_e *MockTransactionServiceInterface_Expecter) FetchTransactionByID(ctx interface{}, userID interface{}, id interface{}, includeDeleted interface{}) *MockTransactionServiceInterface_FetchTransactionByID_Call {
	return &MockTransactionServiceInterface_FetchTransactionByID_Call{Call: _e.mock.On("FetchTransactionByID", ctx, userID, id, includeDeleted)}
}

func (_c *MockTransactionServiceInterface_FetchTransactionByID_Call) Run(run func(ctx context.Context, userID int64, id int64, includeDeleted bool)) *MockTransactionServiceInterface_FetchTransactionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionByID_Call) Return(transaction *models.Transaction, err error) *MockTransactionServiceInterface_FetchTransactionByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, includeDeleted bool) (*models.Transaction, error)) *MockTransactionServiceInterface_FetchTransactionByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchTransactionTemplateByID provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchTransactionTemplateByID(ctx context.Context, userID int64, id int64) (*models.TransactionTemplate, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactionTemplateByID")
	}

	var r0 *models.TransactionTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.TransactionTemplate, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.TransactionTemplate); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TransactionTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_FetchTransactionTemplateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTransactionTemplateByID'
type MockTransactionServiceInterface_FetchTransactionTemplateByID_Call struct {
	*mock.Call
}

// FetchTransactionTemplateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) FetchTransactionTemplateByID(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call {
	return &MockTransactionServiceInterface_FetchTransactionTemplateByID_Call{Call: _e.mock.On("FetchTransactionTemplateByID", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call) Return(transactionTemplate *models.TransactionTemplate, err error) *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call {
	_c.Call.Return(transactionTemplate, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (*models.TransactionTemplate, error)) *MockTransactionServiceInterface_FetchTransactionTemplateByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchTransactionTemplatesPaginated provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchTransactionTemplatesPaginated(ctx context.Context, userID int64, p utils.PaginationParams, templateType string) ([]models.TransactionTemplate, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, p, templateType)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactionTemplatesPaginated")
	}

	var r0 []models.TransactionTemplate
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, string) ([]models.TransactionTemplate, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, p, templateType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, string) []models.TransactionTemplate); ok {
		r0 = returnFunc(ctx, userID, p, templateType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TransactionTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, utils.PaginationParams, string) *utils.Paginator); ok {
		r1 = returnFunc(ctx, userID, p, templateType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, utils.PaginationParams, string) error); ok {
		r2 = returnFunc(ctx, userID, p, templateType)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTransactionTemplatesPaginated'
type MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call struct {
	*mock.Call
}

// FetchTransactionTemplatesPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p utils.PaginationParams
//   - templateType string
func (_e *MockTransactionServiceInterface_Expecter) FetchTransactionTemplatesPaginated(ctx interface{}, userID interface{}, p interface{}, templateType interface{}) *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call {
	return &MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call{Call: _e.mock.On("FetchTransactionTemplatesPaginated", ctx, userID, p, templateType)}
}

func (_c *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call) Run(run func(ctx context.Context, userID int64, p utils.PaginationParams, templateType string)) *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 utils.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(utils.PaginationParams)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call) Return(transactionTemplates []models.TransactionTemplate, paginator *utils.Paginator, err error) *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call {
	_c.Call.Return(transactionTemplates, paginator, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, p utils.PaginationParams, templateType string) ([]models.TransactionTemplate, *utils.Paginator, error)) *MockTransactionServiceInterface_FetchTransactionTemplatesPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FetchTransactionsPaginated provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchTransactionsPaginated(ctx context.Context, userID int64, p utils.PaginationParams, includeDeleted bool, accountID *int64) ([]models.Transaction, *models.TransactionBatchTotals, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, p, includeDeleted, accountID)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactionsPaginated")
	}

	var r0 []models.Transaction
	var r1 *models.TransactionBatchTotals
	var r2 *utils.Paginator
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, bool, *int64) ([]models.Transaction, *models.TransactionBatchTotals, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, p, includeDeleted, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, bool, *int64) []models.Transaction); ok {
		r0 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, utils.PaginationParams, bool, *int64) *models.TransactionBatchTotals); ok {
		r1 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.TransactionBatchTotals)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, utils.PaginationParams, bool, *int64) *utils.Paginator); ok {
		r2 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, int64, utils.PaginationParams, bool, *int64) error); ok {
		r3 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockTransactionServiceInterface_FetchTransactionsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTransactionsPaginated'
type MockTransactionServiceInterface_FetchTransactionsPaginated_Call struct {
	*mock.Call
}

// FetchTransactionsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p utils.PaginationParams
//   - includeDeleted bool
//   - accountID *int64
func (_e *MockTransactionServiceInterface_Expecter) FetchTransactionsPaginated(ctx interface{}, userID interface{}, p interface{}, includeDeleted interface{}, accountID interface{}) *MockTransactionServiceInterface_FetchTransactionsPaginated_Call {
	return &MockTransactionServiceInterface_FetchTransactionsPaginated_Call{Call: _e.mock.On("FetchTransactionsPaginated", ctx, userID, p, includeDeleted, accountID)}
}

func (_c *MockTransactionServiceInterface_FetchTransactionsPaginated_Call) Run(run func(ctx context.Context, userID int64, p utils.PaginationParams, includeDeleted bool, accountID *int64)) *MockTransactionServiceInterface_FetchTransactionsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 utils.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(utils.PaginationParams)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionsPaginated_Call) Return(transactions []models.Transaction, transactionBatchTotals *models.TransactionBatchTotals, paginator *utils.Paginator, err error) *MockTransactionServiceInterface_FetchTransactionsPaginated_Call {
	_c.Call.Return(transactions, transactionBatchTotals, paginator, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransactionsPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, p utils.PaginationParams, includeDeleted bool, accountID *int64) ([]models.Transaction, *models.TransactionBatchTotals, *utils.Paginator, error)) *MockTransactionServiceInterface_FetchTransactionsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FetchTransfersPaginated provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) FetchTransfersPaginated(ctx context.Context, userID int64, p utils.PaginationParams, includeDeleted bool, accountID *int64) ([]models.Transfer, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, p, includeDeleted, accountID)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransfersPaginated")
	}

	var r0 []models.Transfer
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, bool, *int64) ([]models.Transfer, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, p, includeDeleted, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, utils.PaginationParams, bool, *int64) []models.Transfer); ok {
		r0 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, utils.PaginationParams, bool, *int64) *utils.Paginator); ok {
		r1 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, utils.PaginationParams, bool, *int64) error); ok {
		r2 = returnFunc(ctx, userID, p, includeDeleted, accountID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionServiceInterface_FetchTransfersPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTransfersPaginated'
type MockTransactionServiceInterface_FetchTransfersPaginated_Call struct {
	*mock.Call
}

// FetchTransfersPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p utils.PaginationParams
//   - includeDeleted bool
//   - accountID *int64
func (_e *MockTransactionServiceInterface_Expecter) FetchTransfersPaginated(ctx interface{}, userID interface{}, p interface{}, includeDeleted interface{}, accountID interface{}) *MockTransactionServiceInterface_FetchTransfersPaginated_Call {
	return &MockTransactionServiceInterface_FetchTransfersPaginated_Call{Call: _e.mock.On("FetchTransfersPaginated", ctx, userID, p, includeDeleted, accountID)}
}

func (_c *MockTransactionServiceInterface_FetchTransfersPaginated_Call) Run(run func(ctx context.Context, userID int64, p utils.PaginationParams, includeDeleted bool, accountID *int64)) *MockTransactionServiceInterface_FetchTransfersPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 utils.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(utils.PaginationParams)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransfersPaginated_Call) Return(transfers []models.Transfer, paginator *utils.Paginator, err error) *MockTransactionServiceInterface_FetchTransfersPaginated_Call {
	_c.Call.Return(transfers, paginator, err)
	return _c
}

func (_c *MockTransactionServiceInterface_FetchTransfersPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, p utils.PaginationParams, includeDeleted bool, accountID *int64) ([]models.Transfer, *utils.Paginator, error)) *MockTransactionServiceInterface_FetchTransfersPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateSummary provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) GetTemplateSummary(ctx context.Context, userID int64) (*models.TemplateSummary, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateSummary")
	}

	var r0 *models.TemplateSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.TemplateSummary, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.TemplateSummary); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TemplateSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_GetTemplateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateSummary'
type MockTransactionServiceInterface_GetTemplateSummary_Call struct {
	*mock.Call
}

// GetTemplateSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTransactionServiceInterface_Expecter) GetTemplateSummary(ctx interface{}, userID interface{}) *MockTransactionServiceInterface_GetTemplateSummary_Call {
	return &MockTransactionServiceInterface_GetTemplateSummary_Call{Call: _e.mock.On("GetTemplateSummary", ctx, userID)}
}

func (_c *MockTransactionServiceInterface_GetTemplateSummary_Call) Run(run func(ctx context.Context, userID int64)) *MockTransactionServiceInterface_GetTemplateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_GetTemplateSummary_Call) Return(templateSummary *models.TemplateSummary, err error) *MockTransactionServiceInterface_GetTemplateSummary_Call {
	_c.Call.Return(templateSummary, err)
	return _c
}

func (_c *MockTransactionServiceInterface_GetTemplateSummary_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*models.TemplateSummary, error)) *MockTransactionServiceInterface_GetTemplateSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplatesReadyToRun provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) GetTemplatesReadyToRun(ctx context.Context, tx *gorm.DB) ([]*models.TransactionTemplate, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplatesReadyToRun")
	}

	var r0 []*models.TransactionTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]*models.TransactionTemplate, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB) []*models.TransactionTemplate); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TransactionTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_GetTemplatesReadyToRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplatesReadyToRun'
type MockTransactionServiceInterface_GetTemplatesReadyToRun_Call struct {
	*mock.Call
}

// GetTemplatesReadyToRun is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
func (_e *MockTransactionServiceInterface_Expecter) GetTemplatesReadyToRun(ctx interface{}, tx interface{}) *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call {
	return &MockTransactionServiceInterface_GetTemplatesReadyToRun_Call{Call: _e.mock.On("GetTemplatesReadyToRun", ctx, tx)}
}

func (_c *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call) Run(run func(ctx context.Context, tx *gorm.DB)) *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call) Return(transactionTemplates []*models.TransactionTemplate, err error) *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call {
	_c.Call.Return(transactionTemplates, err)
	return _c
}

func (_c *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB) ([]*models.TransactionTemplate, error)) *MockTransactionServiceInterface_GetTemplatesReadyToRun_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionTemplateCount provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) GetTransactionTemplateCount(ctx context.Context, userID int64, templateType string) (int64, error) {
	ret := _mock.Called(ctx, userID, templateType)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionTemplateCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (int64, error)); ok {
		return returnFunc(ctx, userID, templateType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) int64); ok {
		r0 = returnFunc(ctx, userID, templateType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, templateType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_GetTransactionTemplateCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionTemplateCount'
type MockTransactionServiceInterface_GetTransactionTemplateCount_Call struct {
	*mock.Call
}

// GetTransactionTemplateCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - templateType string
func (_e *MockTransactionServiceInterface_Expecter) GetTransactionTemplateCount(ctx interface{}, userID interface{}, templateType interface{}) *MockTransactionServiceInterface_GetTransactionTemplateCount_Call {
	return &MockTransactionServiceInterface_GetTransactionTemplateCount_Call{Call: _e.mock.On("GetTransactionTemplateCount", ctx, userID, templateType)}
}

func (_c *MockTransactionServiceInterface_GetTransactionTemplateCount_Call) Run(run func(ctx context.Context, userID int64, templateType string)) *MockTransactionServiceInterface_GetTransactionTemplateCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_GetTransactionTemplateCount_Call) Return(n int64, err error) *MockTransactionServiceInterface_GetTransactionTemplateCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_GetTransactionTemplateCount_Call) RunAndReturn(run func(ctx context.Context, userID int64, templateType string) (int64, error)) *MockTransactionServiceInterface_GetTransactionTemplateCount_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCategory provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) InsertCategory(ctx context.Context, userID int64, req *models.CategoryReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertCategory")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.CategoryReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.CategoryReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.CategoryReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_InsertCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCategory'
type MockTransactionServiceInterface_InsertCategory_Call struct {
	*mock.Call
}

// InsertCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.CategoryReq
func (_e *MockTransactionServiceInterface_Expecter) InsertCategory(ctx interface{}, userID interface{}, req interface{}) *MockTransactionServiceInterface_InsertCategory_Call {
	return &MockTransactionServiceInterface_InsertCategory_Call{Call: _e.mock.On("InsertCategory", ctx, userID, req)}
}

func (_c *MockTransactionServiceInterface_InsertCategory_Call) Run(run func(ctx context.Context, userID int64, req *models.CategoryReq)) *MockTransactionServiceInterface_InsertCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.CategoryReq
		if args[2] != nil {
			arg2 = args[2].(*models.CategoryReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_InsertCategory_Call) Return(n int64, err error) *MockTransactionServiceInterface_InsertCategory_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_InsertCategory_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.CategoryReq) (int64, error)) *MockTransactionServiceInterface_InsertCategory_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCategoryGroup provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) InsertCategoryGroup(ctx context.Context, userID int64, req *models.CategoryGroupReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertCategoryGroup")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.CategoryGroupReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.CategoryGroupReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.CategoryGroupReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_InsertCategoryGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCategoryGroup'
type MockTransactionServiceInterface_InsertCategoryGroup_Call struct {
	*mock.Call
}

// InsertCategoryGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.CategoryGroupReq
func (_e *MockTransactionServiceInterface_Expecter) InsertCategoryGroup(ctx interface{}, userID interface{}, req interface{}) *MockTransactionServiceInterface_InsertCategoryGroup_Call {
	return &MockTransactionServiceInterface_InsertCategoryGroup_Call{Call: _e.mock.On("InsertCategoryGroup", ctx, userID, req)}
}

func (_c *MockTransactionServiceInterface_InsertCategoryGroup_Call) Run(run func(ctx context.Context, userID int64, req *models.CategoryGroupReq)) *MockTransactionServiceInterface_InsertCategoryGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.CategoryGroupReq
		if args[2] != nil {
			arg2 = args[2].(*models.CategoryGroupReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_InsertCategoryGroup_Call) Return(n int64, err error) *MockTransactionServiceInterface_InsertCategoryGroup_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_InsertCategoryGroup_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.CategoryGroupReq) (int64, error)) *MockTransactionServiceInterface_InsertCategoryGroup_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransaction provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) InsertTransaction(ctx context.Context, userID int64, req *models.TransactionReq, existingTx ...*gorm.DB) (models.InsertResult, error) {
	var tmpRet mock.Arguments
	if len(existingTx) > 0 {
		tmpRet = _mock.Called(ctx, userID, req, existingTx)
	} else {
		tmpRet = _mock.Called(ctx, userID, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertTransaction")
	}

	var r0 models.InsertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.TransactionReq, ...*gorm.DB) (models.InsertResult, error)); ok {
		return returnFunc(ctx, userID, req, existingTx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.TransactionReq, ...*gorm.DB) models.InsertResult); ok {
		r0 = returnFunc(ctx, userID, req, existingTx...)
	} else {
		r0 = ret.Get(0).(models.InsertResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.TransactionReq, ...*gorm.DB) error); ok {
		r1 = returnFunc(ctx, userID, req, existingTx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_InsertTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransaction'
type MockTransactionServiceInterface_InsertTransaction_Call struct {
	*mock.Call
}

// InsertTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.TransactionReq
//   - existingTx ...*gorm.DB
func (_e *MockTransactionServiceInterface_Expecter) InsertTransaction(ctx interface{}, userID interface{}, req interface{}, existingTx ...interface{}) *MockTransactionServiceInterface_InsertTransaction_Call {
	return &MockTransactionServiceInterface_InsertTransaction_Call{Call: _e.mock.On("InsertTransaction",
		append([]interface{}{ctx, userID, req}, existingTx...)...)}
}

func (_c *MockTransactionServiceInterface_InsertTransaction_Call) Run(run func(ctx context.Context, userID int64, req *models.TransactionReq, existingTx ...*gorm.DB)) *MockTransactionServiceInterface_InsertTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.TransactionReq
		if args[2] != nil {
			arg2 = args[2].(*models.TransactionReq)
		}
		var arg3 []*gorm.DB
		var variadicArgs []*gorm.DB
		if len(args) > 3 {
			variadicArgs = args[3].([]*gorm.DB)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_InsertTransaction_Call) Return(insertResult models.InsertResult, err error) *MockTransactionServiceInterface_InsertTransaction_Call {
	_c.Call.Return(insertResult, err)
	return _c
}

func (_c *MockTransactionServiceInterface_InsertTransaction_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.TransactionReq, existingTx ...*gorm.DB) (models.InsertResult, error)) *MockTransactionServiceInterface_InsertTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransactionTemplate provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) InsertTransactionTemplate(ctx context.Context, userID int64, req *models.TransactionTemplateReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransactionTemplate")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.TransactionTemplateReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.TransactionTemplateReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.TransactionTemplateReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_InsertTransactionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransactionTemplate'
type MockTransactionServiceInterface_InsertTransactionTemplate_Call struct {
	*mock.Call
}

// InsertTransactionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.TransactionTemplateReq
func (_e *MockTransactionServiceInterface_Expecter) InsertTransactionTemplate(ctx interface{}, userID interface{}, req interface{}) *MockTransactionServiceInterface_InsertTransactionTemplate_Call {
	return &MockTransactionServiceInterface_InsertTransactionTemplate_Call{Call: _e.mock.On("InsertTransactionTemplate", ctx, userID, req)}
}

func (_c *MockTransactionServiceInterface_InsertTransactionTemplate_Call) Run(run func(ctx context.Context, userID int64, req *models.TransactionTemplateReq)) *MockTransactionServiceInterface_InsertTransactionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.TransactionTemplateReq
		if args[2] != nil {
			arg2 = args[2].(*models.TransactionTemplateReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_InsertTransactionTemplate_Call) Return(n int64, err error) *MockTransactionServiceInterface_InsertTransactionTemplate_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_InsertTransactionTemplate_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.TransactionTemplateReq) (int64, error)) *MockTransactionServiceInterface_InsertTransactionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransfer provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) InsertTransfer(ctx context.Context, userID int64, req *models.TransferReq) (models.InsertResult, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransfer")
	}

	var r0 models.InsertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.TransferReq) (models.InsertResult, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.TransferReq) models.InsertResult); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(models.InsertResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.TransferReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_InsertTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransfer'
type MockTransactionServiceInterface_InsertTransfer_Call struct {
	*mock.Call
}

// InsertTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.TransferReq
func (_e *MockTransactionServiceInterface_Expecter) InsertTransfer(ctx interface{}, userID interface{}, req interface{}) *MockTransactionServiceInterface_InsertTransfer_Call {
	return &MockTransactionServiceInterface_InsertTransfer_Call{Call: _e.mock.On("InsertTransfer", ctx, userID, req)}
}

func (_c *MockTransactionServiceInterface_InsertTransfer_Call) Run(run func(ctx context.Context, userID int64, req *models.TransferReq)) *MockTransactionServiceInterface_InsertTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.TransferReq
		if args[2] != nil {
			arg2 = args[2].(*models.TransferReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_InsertTransfer_Call) Return(insertResult models.InsertResult, err error) *MockTransactionServiceInterface_InsertTransfer_Call {
	_c.Call.Return(insertResult, err)
	return _c
}

func (_c *MockTransactionServiceInterface_InsertTransfer_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.TransferReq) (models.InsertResult, error)) *MockTransactionServiceInterface_InsertTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessTemplate provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) ProcessTemplate(ctx context.Context, template *models.TransactionTemplate) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TransactionTemplate) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_ProcessTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTemplate'
type MockTransactionServiceInterface_ProcessTemplate_Call struct {
	*mock.Call
}

// ProcessTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template *models.TransactionTemplate
func (_e *MockTransactionServiceInterface_Expecter) ProcessTemplate(ctx interface{}, template interface{}) *MockTransactionServiceInterface_ProcessTemplate_Call {
	return &MockTransactionServiceInterface_ProcessTemplate_Call{Call: _e.mock.On("ProcessTemplate", ctx, template)}
}

func (_c *MockTransactionServiceInterface_ProcessTemplate_Call) Run(run func(ctx context.Context, template *models.TransactionTemplate)) *MockTransactionServiceInterface_ProcessTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.TransactionTemplate
		if args[1] != nil {
			arg1 = args[1].(*models.TransactionTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_ProcessTemplate_Call) Return(err error) *MockTransactionServiceInterface_ProcessTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_ProcessTemplate_Call) RunAndReturn(run func(ctx context.Context, template *models.TransactionTemplate) error) *MockTransactionServiceInterface_ProcessTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCategory provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) RestoreCategory(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_RestoreCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCategory'
type MockTransactionServiceInterface_RestoreCategory_Call struct {
	*mock.Call
}

// RestoreCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) RestoreCategory(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_RestoreCategory_Call {
	return &MockTransactionServiceInterface_RestoreCategory_Call{Call: _e.mock.On("RestoreCategory", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_RestoreCategory_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_RestoreCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_RestoreCategory_Call) Return(err error) *MockTransactionServiceInterface_RestoreCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_RestoreCategory_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_RestoreCategory_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCategoryName provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) RestoreCategoryName(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCategoryName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_RestoreCategoryName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCategoryName'
type MockTransactionServiceInterface_RestoreCategoryName_Call struct {
	*mock.Call
}

// RestoreCategoryName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) RestoreCategoryName(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_RestoreCategoryName_Call {
	return &MockTransactionServiceInterface_RestoreCategoryName_Call{Call: _e.mock.On("RestoreCategoryName", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_RestoreCategoryName_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_RestoreCategoryName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_RestoreCategoryName_Call) Return(err error) *MockTransactionServiceInterface_RestoreCategoryName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_RestoreCategoryName_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_RestoreCategoryName_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreTransaction provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) RestoreTransaction(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_RestoreTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreTransaction'
type MockTransactionServiceInterface_RestoreTransaction_Call struct {
	*mock.Call
}

// RestoreTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) RestoreTransaction(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_RestoreTransaction_Call {
	return &MockTransactionServiceInterface_RestoreTransaction_Call{Call: _e.mock.On("RestoreTransaction", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_RestoreTransaction_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_RestoreTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_RestoreTransaction_Call) Return(err error) *MockTransactionServiceInterface_RestoreTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_RestoreTransaction_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_RestoreTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleTransactionTemplateActiveState provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) ToggleTransactionTemplateActiveState(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleTransactionTemplateActiveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleTransactionTemplateActiveState'
type MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call struct {
	*mock.Call
}

// ToggleTransactionTemplateActiveState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockTransactionServiceInterface_Expecter) ToggleTransactionTemplateActiveState(ctx interface{}, userID interface{}, id interface{}) *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call {
	return &MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call{Call: _e.mock.On("ToggleTransactionTemplateActiveState", ctx, userID, id)}
}

func (_c *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call) Return(err error) *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockTransactionServiceInterface_ToggleTransactionTemplateActiveState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) UpdateCategory(ctx context.Context, userID int64, id int64, req *models.CategoryReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.CategoryReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.CategoryReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.CategoryReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockTransactionServiceInterface_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.CategoryReq
func (_e *MockTransactionServiceInterface_Expecter) UpdateCategory(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockTransactionServiceInterface_UpdateCategory_Call {
	return &MockTransactionServiceInterface_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", ctx, userID, id, req)}
}

func (_c *MockTransactionServiceInterface_UpdateCategory_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.CategoryReq)) *MockTransactionServiceInterface_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.CategoryReq
		if args[3] != nil {
			arg3 = args[3].(*models.CategoryReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateCategory_Call) Return(n int64, err error) *MockTransactionServiceInterface_UpdateCategory_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateCategory_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.CategoryReq) (int64, error)) *MockTransactionServiceInterface_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategoryGroup provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) UpdateCategoryGroup(ctx context.Context, userID int64, id int64, req *models.CategoryGroupReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategoryGroup")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.CategoryGroupReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.CategoryGroupReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.CategoryGroupReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_UpdateCategoryGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategoryGroup'
type MockTransactionServiceInterface_UpdateCategoryGroup_Call struct {
	*mock.Call
}

// UpdateCategoryGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.CategoryGroupReq
func (_e *MockTransactionServiceInterface_Expecter) UpdateCategoryGroup(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockTransactionServiceInterface_UpdateCategoryGroup_Call {
	return &MockTransactionServiceInterface_UpdateCategoryGroup_Call{Call: _e.mock.On("UpdateCategoryGroup", ctx, userID, id, req)}
}

func (_c *MockTransactionServiceInterface_UpdateCategoryGroup_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.CategoryGroupReq)) *MockTransactionServiceInterface_UpdateCategoryGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.CategoryGroupReq
		if args[3] != nil {
			arg3 = args[3].(*models.CategoryGroupReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateCategoryGroup_Call) Return(n int64, err error) *MockTransactionServiceInterface_UpdateCategoryGroup_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateCategoryGroup_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.CategoryGroupReq) (int64, error)) *MockTransactionServiceInterface_UpdateCategoryGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransaction provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) UpdateTransaction(ctx context.Context, userID int64, id int64, req *models.TransactionReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.TransactionReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.TransactionReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.TransactionReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_UpdateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransaction'
type MockTransactionServiceInterface_UpdateTransaction_Call struct {
	*mock.Call
}

// UpdateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.TransactionReq
func (_e *MockTransactionServiceInterface_Expecter) UpdateTransaction(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockTransactionServiceInterface_UpdateTransaction_Call {
	return &MockTransactionServiceInterface_UpdateTransaction_Call{Call: _e.mock.On("UpdateTransaction", ctx, userID, id, req)}
}

func (_c *MockTransactionServiceInterface_UpdateTransaction_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.TransactionReq)) *MockTransactionServiceInterface_UpdateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.TransactionReq
		if args[3] != nil {
			arg3 = args[3].(*models.TransactionReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateTransaction_Call) Return(n int64, err error) *MockTransactionServiceInterface_UpdateTransaction_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateTransaction_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.TransactionReq) (int64, error)) *MockTransactionServiceInterface_UpdateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransactionTemplate provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) UpdateTransactionTemplate(ctx context.Context, userID int64, id int64, req *models.TransactionTemplateReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionTemplate")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.TransactionTemplateReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.TransactionTemplateReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.TransactionTemplateReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionServiceInterface_UpdateTransactionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransactionTemplate'
type MockTransactionServiceInterface_UpdateTransactionTemplate_Call struct {
	*mock.Call
}

// UpdateTransactionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.TransactionTemplateReq
func (_e *MockTransactionServiceInterface_Expecter) UpdateTransactionTemplate(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockTransactionServiceInterface_UpdateTransactionTemplate_Call {
	return &MockTransactionServiceInterface_UpdateTransactionTemplate_Call{Call: _e.mock.On("UpdateTransactionTemplate", ctx, userID, id, req)}
}

func (_c *MockTransactionServiceInterface_UpdateTransactionTemplate_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.TransactionTemplateReq)) *MockTransactionServiceInterface_UpdateTransactionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.TransactionTemplateReq
		if args[3] != nil {
			arg3 = args[3].(*models.TransactionTemplateReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateTransactionTemplate_Call) Return(n int64, err error) *MockTransactionServiceInterface_UpdateTransactionTemplate_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateTransactionTemplate_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.TransactionTemplateReq) (int64, error)) *MockTransactionServiceInterface_UpdateTransactionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransfer provides a mock function for the type MockTransactionServiceInterface
func (_mock *MockTransactionServiceInterface) UpdateTransfer(ctx context.Context, userID int64, id int64, req *models.UpdateTransferReq) error {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.UpdateTransferReq) error); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionServiceInterface_UpdateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransfer'
type MockTransactionServiceInterface_UpdateTransfer_Call struct {
	*mock.Call
}

// UpdateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.UpdateTransferReq
func (_e *MockTransactionServiceInterface_Expecter) UpdateTransfer(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockTransactionServiceInterface_UpdateTransfer_Call {
	return &MockTransactionServiceInterface_UpdateTransfer_Call{Call: _e.mock.On("UpdateTransfer", ctx, userID, id, req)}
}

func (_c *MockTransactionServiceInterface_UpdateTransfer_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.UpdateTransferReq)) *MockTransactionServiceInterface_UpdateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.UpdateTransferReq
		if args[3] != nil {
			arg3 = args[3].(*models.UpdateTransferReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateTransfer_Call) Return(err error) *MockTransactionServiceInterface_UpdateTransfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionServiceInterface_UpdateTransfer_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.UpdateTransferReq) error) *MockTransactionServiceInterface_UpdateTransfer_Call {
	_c.Call.Return(run)
	return _c
}
