// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"wealth-warden/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionsServiceInterface creates a new instance of MockSessionsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsServiceInterface {
	mock := &MockSessionsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionsServiceInterface is an autogenerated mock type for the SessionsServiceInterface type
type MockSessionsServiceInterface struct {
	mock.Mock
}

type MockSessionsServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsServiceInterface) EXPECT() *MockSessionsServiceInterface_Expecter {
	return &MockSessionsServiceInterface_Expecter{mock: &_m.Mock}
}

// ListSessions provides a mock function for the type MockSessionsServiceInterface
func (_mock *MockSessionsServiceInterface) ListSessions(ctx context.Context, userID int64, currentSessionID string) ([]models.SessionInfo, error) {
	ret := _mock.Called(ctx, userID, currentSessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []models.SessionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]models.SessionInfo, error)); ok {
		return returnFunc(ctx, userID, currentSessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []models.SessionInfo); ok {
		r0 = returnFunc(ctx, userID, currentSessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SessionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, currentSessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsServiceInterface_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockSessionsServiceInterface_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currentSessionID string
func (_e *MockSessionsServiceInterface_Expecter) ListSessions(ctx interface{}, userID interface{}, currentSessionID interface{}) *MockSessionsServiceInterface_ListSessions_Call {
	return &MockSessionsServiceInterface_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, userID, currentSessionID)}
}

func (_c *MockSessionsServiceInterface_ListSessions_Call) Run(run func(ctx context.Context, userID int64, currentSessionID string)) *MockSessionsServiceInterface_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionsServiceInterface_ListSessions_Call) Return(sessionInfos []models.SessionInfo, err error) *MockSessionsServiceInterface_ListSessions_Call {
	_c.Call.Return(sessionInfos, err)
	return _c
}

func (_c *MockSessionsServiceInterface_ListSessions_Call) RunAndReturn(run func(ctx context.Context, userID int64, currentSessionID string) ([]models.SessionInfo, error)) *MockSessionsServiceInterface_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessions provides a mock function for the type MockSessionsServiceInterface
func (_mock *MockSessionsServiceInterface) RevokeAllSessions(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsServiceInterface_RevokeAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessions'
type MockSessionsServiceInterface_RevokeAllSessions_Call struct {
	*mock.Call
}

// RevokeAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockSessionsServiceInterface_Expecter) RevokeAllSessions(ctx interface{}, userID interface{}) *MockSessionsServiceInterface_RevokeAllSessions_Call {
	return &MockSessionsServiceInterface_RevokeAllSessions_Call{Call: _e.mock.On("RevokeAllSessions", ctx, userID)}
}

func (_c *MockSessionsServiceInterface_RevokeAllSessions_Call) Run(run func(ctx context.Context, userID int64)) *MockSessionsServiceInterface_RevokeAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsServiceInterface_RevokeAllSessions_Call) Return(err error) *MockSessionsServiceInterface_RevokeAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsServiceInterface_RevokeAllSessions_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockSessionsServiceInterface_RevokeAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockSessionsServiceInterface
func (_mock *MockSessionsServiceInterface) RevokeSession(ctx context.Context, userID int64, currentSessionID string, handle string) error {
	ret := _mock.Called(ctx, userID, currentSessionID, handle)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentSessionID, handle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsServiceInterface_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionsServiceInterface_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currentSessionID string
//   - handle string
func (_e *MockSessionsServiceInterface_Expecter) RevokeSession(ctx interface{}, userID interface{}, currentSessionID interface{}, handle interface{}) *MockSessionsServiceInterface_RevokeSession_Call {
	return &MockSessionsServiceInterface_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, userID, currentSessionID, handle)}
}

func (_c *MockSessionsServiceInterface_RevokeSession_Call) Run(run func(ctx context.Context, userID int64, currentSessionID string, handle string)) *MockSessionsServiceInterface_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionsServiceInterface_RevokeSession_Call) Return(err error) *MockSessionsServiceInterface_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsServiceInterface_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, userID int64, currentSessionID string, handle string) error) *MockSessionsServiceInterface_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}
