// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"wealth-warden/internal/models"
	"wealth-warden/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSavingsServiceInterface creates a new instance of MockSavingsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSavingsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSavingsServiceInterface {
	mock := &MockSavingsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSavingsServiceInterface is an autogenerated mock type for the SavingsServiceInterface type
type MockSavingsServiceInterface struct {
	mock.Mock
}

type MockSavingsServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSavingsServiceInterface) EXPECT() *MockSavingsServiceInterface_Expecter {
	return &MockSavingsServiceInterface_Expecter{mock: &_m.Mock}
}

// AutoFundGoal provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) AutoFundGoal(ctx context.Context, goal models.SavingGoal, month time.Time) (bool, string, error) {
	ret := _mock.Called(ctx, goal, month)

	if len(ret) == 0 {
		panic("no return value specified for AutoFundGoal")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SavingGoal, time.Time) (bool, string, error)); ok {
		return returnFunc(ctx, goal, month)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SavingGoal, time.Time) bool); ok {
		r0 = returnFunc(ctx, goal, month)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.SavingGoal, time.Time) string); ok {
		r1 = returnFunc(ctx, goal, month)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, models.SavingGoal, time.Time) error); ok {
		r2 = returnFunc(ctx, goal, month)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSavingsServiceInterface_AutoFundGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoFundGoal'
type MockSavingsServiceInterface_AutoFundGoal_Call struct {
	*mock.Call
}

// AutoFundGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - goal models.SavingGoal
//   - month time.Time
func (_e *MockSavingsServiceInterface_Expecter) AutoFundGoal(ctx any, goal any, month any) *MockSavingsServiceInterface_AutoFundGoal_Call {
	return &MockSavingsServiceInterface_AutoFundGoal_Call{Call: _e.mock.On("AutoFundGoal", ctx, goal, month)}
}

func (_c *MockSavingsServiceInterface_AutoFundGoal_Call) Run(run func(ctx context.Context, goal models.SavingGoal, month time.Time)) *MockSavingsServiceInterface_AutoFundGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SavingGoal
		if args[1] != nil {
			arg1 = args[1].(models.SavingGoal)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_AutoFundGoal_Call) Return(funded bool, skipReason string, err error) *MockSavingsServiceInterface_AutoFundGoal_Call {
	_c.Call.Return(funded, skipReason, err)
	return _c
}

func (_c *MockSavingsServiceInterface_AutoFundGoal_Call) RunAndReturn(run func(ctx context.Context, goal models.SavingGoal, month time.Time) (bool, string, error)) *MockSavingsServiceInterface_AutoFundGoal_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteContribution provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) DeleteContribution(ctx context.Context, userID int64, goalID int64, id int64) error {
	ret := _mock.Called(ctx, userID, goalID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContribution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, goalID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavingsServiceInterface_DeleteContribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteContribution'
type MockSavingsServiceInterface_DeleteContribution_Call struct {
	*mock.Call
}

// DeleteContribution is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - goalID int64
//   - id int64
func (_e *MockSavingsServiceInterface_Expecter) DeleteContribution(ctx any, userID any, goalID any, id any) *MockSavingsServiceInterface_DeleteContribution_Call {
	return &MockSavingsServiceInterface_DeleteContribution_Call{Call: _e.mock.On("DeleteContribution", ctx, userID, goalID, id)}
}

func (_c *MockSavingsServiceInterface_DeleteContribution_Call) Run(run func(ctx context.Context, userID int64, goalID int64, id int64)) *MockSavingsServiceInterface_DeleteContribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_DeleteContribution_Call) Return(err error) *MockSavingsServiceInterface_DeleteContribution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavingsServiceInterface_DeleteContribution_Call) RunAndReturn(run func(ctx context.Context, userID int64, goalID int64, id int64) error) *MockSavingsServiceInterface_DeleteContribution_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGoal provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) DeleteGoal(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGoal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavingsServiceInterface_DeleteGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGoal'
type MockSavingsServiceInterface_DeleteGoal_Call struct {
	*mock.Call
}

// DeleteGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockSavingsServiceInterface_Expecter) DeleteGoal(ctx any, userID any, id any) *MockSavingsServiceInterface_DeleteGoal_Call {
	return &MockSavingsServiceInterface_DeleteGoal_Call{Call: _e.mock.On("DeleteGoal", ctx, userID, id)}
}

func (_c *MockSavingsServiceInterface_DeleteGoal_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockSavingsServiceInterface_DeleteGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_DeleteGoal_Call) Return(err error) *MockSavingsServiceInterface_DeleteGoal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavingsServiceInterface_DeleteGoal_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *MockSavingsServiceInterface_DeleteGoal_Call {
	_c.Call.Return(run)
	return _c
}

// FetchActiveGoalsWithAllocation provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) FetchActiveGoalsWithAllocation(ctx context.Context, dayOfMonth int) ([]models.SavingGoal, error) {
	ret := _mock.Called(ctx, dayOfMonth)

	if len(ret) == 0 {
		panic("no return value specified for FetchActiveGoalsWithAllocation")
	}

	var r0 []models.SavingGoal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.SavingGoal, error)); ok {
		return returnFunc(ctx, dayOfMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.SavingGoal); ok {
		r0 = returnFunc(ctx, dayOfMonth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SavingGoal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, dayOfMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchActiveGoalsWithAllocation'
type MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call struct {
	*mock.Call
}

// FetchActiveGoalsWithAllocation is a helper method to define mock.On call
//   - ctx context.Context
//   - dayOfMonth int
func (_e *MockSavingsServiceInterface_Expecter) FetchActiveGoalsWithAllocation(ctx any, dayOfMonth any) *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call {
	return &MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call{Call: _e.mock.On("FetchActiveGoalsWithAllocation", ctx, dayOfMonth)}
}

func (_c *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call) Run(run func(ctx context.Context, dayOfMonth int)) *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call) Return(savingGoals []models.SavingGoal, err error) *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call {
	_c.Call.Return(savingGoals, err)
	return _c
}

func (_c *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call) RunAndReturn(run func(ctx context.Context, dayOfMonth int) ([]models.SavingGoal, error)) *MockSavingsServiceInterface_FetchActiveGoalsWithAllocation_Call {
	_c.Call.Return(run)
	return _c
}

// FetchContributionsPaginated provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) FetchContributionsPaginated(ctx context.Context, userID int64, goalID int64, p utils.PaginationParams) ([]models.SavingContribution, *utils.Paginator, error) {
	ret := _mock.Called(ctx, userID, goalID, p)

	if len(ret) == 0 {
		panic("no return value specified for FetchContributionsPaginated")
	}

	var r0 []models.SavingContribution
	var r1 *utils.Paginator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, utils.PaginationParams) ([]models.SavingContribution, *utils.Paginator, error)); ok {
		return returnFunc(ctx, userID, goalID, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, utils.PaginationParams) []models.SavingContribution); ok {
		r0 = returnFunc(ctx, userID, goalID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SavingContribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, utils.PaginationParams) *utils.Paginator); ok {
		r1 = returnFunc(ctx, userID, goalID, p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.Paginator)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, int64, utils.PaginationParams) error); ok {
		r2 = returnFunc(ctx, userID, goalID, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSavingsServiceInterface_FetchContributionsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchContributionsPaginated'
type MockSavingsServiceInterface_FetchContributionsPaginated_Call struct {
	*mock.Call
}

// FetchContributionsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - goalID int64
//   - p utils.PaginationParams
func (_e *MockSavingsServiceInterface_Expecter) FetchContributionsPaginated(ctx any, userID any, goalID any, p any) *MockSavingsServiceInterface_FetchContributionsPaginated_Call {
	return &MockSavingsServiceInterface_FetchContributionsPaginated_Call{Call: _e.mock.On("FetchContributionsPaginated", ctx, userID, goalID, p)}
}

func (_c *MockSavingsServiceInterface_FetchContributionsPaginated_Call) Run(run func(ctx context.Context, userID int64, goalID int64, p utils.PaginationParams)) *MockSavingsServiceInterface_FetchContributionsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 utils.PaginationParams
		if args[3] != nil {
			arg3 = args[3].(utils.PaginationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_FetchContributionsPaginated_Call) Return(savingContributions []models.SavingContribution, paginator *utils.Paginator, err error) *MockSavingsServiceInterface_FetchContributionsPaginated_Call {
	_c.Call.Return(savingContributions, paginator, err)
	return _c
}

func (_c *MockSavingsServiceInterface_FetchContributionsPaginated_Call) RunAndReturn(run func(ctx context.Context, userID int64, goalID int64, p utils.PaginationParams) ([]models.SavingContribution, *utils.Paginator, error)) *MockSavingsServiceInterface_FetchContributionsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FetchGoalByID provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) FetchGoalByID(ctx context.Context, userID int64, id int64) (*models.SavingGoalWithProgress, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchGoalByID")
	}

	var r0 *models.SavingGoalWithProgress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.SavingGoalWithProgress, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.SavingGoalWithProgress); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SavingGoalWithProgress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsServiceInterface_FetchGoalByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchGoalByID'
type MockSavingsServiceInterface_FetchGoalByID_Call struct {
	*mock.Call
}

// FetchGoalByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockSavingsServiceInterface_Expecter) FetchGoalByID(ctx any, userID any, id any) *MockSavingsServiceInterface_FetchGoalByID_Call {
	return &MockSavingsServiceInterface_FetchGoalByID_Call{Call: _e.mock.On("FetchGoalByID", ctx, userID, id)}
}

func (_c *MockSavingsServiceInterface_FetchGoalByID_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockSavingsServiceInterface_FetchGoalByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_FetchGoalByID_Call) Return(savingGoalWithProgress *models.SavingGoalWithProgress, err error) *MockSavingsServiceInterface_FetchGoalByID_Call {
	_c.Call.Return(savingGoalWithProgress, err)
	return _c
}

func (_c *MockSavingsServiceInterface_FetchGoalByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (*models.SavingGoalWithProgress, error)) *MockSavingsServiceInterface_FetchGoalByID_Call {
	_c.Call.Return(run)
	return _c
}

// FetchGoals provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) FetchGoals(ctx context.Context, userID int64) ([]models.SavingGoalWithProgress, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchGoals")
	}

	var r0 []models.SavingGoalWithProgress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.SavingGoalWithProgress, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.SavingGoalWithProgress); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SavingGoalWithProgress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsServiceInterface_FetchGoals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchGoals'
type MockSavingsServiceInterface_FetchGoals_Call struct {
	*mock.Call
}

// FetchGoals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockSavingsServiceInterface_Expecter) FetchGoals(ctx any, userID any) *MockSavingsServiceInterface_FetchGoals_Call {
	return &MockSavingsServiceInterface_FetchGoals_Call{Call: _e.mock.On("FetchGoals", ctx, userID)}
}

func (_c *MockSavingsServiceInterface_FetchGoals_Call) Run(run func(ctx context.Context, userID int64)) *MockSavingsServiceInterface_FetchGoals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_FetchGoals_Call) Return(savingGoalWithProgresss []models.SavingGoalWithProgress, err error) *MockSavingsServiceInterface_FetchGoals_Call {
	_c.Call.Return(savingGoalWithProgresss, err)
	return _c
}

func (_c *MockSavingsServiceInterface_FetchGoals_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.SavingGoalWithProgress, error)) *MockSavingsServiceInterface_FetchGoals_Call {
	_c.Call.Return(run)
	return _c
}

// FundGoalNow provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) FundGoalNow(ctx context.Context, userID int64, goalID int64) error {
	ret := _mock.Called(ctx, userID, goalID)

	if len(ret) == 0 {
		panic("no return value specified for FundGoalNow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, goalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavingsServiceInterface_FundGoalNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundGoalNow'
type MockSavingsServiceInterface_FundGoalNow_Call struct {
	*mock.Call
}

// FundGoalNow is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - goalID int64
func (_e *MockSavingsServiceInterface_Expecter) FundGoalNow(ctx any, userID any, goalID any) *MockSavingsServiceInterface_FundGoalNow_Call {
	return &MockSavingsServiceInterface_FundGoalNow_Call{Call: _e.mock.On("FundGoalNow", ctx, userID, goalID)}
}

func (_c *MockSavingsServiceInterface_FundGoalNow_Call) Run(run func(ctx context.Context, userID int64, goalID int64)) *MockSavingsServiceInterface_FundGoalNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_FundGoalNow_Call) Return(err error) *MockSavingsServiceInterface_FundGoalNow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavingsServiceInterface_FundGoalNow_Call) RunAndReturn(run func(ctx context.Context, userID int64, goalID int64) error) *MockSavingsServiceInterface_FundGoalNow_Call {
	_c.Call.Return(run)
	return _c
}

// InsertContribution provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) InsertContribution(ctx context.Context, userID int64, goalID int64, req *models.SavingContributionReq) (int64, error) {
	ret := _mock.Called(ctx, userID, goalID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertContribution")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.SavingContributionReq) (int64, error)); ok {
		return returnFunc(ctx, userID, goalID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.SavingContributionReq) int64); ok {
		r0 = returnFunc(ctx, userID, goalID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.SavingContributionReq) error); ok {
		r1 = returnFunc(ctx, userID, goalID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsServiceInterface_InsertContribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertContribution'
type MockSavingsServiceInterface_InsertContribution_Call struct {
	*mock.Call
}

// InsertContribution is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - goalID int64
//   - req *models.SavingContributionReq
func (_e *MockSavingsServiceInterface_Expecter) InsertContribution(ctx any, userID any, goalID any, req any) *MockSavingsServiceInterface_InsertContribution_Call {
	return &MockSavingsServiceInterface_InsertContribution_Call{Call: _e.mock.On("InsertContribution", ctx, userID, goalID, req)}
}

func (_c *MockSavingsServiceInterface_InsertContribution_Call) Run(run func(ctx context.Context, userID int64, goalID int64, req *models.SavingContributionReq)) *MockSavingsServiceInterface_InsertContribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.SavingContributionReq
		if args[3] != nil {
			arg3 = args[3].(*models.SavingContributionReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_InsertContribution_Call) Return(n int64, err error) *MockSavingsServiceInterface_InsertContribution_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSavingsServiceInterface_InsertContribution_Call) RunAndReturn(run func(ctx context.Context, userID int64, goalID int64, req *models.SavingContributionReq) (int64, error)) *MockSavingsServiceInterface_InsertContribution_Call {
	_c.Call.Return(run)
	return _c
}

// InsertGoal provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) InsertGoal(ctx context.Context, userID int64, req *models.SavingGoalReq) (int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertGoal")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.SavingGoalReq) (int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *models.SavingGoalReq) int64); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *models.SavingGoalReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsServiceInterface_InsertGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertGoal'
type MockSavingsServiceInterface_InsertGoal_Call struct {
	*mock.Call
}

// InsertGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *models.SavingGoalReq
func (_e *MockSavingsServiceInterface_Expecter) InsertGoal(ctx any, userID any, req any) *MockSavingsServiceInterface_InsertGoal_Call {
	return &MockSavingsServiceInterface_InsertGoal_Call{Call: _e.mock.On("InsertGoal", ctx, userID, req)}
}

func (_c *MockSavingsServiceInterface_InsertGoal_Call) Run(run func(ctx context.Context, userID int64, req *models.SavingGoalReq)) *MockSavingsServiceInterface_InsertGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *models.SavingGoalReq
		if args[2] != nil {
			arg2 = args[2].(*models.SavingGoalReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_InsertGoal_Call) Return(n int64, err error) *MockSavingsServiceInterface_InsertGoal_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSavingsServiceInterface_InsertGoal_Call) RunAndReturn(run func(ctx context.Context, userID int64, req *models.SavingGoalReq) (int64, error)) *MockSavingsServiceInterface_InsertGoal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGoal provides a mock function for the type MockSavingsServiceInterface
func (_mock *MockSavingsServiceInterface) UpdateGoal(ctx context.Context, userID int64, id int64, req *models.SavingGoalUpdateReq) (int64, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGoal")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.SavingGoalUpdateReq) (int64, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, *models.SavingGoalUpdateReq) int64); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, *models.SavingGoalUpdateReq) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsServiceInterface_UpdateGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGoal'
type MockSavingsServiceInterface_UpdateGoal_Call struct {
	*mock.Call
}

// UpdateGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - req *models.SavingGoalUpdateReq
func (_e *MockSavingsServiceInterface_Expecter) UpdateGoal(ctx any, userID any, id any, req any) *MockSavingsServiceInterface_UpdateGoal_Call {
	return &MockSavingsServiceInterface_UpdateGoal_Call{Call: _e.mock.On("UpdateGoal", ctx, userID, id, req)}
}

func (_c *MockSavingsServiceInterface_UpdateGoal_Call) Run(run func(ctx context.Context, userID int64, id int64, req *models.SavingGoalUpdateReq)) *MockSavingsServiceInterface_UpdateGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *models.SavingGoalUpdateReq
		if args[3] != nil {
			arg3 = args[3].(*models.SavingGoalUpdateReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSavingsServiceInterface_UpdateGoal_Call) Return(n int64, err error) *MockSavingsServiceInterface_UpdateGoal_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSavingsServiceInterface_UpdateGoal_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, req *models.SavingGoalUpdateReq) (int64, error)) *MockSavingsServiceInterface_UpdateGoal_Call {
	_c.Call.Return(run)
	return _c
}
